pages:
  image: python:3.11
  script:
    # 1. Installer les dépendances doc
    - pip install mkdocs mkdocs-material mkdocstrings[python]

    # 2. Installer le package (nécessaire pour mkdocstrings + hooks.py)
    - pip install -e .

    # 3. Générer les .md API
    - python utils/docs/ci_generate.py

    # 4. Compiler → dossier public/
    - mkdocs build --site-dir public

  artifacts:
    paths:
      - public

  only:
    - main
