# This file is AUTO-GENERATED by utils/generator/main.py
# DO NOT EDIT MANUALLY — run the generator to regenerate.
#  Generator author: Clement RACINET
"""
RWS module: RobotWare Services → IO Service → Get IO System resources

1:1 mirror of the ABB RobotWare 6 REST API.
Each function maps to exactly one HTTP endpoint.
No composed logic — see highlevel/ for wrappers.
"""
from __future__ import annotations

import httpx

from abb_rws_client_python_rw6.core.client import RWSClient


async def get_io_system_resources(client: RWSClient) -> httpx.Response:
    """
    Get IO System resources.

    Route: ``GET /rw/iosystem``
    ABB constraints: Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD REQUEST(400)

    Example:
        ```python
        >>> await get_io_system_resources(client)
        <Response [200]>
        ```
    """
    return await client.get("/rw/iosystem")

async def get_io_network(
    client: RWSClient,
    network: str,
) -> httpx.Response:
    """
    Get IO Network.

    Route: ``GET /rw/iosystem/networks/{network}``
    ABB constraints: Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        network: URL path parameter.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD REQUEST(400)

    Example:
        ```python
        >>> await get_io_network(client, "network_value")
        <Response [200]>
        ```
    """
    return await client.get(f"/rw/iosystem/networks/{network}")

async def get_io_network_actions(
    client: RWSClient,
    network: str,
    action: str | None = None,
) -> httpx.Response:
    """
    Get IO Network actions.

    Route: ``GET /rw/iosystem/networks/{network}``
    ABB constraints: Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        network: URL path parameter.
        action: Query parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD REQUEST(400)

    Example:
        ```python
        >>> await get_io_network_actions(client, "network_value")
        <Response [200]>
        ```
    """
    return await client.get(
        f"/rw/iosystem/networks/{network}",
        params={k: v for k, v in {"action": action}.items() if v is not None},
    )

async def update_io_network(
    client: RWSClient,
    network: str,
    action: str | None = None,
    lstate: str | None = None,
) -> httpx.Response:
    """
    Update IO Network.

    Route: ``POST /rw/iosystem/networks/{network}``
    ABB constraints: Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        network: URL path parameter.
        action: Query parameter. Optional.
        lstate: Body parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 204.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD REQUEST(400)

    Example:
        ```python
        >>> await update_io_network(client, "network_value")
        <Response [204]>
        ```
    """
    return await client.post(
        f"/rw/iosystem/networks/{network}",
        params={k: v for k, v in {"action": action}.items() if v is not None},
        data={k: v for k, v in {"lstate": lstate}.items() if v is not None},
    )

async def subscribe_io_network(
    client: RWSClient,
    identifier: str | None = None,
    identifier_p: str | None = None,
) -> httpx.Response:
    """
    Subscribe IO Network.

    Route: ``POST /subscription``
    ABB constraints: Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        identifier: Body parameter. Optional.
        identifier_p: Body parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 201.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD REQUEST(400)

    Example:
        ```python
        >>> await subscribe_io_network(client)
        <Response [201]>
        ```
    """
    return await client.post(
        "/subscription",
        data={
            k: v
            for k, v in {
                "identifier": identifier,
                "identifier_p": identifier_p
            }.items()
            if v is not None
        },
    )

async def get_io_network_configuration_properties(
    client: RWSClient,
    network: str,
    resource: str | None = None,
    configtype: str | None = None,
) -> httpx.Response:
    """
    Get IO Network Configuration Properties.

    Route: ``GET /rw/iosystem/networks/{network}``
    ABB constraints: "configtype_value" should be 1 (or) 2 (or) 3 (2= general configuration , 1 =
        runtime configuration, 3 = both) Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        network: URL path parameter.
        resource: Query parameter. Optional.
        configtype: Query parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD REQUEST(400)

    Example:
        ```python
        >>> await get_io_network_configuration_properties(client, "network_value")
        <Response [200]>
        ```
    """
    return await client.get(
        f"/rw/iosystem/networks/{network}",
        params={
            k: v
            for k, v in {
                "resource": resource,
                "configtype": configtype
            }.items()
            if v is not None
        },
    )

async def update_io_network_configuration_type(
    client: RWSClient,
    network: str,
    action: str | None = None,
    config_type: str | None = None,
) -> httpx.Response:
    """
    Update IO Network Configuration Type.

    Route: ``POST /rw/iosystem/networks/{network}``
    ABB constraints: Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        network: URL path parameter.
        action: Query parameter. Optional.
        config_type: Body parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 204.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD_REQUEST(400)

    Example:
        ```python
        >>> await update_io_network_configuration_type(client, "network_value")
        <Response [204]>
        ```
    """
    return await client.post(
        f"/rw/iosystem/networks/{network}",
        params={k: v for k, v in {"action": action}.items() if v is not None},
        data={k: v for k, v in {"config_type": config_type}.items() if v is not None},
    )

async def get_io_device(
    client: RWSClient,
    device: str,
) -> httpx.Response:
    """
    Get IO Device.

    Route: ``GET /rw/iosystem/devices/{device}``
    ABB constraints: Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        device: URL path parameter.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD_REQUEST(400)

    Example:
        ```python
        >>> await get_io_device(client, "device_value")
        <Response [200]>
        ```
    """
    return await client.get(f"/rw/iosystem/devices/{device}")

async def get_io_device_actions(
    client: RWSClient,
    device: str,
    action: str | None = None,
) -> httpx.Response:
    """
    Get IO Device actions.

    Route: ``GET /rw/iosystem/devices/{device}``
    ABB constraints: Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        device: URL path parameter.
        action: Query parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD REQUEST(400)

    Example:
        ```python
        >>> await get_io_device_actions(client, "device_value")
        <Response [200]>
        ```
    """
    return await client.get(
        f"/rw/iosystem/devices/{device}",
        params={k: v for k, v in {"action": action}.items() if v is not None},
    )

async def update_io_device(
    client: RWSClient,
    device: str,
    action: str | None = None,
    lstate: str | None = None,
) -> httpx.Response:
    """
    Update IO Device.

    Route: ``POST /rw/iosystem/devices/{device}``
    ABB constraints: Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        device: URL path parameter.
        action: Query parameter. Optional.
        lstate: Body parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 204.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD REQUEST(400)

    Example:
        ```python
        >>> await update_io_device(client, "device_value")
        <Response [204]>
        ```
    """
    return await client.post(
        f"/rw/iosystem/devices/{device}",
        params={k: v for k, v in {"action": action}.items() if v is not None},
        data={k: v for k, v in {"lstate": lstate}.items() if v is not None},
    )

async def subscribe_io_device(
    client: RWSClient,
    identifier: str | None = None,
    identifier_p: str | None = None,
) -> httpx.Response:
    """
    Subscribe IO Device.

    Route: ``POST /subscription``
    ABB constraints: Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        identifier: Body parameter. Optional.
        identifier_p: Body parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 201.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD REQUEST(400)

    Example:
        ```python
        >>> await subscribe_io_device(client)
        <Response [201]>
        ```
    """
    return await client.post(
        "/subscription",
        data={
            k: v
            for k, v in {
                "identifier": identifier,
                "identifier_p": identifier_p
            }.items()
            if v is not None
        },
    )

async def set_input_data(
    client: RWSClient,
    device: str,
    action: str | None = None,
    startbyte: str | None = None,
    signaldata: str | None = None,
    datamask: str | None = None,
) -> httpx.Response:
    """
    Set input data.

    Route: ``POST /rw/iosystem/devices/{device}``
    ABB constraints: Only supported in Virtual Controller. If input data is 4 bytes long, start
        byte can have values ranging from 0 to 3. Datamask/signal data can have values ranging
        from 0 to 255 (since it is accessed as 1 byte long). If datamask/signal data is greater
        than 255 (1 byte long), only first 8 bits is us...

    Args:
        client: Open RWSClient instance.
        device: URL path parameter.
        action: Query parameter. Optional.
        startbyte: Body parameter. Optional.
        signaldata: Body parameter. Optional.
        datamask: Body parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 204.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD_REQUEST(400), UNSUPPORTED_MEDIA(415)

    Example:
        ```python
        >>> await set_input_data(client, "device_value")
        <Response [204]>
        ```
    """
    return await client.post(
        f"/rw/iosystem/devices/{device}",
        params={k: v for k, v in {"action": action}.items() if v is not None},
        data={
            k: v
            for k, v in {
                "startbyte": startbyte,
                "signaldata": signaldata,
                "datamask": datamask
            }.items()
            if v is not None
        },
    )

async def set_output_data(
    client: RWSClient,
    device: str,
    action: str | None = None,
    startbyte: str | None = None,
    signaldata: str | None = None,
    datamask: str | None = None,
) -> httpx.Response:
    """
    Set output data.

    Route: ``POST /rw/iosystem/devices/{device}``
    ABB constraints: Only supported in Virtual Controller. If input data is 4 bytes long, start
        byte can have values ranging from 0 to 3. Datamask/signal data can have values ranging
        from 0 to 255 (since it is accessed as 1 byte long). If datamask/signal data is greater
        than 255 (1 byte long), only first 8 bits is us...

    Args:
        client: Open RWSClient instance.
        device: URL path parameter.
        action: Query parameter. Optional.
        startbyte: Body parameter. Optional.
        signaldata: Body parameter. Optional.
        datamask: Body parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 204.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD_REQUEST(400), UNSUPPORTED_MEDIA(415)

    Example:
        ```python
        >>> await set_output_data(client, "device_value")
        <Response [204]>
        ```
    """
    return await client.post(
        f"/rw/iosystem/devices/{device}",
        params={k: v for k, v in {"action": action}.items() if v is not None},
        data={
            k: v
            for k, v in {
                "startbyte": startbyte,
                "signaldata": signaldata,
                "datamask": datamask
            }.items()
            if v is not None
        },
    )

async def get_io_device_configuration_properties(
    client: RWSClient,
    device: str,
    resource: str | None = None,
    configtype: str | None = None,
) -> httpx.Response:
    """
    Get IO Device Configuration Properties.

    Route: ``GET /rw/iosystem/devices/{device}``
    ABB constraints: "configtype_value" should be 1 (or) 2 (or) 3 (2= general configuration , 1 =
        runtime configuration , 3 = both) Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        device: URL path parameter.
        resource: Query parameter. Optional.
        configtype: Query parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD REQUEST(400)

    Example:
        ```python
        >>> await get_io_device_configuration_properties(client, "device_value")
        <Response [200]>
        ```
    """
    return await client.get(
        f"/rw/iosystem/devices/{device}",
        params={
            k: v
            for k, v in {
                "resource": resource,
                "configtype": configtype
            }.items()
            if v is not None
        },
    )

async def get_eio_device_status_information(
    client: RWSClient,
    network: str,
    device: str,
) -> httpx.Response:
    """
    Get eio device status information.

    Route: ``GET /rw/iosystem/devices/{network}/{device}/upgradeinfo``
    ABB constraints: Not supported in bootserver mode Applicable only for RC

    Args:
        client: Open RWSClient instance.
        network: URL path parameter.
        device: URL path parameter.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD_REQUEST(400)

    Example:
        ```python
        >>> await get_eio_device_status_information(client, "network_value", "device_value")
        <Response [200]>
        ```
    """
    return await client.get(f"/rw/iosystem/devices/{network}/{device}/upgradeinfo")

async def post_send_device_command(
    client: RWSClient,
    device: str,
    commandname: str | None = None,
    value: str | None = None,
    valuelength: str | None = None,
    timeout: str | None = None,
) -> httpx.Response:
    """
    Send Device Command.

    Route: ``POST /rw/iosystem/devices/{device}/command``
    ABB constraints: Applicable only for RC. Not supported in bootserver mode.

    Args:
        client: Open RWSClient instance.
        device: URL path parameter.
        commandname: Body parameter. Optional.
        value: Body parameter. Optional.
        valuelength: Body parameter. Optional.
        timeout: Body parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 204.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD_REQUEST(400), UNSUPPORTED_MEDIA(415)

    Example:
        ```python
        >>> await post_send_device_command(client, "device_value")
        <Response [204]>
        ```
    """
    return await client.post(
        f"/rw/iosystem/devices/{device}/command",
        data={
            k: v
            for k, v in {
                "commandname": commandname,
                "value": value,
                "valuelength": valuelength,
                "timeout": timeout
            }.items()
            if v is not None
        },
    )

async def options_send_device_command_actions(
    client: RWSClient,
    device: str,
) -> httpx.Response:
    """
    Send Device Command actions.

    Route: ``OPTIONS /rw/iosystem/devices/{device}/command``
    ABB constraints: Not supported in bootserver mode.

    Args:
        client: Open RWSClient instance.
        device: URL path parameter.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: See

    Example:
        ```python
        >>> await options_send_device_command_actions(client, "device_value")
        <Response [200]>
        ```
    """
    return await client.options(f"/rw/iosystem/devices/{device}/command")

async def get_an_io_signal(
    client: RWSClient,
    network: str,
    unit: str,
    signal: str,
) -> httpx.Response:
    """
    Get an IO Signal.

    Route: ``GET /rw/iosystem/signals/{network}/{unit}/{signal}``
    ABB constraints: Not supported in bootserver mode.
        /rw/iosystem/signals/{network}/{unit}/{signal};state will return only the IO signal
        value.

    Args:
        client: Open RWSClient instance.
        network: URL path parameter.
        unit: URL path parameter.
        signal: URL path parameter.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD REQUEST(400)

    Example:
        ```python
        >>> await get_an_io_signal(client, "network_value", "unit_value", "signal_value")
        <Response [200]>
        ```
    """
    return await client.get(f"/rw/iosystem/signals/{network}/{unit}/{signal}")

async def get_io_signal_actions(
    client: RWSClient,
    network: str,
    unit: str,
    signal: str,
    action: str | None = None,
) -> httpx.Response:
    """
    Get IO Signal actions.

    Route: ``GET /rw/iosystem/signals/{network}/{unit}/{signal}``
    ABB constraints: Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        network: URL path parameter.
        unit: URL path parameter.
        signal: URL path parameter.
        action: Query parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD REQUEST(400)

    Example:
        ```python
        >>> await get_io_signal_actions(client, "network_value", "unit_value", "signal_value")
        <Response [200]>
        ```
    """
    return await client.get(
        f"/rw/iosystem/signals/{network}/{unit}/{signal}",
        params={k: v for k, v in {"action": action}.items() if v is not None},
    )

async def update_io_signal_state(
    client: RWSClient,
    network: str,
    device: str,
    signal: str,
    action: str | None = None,
    lstate: str | None = None,
) -> httpx.Response:
    """
    Update IO Signal State.

    Route: ``POST /rw/iosystem/signals/{network}/{device}/{signal}``
    ABB constraints: Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        network: URL path parameter.
        device: URL path parameter.
        signal: URL path parameter.
        action: Query parameter. Optional.
        lstate: Body parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 204.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD_REQUEST(400)

    Example:
        ```python
        >>> await update_io_signal_state(client, "network_value", "device_value", "signal_value")
        <Response [204]>
        ```
    """
    return await client.post(
        f"/rw/iosystem/signals/{network}/{device}/{signal}",
        params={k: v for k, v in {"action": action}.items() if v is not None},
        data={k: v for k, v in {"lstate": lstate}.items() if v is not None},
    )

async def update_io_signal_value(
    client: RWSClient,
    network: str,
    device: str,
    signal: str,
    action: str | None = None,
) -> httpx.Response:
    """
    Update IO Signal Value.

    Route: ``POST /rw/iosystem/signals/{network}/{device}/{signal}``
    ABB constraints: Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        network: URL path parameter.
        device: URL path parameter.
        signal: URL path parameter.
        action: Query parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 204.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD_REQUEST(400)

    Example:
        ```python
        >>> await update_io_signal_value(client, "network_value", "device_value", "signal_value")
        <Response [204]>
        ```
    """
    return await client.post(
        f"/rw/iosystem/signals/{network}/{device}/{signal}",
        params={k: v for k, v in {"action": action}.items() if v is not None},
        data={},
    )

async def subscribe_io_signal(
    client: RWSClient,
    identifier: str | None = None,
    identifier_p: str | None = None,
) -> httpx.Response:
    """
    Subscribe IO Signal.

    Route: ``POST /subscription``
    ABB constraints: Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        identifier: Body parameter. Optional.
        identifier_p: Body parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 201.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD REQUEST(400)

    Example:
        ```python
        >>> await subscribe_io_signal(client)
        <Response [201]>
        ```
    """
    return await client.post(
        "/subscription",
        data={
            k: v
            for k, v in {
                "identifier": identifier,
                "identifier_p": identifier_p
            }.items()
            if v is not None
        },
    )

async def get_io_signal_configuration_properties(
    client: RWSClient,
    network: str,
    unit: str,
    signal: str,
    resource: str | None = None,
    configtype: str | None = None,
) -> httpx.Response:
    """
    Get IO signal Configuration Properties.

    Route: ``GET /rw/iosystem/signals/{network}/{unit}/{signal}``
    ABB constraints: "configtype_value" should be 1 (or) 2 (or) 3 (2= general configuration , 1 =
        runtime configuration , 3 = both) Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        network: URL path parameter.
        unit: URL path parameter.
        signal: URL path parameter.
        resource: Query parameter. Optional.
        configtype: Query parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD REQUEST(400)

    Example:
        ```python
        >>> await get_io_signal_configuration_properties(
        ...     client,
        ...     "network_value",
        ...     "unit_value",
        ...     "signal_value"
        ... )
        <Response [200]>
        ```
    """
    return await client.get(
        f"/rw/iosystem/signals/{network}/{unit}/{signal}",
        params={
            k: v
            for k, v in {
                "resource": resource,
                "configtype": configtype
            }.items()
            if v is not None
        },
    )
