# This file is AUTO-GENERATED by contrib/generator/main.py
# DO NOT EDIT MANUALLY — run the generator to regenerate.
#  Generator author: Clement RACINET
"""Auto-generated unit tests for rws/users/rmmp."""
from __future__ import annotations

import httpx
import pytest

from abb_rws_client._core.client import RWSClient
from abb_rws_client.rws.users.rmmp import (
    cancel_held_or_requested_rmmp,
    get_rmmp_actions,
    get_rmmp_state,
    grant_or_deny_an_rmmp_request,
    poll_for_rmmp_grant_status,
    request_rmmp,
    subscribe_on_rmmp_request_event,
)


class _MockTransport(httpx.AsyncBaseTransport):
    """Mock transport returning a configurable HTTP response."""

    def __init__(self, status_code: int = 200, content: bytes = b"") -> None:
        self.status_code = status_code
        self.content = content
        self.last_request: httpx.Request | None = None

    async def handle_async_request(self, request: httpx.Request) -> httpx.Response:
        self.last_request = request
        return httpx.Response(self.status_code, content=self.content, request=request)


def _make_client(transport: _MockTransport) -> RWSClient:
    """Build an RWSClient connected to the mock transport."""
    client = RWSClient.__new__(RWSClient)
    client._http = httpx.AsyncClient(
        transport=transport,
        base_url="http://localhost/",
    )
    client.host = "localhost"
    return client


@pytest.mark.asyncio
async def test_get_rmmp_state() -> None:
    """
    Verify that get_rmmp_state sends GET /users/rmmp.
    """
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_rmmp_state(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/users/rmmp"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_rmmp_actions() -> None:
    """
    Verify that get_rmmp_actions sends GET /users/rmmp.
    """
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_rmmp_actions(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/users/rmmp"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_request_rmmp() -> None:
    """
    Verify that request_rmmp sends POST /users/rmmp.
    """
    transport = _MockTransport(status_code=202)
    client = _make_client(transport)

    resp = await request_rmmp(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/users/rmmp"
    ct = transport.last_request.headers.get("content-type") or ""
    assert "application/x-www-form-urlencoded" in ct
    assert resp.status_code == 202

@pytest.mark.asyncio
async def test_grant_or_deny_an_rmmp_request() -> None:
    """
    Verify that grant_or_deny_an_rmmp_request sends POST /users/rmmp.
    """
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await grant_or_deny_an_rmmp_request(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/users/rmmp"
    ct = transport.last_request.headers.get("content-type") or ""
    assert "application/x-www-form-urlencoded" in ct
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_cancel_held_or_requested_rmmp() -> None:
    """
    Verify that cancel_held_or_requested_rmmp sends POST /users/rmmp.
    """
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await cancel_held_or_requested_rmmp(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/users/rmmp"
    ct = transport.last_request.headers.get("content-type") or ""
    assert "application/x-www-form-urlencoded" in ct
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_subscribe_on_rmmp_request_event() -> None:
    """
    Verify that subscribe_on_rmmp_request_event sends POST /subscription.
    """
    transport = _MockTransport(status_code=201)
    client = _make_client(transport)

    resp = await subscribe_on_rmmp_request_event(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/subscription"
    ct = transport.last_request.headers.get("content-type") or ""
    assert "application/x-www-form-urlencoded" in ct
    assert resp.status_code == 201

@pytest.mark.asyncio
async def test_poll_for_rmmp_grant_status() -> None:
    """
    Verify that poll_for_rmmp_grant_status sends GET /users/rmmp/poll.
    """
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await poll_for_rmmp_grant_status(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/users/rmmp/poll"
    assert resp.status_code == 200
