# This file is AUTO-GENERATED by contrib/generator/main.py
# DO NOT EDIT MANUALLY — run the generator to regenerate.
#  Generator author: Clément RACINET
"""Auto-generated unit tests for rws/users/remote."""
from __future__ import annotations

import httpx
import pytest

from abb_rws_client._core.client import RWSClient
from abb_rws_client.rws.users.remote import (
    get_remote_user_actions,
    post_remote_user_logon_request,
    post_remote_user_logout_request,
    subscribe_on_remote_user_state,
)


class _MockTransport(httpx.AsyncBaseTransport):
    """Mock transport returning a configurable HTTP response."""

    def __init__(self, status_code: int = 200, content: bytes = b"") -> None:
        self.status_code = status_code
        self.content = content
        self.last_request: httpx.Request | None = None

    async def handle_async_request(self, request: httpx.Request) -> httpx.Response:
        self.last_request = request
        return httpx.Response(self.status_code, content=self.content, request=request)


def _make_client(transport: _MockTransport) -> RWSClient:
    """Build an RWSClient connected to the mock transport."""
    client = RWSClient.__new__(RWSClient)
    client._http = httpx.AsyncClient(
        transport=transport,
        base_url="http://localhost/",
    )
    client.host = "localhost"
    return client


@pytest.mark.asyncio
async def test_get_remote_user_actions() -> None:
    """
    Verify that get_remote_user_actions sends GET /users/remoteuser.
    """
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_remote_user_actions(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/users/remoteuser"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_post_remote_user_logon_request() -> None:
    """
    Verify that post_remote_user_logon_request sends POST /users/remoteuser.
    """
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await post_remote_user_logon_request(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/users/remoteuser"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_post_remote_user_logout_request() -> None:
    """
    Verify that post_remote_user_logout_request sends POST /users/remoteuser.
    """
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await post_remote_user_logout_request(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/users/remoteuser"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_subscribe_on_remote_user_state() -> None:
    """
    Verify that subscribe_on_remote_user_state sends POST /subscription.
    """
    transport = _MockTransport(status_code=201)
    client = _make_client(transport)

    resp = await subscribe_on_remote_user_state(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/subscription"
    assert resp.status_code == 201
