# This file is AUTO-GENERATED by contrib/generator/main.py
# DO NOT EDIT MANUALLY — run the generator to regenerate.
"""Tests unitaires auto-générés pour rws/users/users."""
from __future__ import annotations

import pytest
import httpx

from abb_rws_client._core.client import RWSClient
from abb_rws_client.rws.users.users import (
    get_user_resources,
    get_user_actions,
    register_the_user,
    impersonate_user,
    login_as_local_user,
)


class _MockTransport(httpx.AsyncBaseTransport):
    """Transport mock retournant une réponse HTTP configurable."""

    def __init__(self, status_code: int = 200, content: bytes = b"") -> None:
        self.status_code = status_code
        self.content = content
        self.last_request: httpx.Request | None = None

    async def handle_async_request(self, request: httpx.Request) -> httpx.Response:
        self.last_request = request
        return httpx.Response(self.status_code, content=self.content, request=request)


def _make_client(transport: _MockTransport) -> RWSClient:
    """Construit un RWSClient branché sur le transport mock."""
    client = RWSClient.__new__(RWSClient)
    client._http = httpx.AsyncClient(
        transport=transport,
        base_url="http://localhost/",
    )
    client.host = "localhost"
    return client


@pytest.mark.asyncio
async def test_get_user_resources() -> None:
    """Vérifie que get_user_resources émet GET /users."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_user_resources(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/users"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_user_actions() -> None:
    """Vérifie que get_user_actions émet GET /users."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_user_actions(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/users"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_register_the_user() -> None:
    """Vérifie que register_the_user émet POST /users."""
    transport = _MockTransport(status_code=201)
    client = _make_client(transport)

    resp = await register_the_user(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/users"
    assert resp.status_code == 201

@pytest.mark.asyncio
async def test_impersonate_user() -> None:
    """Vérifie que impersonate_user émet POST /users."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await impersonate_user(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/users"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_login_as_local_user() -> None:
    """Vérifie que login_as_local_user émet POST /users."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await login_as_local_user(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/users"
    assert resp.status_code == 200
