# This file is AUTO-GENERATED by contrib/generator/main.py
# DO NOT EDIT MANUALLY — run the generator to regenerate.
"""Tests unitaires auto-générés pour rws/users/remote."""
from __future__ import annotations

import pytest
import httpx

from abb_rws_client._core.client import RWSClient
from abb_rws_client.rws.users.remote import (
    get_remote_user_actions,
    post_remote_user_logon_request,
    post_remote_user_logout_request,
    subscribe_on_remote_user_state,
)


class _MockTransport(httpx.AsyncBaseTransport):
    """Transport mock retournant une réponse HTTP configurable."""

    def __init__(self, status_code: int = 200, content: bytes = b"") -> None:
        self.status_code = status_code
        self.content = content
        self.last_request: httpx.Request | None = None

    async def handle_async_request(self, request: httpx.Request) -> httpx.Response:
        self.last_request = request
        return httpx.Response(self.status_code, content=self.content, request=request)


def _make_client(transport: _MockTransport) -> RWSClient:
    """Construit un RWSClient branché sur le transport mock."""
    client = RWSClient.__new__(RWSClient)
    client._http = httpx.AsyncClient(
        transport=transport,
        base_url="http://localhost/",
    )
    client.host = "localhost"
    return client


@pytest.mark.asyncio
async def test_get_remote_user_actions() -> None:
    """Vérifie que get_remote_user_actions émet GET /users/remoteuser."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_remote_user_actions(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/users/remoteuser"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_post_remote_user_logon_request() -> None:
    """Vérifie que post_remote_user_logon_request émet POST /users/remoteuser."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await post_remote_user_logon_request(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/users/remoteuser"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_post_remote_user_logout_request() -> None:
    """Vérifie que post_remote_user_logout_request émet POST /users/remoteuser."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await post_remote_user_logout_request(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/users/remoteuser"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_subscribe_on_remote_user_state() -> None:
    """Vérifie que subscribe_on_remote_user_state émet POST /subscription."""
    transport = _MockTransport(status_code=201)
    client = _make_client(transport)

    resp = await subscribe_on_remote_user_state(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/subscription"
    assert resp.status_code == 201
