# This file is AUTO-GENERATED by contrib/generator/main.py
# DO NOT EDIT MANUALLY — run the generator to regenerate.
"""
RWS module : RobotWare Services → RAPID Service → Operations on RAPID execution

Miroir 1:1 de l'API REST ABB RobotWare 6.
Chaque fonction correspond à exactement un endpoint HTTP.
Aucune logique composée — voir highlevel/ pour les wrappers.
"""
from __future__ import annotations

import httpx

from abb_rws_client._core.client import RWSClient


async def get_rapid_execution_state(
    client: RWSClient,
    continue_on_err: str | None = None,
) -> httpx.Response:
    """
    Get RAPID Execution state.

    Route: ``GET /rw/rapid/execution``
    Contraintes ABB: Not supported in bootserver mode. Use /rw/rapid/execution;ctrlexecstate to filter ctrlexecstate value.

    Args:
        client: Instance RWSClient ouverte.
        continue_on_err: Paramètre query. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 200.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD_REQUEST(400)

    Example:
        # curl --digest -u "Default User":robotics "http://localhost/rw/rapid/execution"
    """
    return await client.get("/rw/rapid/execution", params={k: v for k, v in {"continue_on_err": continue_on_err}.items() if v is not None})

async def get_rapid_execution_actions(
    client: RWSClient,
    action: str | None = None,
) -> httpx.Response:
    """
    Get RAPID Execution actions.

    Route: ``GET /rw/rapid/execution``
    Contraintes ABB: Not supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        action: Paramètre query. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 200.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD_REQUEST(400)

    Example:
        # curl --digest -u "Default User":robotics" "
    """
    return await client.get("/rw/rapid/execution", params={k: v for k, v in {"action": action}.items() if v is not None})

async def start_rapid_execution(
    client: RWSClient,
    action: str | None = None,
    regain: str | None = None,
    execmode: str | None = None,
    cycle: str | None = None,
    condition: str | None = None,
    stopatbp: str | None = None,
    alltaskbytsp: str | None = None,
) -> httpx.Response:
    """
    Start RAPID Execution.

    Route: ``POST /rw/rapid/execution``
    Contraintes ABB: Not supported in bootserver mode.

    Args:
        client: Instance RWSClient ouverte.
        action: Paramètre query. Optionnel.
        regain: Paramètre body. Optionnel.
        execmode: Paramètre body. Optionnel.
        cycle: Paramètre body. Optionnel.
        condition: Paramètre body. Optionnel.
        stopatbp: Paramètre body. Optionnel.
        alltaskbytsp: Paramètre body. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 204.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD_REQUEST(400)

    Example:
        # curl --digest -u "Default User":robotics -d "regain=continue&execmode=continue&cycle=forever&condition=none&stopatbp=dis
    """
    return await client.post("/rw/rapid/execution", params={k: v for k, v in {"action": action}.items() if v is not None}, data={k: v for k, v in {"regain": regain, "execmode": execmode, "cycle": cycle, "condition": condition, "stopatbp": stopatbp, "alltaskbytsp": alltaskbytsp}.items() if v is not None})

async def stop_rapid_execution(
    client: RWSClient,
    action: str | None = None,
    stopmode: str | None = None,
    usetsp: str | None = None,
) -> httpx.Response:
    """
    Stop RAPID Execution.

    Route: ``POST /rw/rapid/execution``
    Contraintes ABB: Not supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        action: Paramètre query. Optionnel.
        stopmode: Paramètre body. Optionnel.
        usetsp: Paramètre body. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 204.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD_REQUEST(400)

    Example:
        # curl --digest -u "Default User":robotics -X POST "http://localhost/rw/rapid/execution?action=stop"
    """
    return await client.post("/rw/rapid/execution", params={k: v for k, v in {"action": action}.items() if v is not None}, data={k: v for k, v in {"stopmode": stopmode, "usetsp": usetsp}.items() if v is not None})

async def start_rapid_execution_from_production_entry(
    client: RWSClient,
    action: str | None = None,
) -> httpx.Response:
    """
    Start RAPID Execution from production entry.

    Route: ``POST /rw/rapid/execution``
    Contraintes ABB: Not supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        action: Paramètre query. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 204.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD_REQUEST(400)

    Example:
        # curl --digest -u "Default User":robotics -X POST "http://localhost/rw/rapid/execution?action=startprodentry"
    """
    return await client.post("/rw/rapid/execution", params={k: v for k, v in {"action": action}.items() if v is not None})

async def reset_rapid_program_pointer_to_main(
    client: RWSClient,
    action: str | None = None,
) -> httpx.Response:
    """
    Reset RAPID program pointer to main.

    Route: ``POST /rw/rapid/execution``
    Contraintes ABB: Not supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        action: Paramètre query. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 204.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD_REQUEST(400)

    Example:
        # curl --digest -u "Default User":robotics -X POST "http://localhost/rw/rapid/execution?action=resetpp"
    """
    return await client.post("/rw/rapid/execution", params={k: v for k, v in {"action": action}.items() if v is not None})

async def set_number_of_execution_cycles(
    client: RWSClient,
    action: str | None = None,
    cycle: str | None = None,
) -> httpx.Response:
    """
    Set number of execution cycles.

    Route: ``POST /rw/rapid/execution``
    Contraintes ABB: Not supported in bootserver mode. Mastership is required to set cycle.

    Args:
        client: Instance RWSClient ouverte.
        action: Paramètre query. Optionnel.
        cycle: Paramètre body. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 204.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD_REQUEST(400)

    Example:
        # curl --digest -u "Default User":robotics -d "cycle=once" -X POST "http://localhost/rw/rapid/execution?action=setcycle"
    """
    return await client.post("/rw/rapid/execution", params={k: v for k, v in {"action": action}.items() if v is not None}, data={k: v for k, v in {"cycle": cycle}.items() if v is not None})

async def subscribe_rapid_execution(
    client: RWSClient,
    resources: str | None = None,
    identifier: str | None = None,
    identifier_p: str | None = None,
) -> httpx.Response:
    """
    Subscribe RAPID Execution.

    Route: ``POST /subscription``
    Contraintes ABB: Not supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        resources: Paramètre body. Optionnel.
        identifier: Paramètre body. Optionnel.
        identifier_p: Paramètre body. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 201.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD_REQUEST(400), UNSUPPORTED_MEDIA(415)

    Example:
        # Subscribe on RAPID execution state
    """
    return await client.post("/subscription", data={k: v for k, v in {"resources": resources, "identifier": identifier, "identifier_p": identifier_p}.items() if v is not None})

async def subscribe_rapid_execution_cycle(
    client: RWSClient,
    resources: str | None = None,
    identifier: str | None = None,
    identifier_p: str | None = None,
) -> httpx.Response:
    """
    Subscribe RAPID Execution Cycle.

    Route: ``POST /subscription``
    Contraintes ABB: Not supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        resources: Paramètre body. Optionnel.
        identifier: Paramètre body. Optionnel.
        identifier_p: Paramètre body. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 201.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD_REQUEST(400), UNSUPPORTED_MEDIA(415)

    Example:
        # Subscribe on RAPID execution cycle
    """
    return await client.post("/subscription", data={k: v for k, v in {"resources": resources, "identifier": identifier, "identifier_p": identifier_p}.items() if v is not None})

async def subscribe_on_hold_to_run(
    client: RWSClient,
    identifier: str | None = None,
    identifier_p: str | None = None,
) -> httpx.Response:
    """
    Subscribe on Hold to Run.

    Route: ``POST /subscription``
    Contraintes ABB: Not supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        identifier: Paramètre body. Optionnel.
        identifier_p: Paramètre body. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 201.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD_REQUEST(400), UNSUPPORTED_MEDIA(415)

    Example:
        # Subscribe on RAPID hold to run
    """
    return await client.post("/subscription", data={k: v for k, v in {"identifier": identifier, "identifier_p": identifier_p}.items() if v is not None})

async def set_hold_to_run_cmd(
    client: RWSClient,
    action: str | None = None,
    state: str | None = None,
) -> httpx.Response:
    """
    Set Hold to Run Cmd.

    Route: ``POST /rw/rapid/execution``
    Contraintes ABB: -Not supported in bootserver mode -Supported in VC only -Login as Local Client -The Hold-To-Run control prevents RAPID-program execution to start until the holdtorun state is changed to Press. -In the state Pressed the client must poll the Hold-To-Run control every 2 second, otherwise the program...

    Args:
        client: Instance RWSClient ouverte.
        action: Paramètre query. Optionnel.
        state: Paramètre body. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 204.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD_REQUEST(400),FORBIDDEN(403)

    Example:
        # curl --digest -u "Default User":robotics -X POST -d "state={press | held | release}" "http://localhost/rw/rapid/executio
    """
    return await client.post("/rw/rapid/execution", params={k: v for k, v in {"action": action}.items() if v is not None}, data={k: v for k, v in {"state": state}.items() if v is not None})
