# This file is AUTO-GENERATED by utils/generator/main.py
# DO NOT EDIT MANUALLY — run the generator to regenerate.
#  Generator author: Clement RACINET
"""
RWS module: RobotWare Services → RAPID Service → Operations on RAPID modules

1:1 mirror of the ABB RobotWare 6 REST API.
Each function maps to exactly one HTTP endpoint.
No composed logic — see highlevel/ for wrappers.
"""
from __future__ import annotations

import httpx

from abb_rws_client.core.client import RWSClient


async def get_rapid_modules_action(
    client: RWSClient,
    action: str | None = None,
) -> httpx.Response:
    """
    Get RAPID modules action.

    Route: ``GET /rw/rapid/modules``
    ABB constraints: Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        action: Query parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD_REQUEST(400)

    Example:
        ```python
        >>> await get_rapid_modules_action(client)
        <Response [200]>
        ```
    """
    return await client.get(
        "/rw/rapid/modules",
        params={k: v for k, v in {"action": action}.items() if v is not None},
    )

async def get_rapid_modules(
    client: RWSClient,
    task: str | None = None,
) -> httpx.Response:
    """
    Get RAPID modules.

    Route: ``GET /rw/rapid/modules``
    ABB constraints: Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        task: Query parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: HTTP Errors, see

    Example:
        ```python
        >>> await get_rapid_modules(client)
        <Response [200]>
        ```
    """
    return await client.get(
        "/rw/rapid/modules",
        params={k: v for k, v in {"task": task}.items() if v is not None},
    )

async def get_mod_possible_all(
    client: RWSClient,
    resource: str | None = None,
) -> httpx.Response:
    """
    Get Mod Possible All.

    Route: ``GET /rw/rapid/modules``
    ABB constraints: Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        resource: Query parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD_REQUEST(400), see

    Example:
        ```python
        >>> await get_mod_possible_all(client)
        <Response [200]>
        ```
    """
    return await client.get(
        "/rw/rapid/modules",
        params={k: v for k, v in {"resource": resource}.items() if v is not None},
    )

async def set_modify_all_positions(
    client: RWSClient,
    action: str | None = None,
    checklimit: str | None = None,
    checkdeactaxes: str | None = None,
) -> httpx.Response:
    """
    Set Modify All Positions.

    Route: ``POST /rw/rapid/modules``
    ABB constraints: User needs to be local client and mastership is also required Not supported
        in bootserver mode

    Args:
        client: Open RWSClient instance.
        action: Query parameter. Optional.
        checklimit: Body parameter. Optional.
        checkdeactaxes: Body parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 204.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD_REQUEST(400), see

    Example:
        ```python
        >>> await set_modify_all_positions(client)
        <Response [204]>
        ```
    """
    return await client.post(
        "/rw/rapid/modules",
        params={k: v for k, v in {"action": action}.items() if v is not None},
        data={
            k: v
            for k, v in {
                "checklimit": checklimit,
                "checkdeactaxes": checkdeactaxes
            }.items()
            if v is not None
        },
    )

async def get_specified_range_of_text(
    client: RWSClient,
    module: str,
) -> httpx.Response:
    """
    Get a specified range of text.

    Route: ``GET /rw/rapid/modules/{module}``
    ABB constraints: Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        module: URL path parameter.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD_REQUEST(400), see

    Example:
        ```python
        >>> await get_specified_range_of_text(client, "module_value")
        <Response [200]>
        ```
    """
    return await client.get(f"/rw/rapid/modules/{module}")

async def get_rapid_module_actions(
    client: RWSClient,
    module: str,
    action: str | None = None,
) -> httpx.Response:
    """
    Get rapid module actions.

    Route: ``GET /rw/rapid/modules/{module}``
    ABB constraints: Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        module: URL path parameter.
        action: Query parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD_REQUEST(400), see

    Example:
        ```python
        >>> await get_rapid_module_actions(client, "module_value")
        <Response [200]>
        ```
    """
    return await client.get(
        f"/rw/rapid/modules/{module}",
        params={k: v for k, v in {"action": action}.items() if v is not None},
    )

async def save_rapid_module(
    client: RWSClient,
    module: str,
    task: str | None = None,
    action: str | None = None,
    name: str | None = None,
    path: str | None = None,
) -> httpx.Response:
    """
    Save rapid module.

    Route: ``POST /rw/rapid/modules/{module}``
    ABB constraints: Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        module: URL path parameter.
        task: Query parameter. Optional.
        action: Query parameter. Optional.
        name: Body parameter. Optional.
        path: Body parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 204.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD_REQUEST(400), see

    Example:
        ```python
        >>> await save_rapid_module(client, "module_value")
        <Response [204]>
        ```
    """
    return await client.post(
        f"/rw/rapid/modules/{module}",
        params={k: v for k, v in {"task": task, "action": action}.items() if v is not None},
        data={k: v for k, v in {"name": name, "path": path}.items() if v is not None},
    )

async def set_text_range(
    client: RWSClient,
    module: str,
    query_mode: str,
    action: str | None = None,
    task: str | None = None,
    replace_mode: str | None = None,
    startrow: str | None = None,
    startcol: str | None = None,
    endrow: str | None = None,
    endcol: str | None = None,
    text: str | None = None,
) -> httpx.Response:
    """
    Set Text Range.

    Route: ``POST /rw/rapid/modules/{module}``
    ABB constraints: Mastership is Required Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        module: URL path parameter.
        action: Query parameter. Optional.
        query_mode: Body parameter. Required.
        task: Body parameter. Optional.
        replace_mode: Body parameter. Optional.
        startrow: Body parameter. Optional.
        startcol: Body parameter. Optional.
        endrow: Body parameter. Optional.
        endcol: Body parameter. Optional.
        text: Body parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 204.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD_REQUEST(400), see

    Example:
        ```python
        >>> await set_text_range(client, "module_value", query_mode="query_mode_value")
        <Response [204]>
        ```
    """
    return await client.post(
        f"/rw/rapid/modules/{module}",
        params={k: v for k, v in {"action": action}.items() if v is not None},
        data={
            k: v
            for k, v in {
                "task": task,
                "replace_mode": replace_mode,
                "query_mode": query_mode,
                "startrow": startrow,
                "startcol": startcol,
                "endrow": endrow,
                "endcol": endcol,
                "text": text
            }.items()
            if v is not None
        },
    )

async def set_module_text(
    client: RWSClient,
    module: str,
    task: str | None = None,
    action: str | None = None,
    text: str | None = None,
) -> httpx.Response:
    """
    Set Module Text.

    Route: ``POST /rw/rapid/modules/{module}``
    ABB constraints: Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        module: URL path parameter.
        task: Query parameter. Optional.
        action: Query parameter. Optional.
        text: Body parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD_REQUEST(400),NOT_FOUND(404), see

    Example:
        ```python
        >>> await set_module_text(client, "module_value")
        <Response [200]>
        ```
    """
    return await client.post(
        f"/rw/rapid/modules/{module}",
        params={k: v for k, v in {"task": task, "action": action}.items() if v is not None},
        data={k: v for k, v in {"text": text}.items() if v is not None},
    )

async def get_rapid_module_attributes(
    client: RWSClient,
    module: str,
    task: str | None = None,
    continue_on_err: str | None = None,
) -> httpx.Response:
    """
    Get RAPID module attributes.

    Route: ``GET /rw/rapid/modules/{module}``
    ABB constraints: Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        module: URL path parameter.
        task: Query parameter. Optional.
        continue_on_err: Query parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD_REQUEST(400), see

    Example:
        ```python
        >>> await get_rapid_module_attributes(client, "module_value")
        <Response [200]>
        ```
    """
    return await client.get(
        f"/rw/rapid/modules/{module}",
        params={
            k: v
            for k, v in {
                "task": task,
                "continue_on_err": continue_on_err
            }.items()
            if v is not None
        },
    )

async def get_change_count(
    client: RWSClient,
    module: str,
    resource: str | None = None,
    task: str | None = None,
) -> httpx.Response:
    """
    Get change count.

    Route: ``GET /rw/rapid/modules/{module}``

    Args:
        client: Open RWSClient instance.
        module: URL path parameter.
        resource: Query parameter. Optional.
        task: Query parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: Bad Request(400), FORBIDDEN(403), NOT_FOUND(404), see

    Example:
        ```python
        >>> await get_change_count(client, "module_value")
        <Response [200]>
        ```
    """
    return await client.get(
        f"/rw/rapid/modules/{module}",
        params={k: v for k, v in {"resource": resource, "task": task}.items() if v is not None},
    )

async def get_rulesinstr(
    client: RWSClient,
    module: str,
    resource: str | None = None,
    task: str | None = None,
    name: str | None = None,
    data_type: str | None = None,
    line: str | None = None,
    col: str | None = None,
) -> httpx.Response:
    """
    Get RulesInstr.

    Route: ``GET /rw/rapid/modules/{module}``

    Args:
        client: Open RWSClient instance.
        module: URL path parameter.
        resource: Query parameter. Optional.
        task: Query parameter. Optional.
        name: Query parameter. Optional.
        data_type: Query parameter. Optional.
        line: Query parameter. Optional.
        col: Query parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD_REQUEST(400)

    Example:
        ```python
        >>> await get_rulesinstr(client, "module_value")
        <Response [200]>
        ```
    """
    return await client.get(
        f"/rw/rapid/modules/{module}",
        params={
            k: v
            for k, v in {
                "resource": resource,
                "task": task,
                "name": name,
                "data_type": data_type,
                "line": line,
                "col": col
            }.items()
            if v is not None
        },
    )

async def get_module_possible_attributes(
    client: RWSClient,
    module: str,
    task: str | None = None,
    attribute: str | None = None,
) -> httpx.Response:
    """
    Get module possible attributes.

    Route: ``GET /rw/rapid/modules/{module}``
    ABB constraints: -Not supported in bootserver mode -URL param "attribute" can be provided
        multiple times

    Args:
        client: Open RWSClient instance.
        module: URL path parameter.
        task: Query parameter. Optional.
        attribute: Query parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD_REQUEST(400), see

    Example:
        ```python
        >>> await get_module_possible_attributes(client, "module_value")
        <Response [200]>
        ```
    """
    return await client.get(
        f"/rw/rapid/modules/{module}",
        params={
            k: v
            for k, v in {
                "task": task,
                "attribute": attribute
            }.items()
            if v is not None
        },
    )

async def get_search_text(
    client: RWSClient,
    module: str,
    task: str | None = None,
    startrow: str | None = None,
    startcol: str | None = None,
    text: str | None = None,
) -> httpx.Response:
    """
    Get Search Text.

    Route: ``GET /rw/rapid/modules/{module}``
    ABB constraints: Not supported in bootserver mode. If the text is not found,the row and
        column values will be zero.

    Args:
        client: Open RWSClient instance.
        module: URL path parameter.
        task: Query parameter. Optional.
        startrow: Query parameter. Optional.
        startcol: Query parameter. Optional.
        text: Query parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD_REQUEST(400), FORBIDDEN(403), NOT_FOUND(404), see

    Example:
        ```python
        >>> await get_search_text(client, "module_value")
        <Response [200]>
        ```
    """
    return await client.get(
        f"/rw/rapid/modules/{module}",
        params={
            k: v
            for k, v in {
                "task": task,
                "startrow": startrow,
                "startcol": startcol,
                "text": text
            }.items()
            if v is not None
        },
    )

async def get_rapid_object(
    client: RWSClient,
    module: str,
) -> httpx.Response:
    """
    Get Rapid Object.

    Route: ``GET /rw/rapid/modules/{module}``
    ABB constraints: Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        module: URL path parameter.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD_REQUEST (400), FORBIDDEN(403), NOT_FOUND(404), see

    Example:
        ```python
        >>> await get_rapid_object(client, "module_value")
        <Response [200]>
        ```
    """
    return await client.get(f"/rw/rapid/modules/{module}")

async def set_syncpers(
    client: RWSClient,
    module: str,
    action: str | None = None,
    task: str | None = None,
) -> httpx.Response:
    """
    Set SyncPers.

    Route: ``POST /rw/rapid/modules/{module}``

    Args:
        client: Open RWSClient instance.
        module: URL path parameter.
        action: Query parameter. Optional.
        task: Query parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD_REQUEST(400)

    Example:
        ```python
        >>> await set_syncpers(client, "module_value")
        <Response [200]>
        ```
    """
    return await client.post(
        f"/rw/rapid/modules/{module}",
        params={k: v for k, v in {"action": action, "task": task}.items() if v is not None},
        data={},
    )

async def set_modify_position(
    client: RWSClient,
    module: str,
    action: str | None = None,
    task: str | None = None,
    startrow: str | None = None,
    startcol: str | None = None,
    endrow: str | None = None,
    endcol: str | None = None,
    checklimit: str | None = None,
    checkdeactaxes: str | None = None,
    allowdeact: str | None = None,
) -> httpx.Response:
    """
    Set Modify Position.

    Route: ``POST /rw/rapid/modules/{module}``

    Args:
        client: Open RWSClient instance.
        module: URL path parameter.
        action: Query parameter. Optional.
        task: Query parameter. Optional.
        startrow: Body parameter. Optional.
        startcol: Body parameter. Optional.
        endrow: Body parameter. Optional.
        endcol: Body parameter. Optional.
        checklimit: Body parameter. Optional.
        checkdeactaxes: Body parameter. Optional.
        allowdeact: Body parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 204.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: Bad Request(400),

    Example:
        ```python
        >>> await set_modify_position(client, "module_value")
        <Response [204]>
        ```
    """
    return await client.post(
        f"/rw/rapid/modules/{module}",
        params={k: v for k, v in {"action": action, "task": task}.items() if v is not None},
        data={
            k: v
            for k, v in {
                "startrow": startrow,
                "startcol": startcol,
                "endrow": endrow,
                "endcol": endcol,
                "checklimit": checklimit,
                "checkdeactaxes": checkdeactaxes,
                "allowdeact": allowdeact
            }.items()
            if v is not None
        },
    )

async def get_module_extension(
    client: RWSClient,
    module: str,
    resource: str | None = None,
    task: str | None = None,
) -> httpx.Response:
    """
    Get Module Extension.

    Route: ``GET /rw/rapid/modules/{module}``

    Args:
        client: Open RWSClient instance.
        module: URL path parameter.
        resource: Query parameter. Optional.
        task: Query parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: Bad Request(400), see

    Example:
        ```python
        >>> await get_module_extension(client, "module_value")
        <Response [200]>
        ```
    """
    return await client.get(
        f"/rw/rapid/modules/{module}",
        params={k: v for k, v in {"resource": resource, "task": task}.items() if v is not None},
    )

async def get_mod_possible(
    client: RWSClient,
    module: str,
    resource: str | None = None,
    task: str | None = None,
    startrow: str | None = None,
    startcol: str | None = None,
    endrow: str | None = None,
    endcol: str | None = None,
) -> httpx.Response:
    """
    Get Mod Possible.

    Route: ``GET /rw/rapid/modules/{module}``

    Args:
        client: Open RWSClient instance.
        module: URL path parameter.
        resource: Query parameter. Optional.
        task: Query parameter. Optional.
        startrow: Query parameter. Optional.
        startcol: Query parameter. Optional.
        endrow: Query parameter. Optional.
        endcol: Query parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: Bad Request(400), see

    Example:
        ```python
        >>> await get_mod_possible(client, "module_value")
        <Response [200]>
        ```
    """
    return await client.get(
        f"/rw/rapid/modules/{module}",
        params={
            k: v
            for k, v in {
                "resource": resource,
                "task": task,
                "startrow": startrow,
                "startcol": startcol,
                "endrow": endrow,
                "endcol": endcol
            }.items()
            if v is not None
        },
    )

async def get_object_child(
    client: RWSClient,
    module: str,
    resource: str | None = None,
    task: str | None = None,
    startline: str | None = None,
    startcolumn: str | None = None,
    endline: str | None = None,
    endcolumn: str | None = None,
) -> httpx.Response:
    """
    Get Object Child.

    Route: ``GET /rw/rapid/modules/{module}``

    Args:
        client: Open RWSClient instance.
        module: URL path parameter.
        resource: Query parameter. Optional.
        task: Query parameter. Optional.
        startline: Query parameter. Optional.
        startcolumn: Query parameter. Optional.
        endline: Query parameter. Optional.
        endcolumn: Query parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: Bad Request(400), see

    Example:
        ```python
        >>> await get_object_child(client, "module_value")
        <Response [200]>
        ```
    """
    return await client.get(
        f"/rw/rapid/modules/{module}",
        params={
            k: v
            for k, v in {
                "resource": resource,
                "task": task,
                "startline": startline,
                "startcolumn": startcolumn,
                "endline": endline,
                "endcolumn": endcolumn
            }.items()
            if v is not None
        },
    )

async def get_syncpers_status(
    client: RWSClient,
    module: str,
    resource: str | None = None,
    task: str | None = None,
) -> httpx.Response:
    """
    Get SyncPers Status.

    Route: ``GET /rw/rapid/modules/{module}``

    Args:
        client: Open RWSClient instance.
        module: URL path parameter.
        resource: Query parameter. Optional.
        task: Query parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: Bad Request(400), see

    Example:
        ```python
        >>> await get_syncpers_status(client, "module_value")
        <Response [200]>
        ```
    """
    return await client.get(
        f"/rw/rapid/modules/{module}",
        params={k: v for k, v in {"resource": resource, "task": task}.items() if v is not None},
    )

async def get_module_text(
    client: RWSClient,
    module: str,
    resource: str | None = None,
    task: str | None = None,
) -> httpx.Response:
    """
    Get Module Text.

    Route: ``GET /rw/rapid/modules/{module}``

    Args:
        client: Open RWSClient instance.
        module: URL path parameter.
        resource: Query parameter. Optional.
        task: Query parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: Bad Request(400), see

    Example:
        ```python
        >>> await get_module_text(client, "module_value")
        <Response [200]>
        ```
    """
    return await client.get(
        f"/rw/rapid/modules/{module}",
        params={k: v for k, v in {"resource": resource, "task": task}.items() if v is not None},
    )

async def get_symbol_information(
    client: RWSClient,
    module: str,
    resource: str | None = None,
    task: str | None = None,
    row: str | None = None,
    col: str | None = None,
) -> httpx.Response:
    """
    Get Symbol Information.

    Route: ``GET /rw/rapid/modules/{module}``

    Args:
        client: Open RWSClient instance.
        module: URL path parameter.
        resource: Query parameter. Optional.
        task: Query parameter. Optional.
        row: Query parameter. Optional.
        col: Query parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: Bad Request(400), see

    Example:
        ```python
        >>> await get_symbol_information(client, "module_value")
        <Response [200]>
        ```
    """
    return await client.get(
        f"/rw/rapid/modules/{module}",
        params={
            k: v
            for k, v in {
                "resource": resource,
                "task": task,
                "row": row,
                "col": col
            }.items()
            if v is not None
        },
    )

async def get_routine_information(
    client: RWSClient,
    module: str,
    task: str | None = None,
    row: str | None = None,
    column: str | None = None,
) -> httpx.Response:
    """
    Get Routine information.

    Route: ``GET /rw/rapid/modules/{module}/routine``
    ABB constraints: Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        module: URL path parameter.
        task: Query parameter. Optional.
        row: Query parameter. Optional.
        column: Query parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: HTTP_BAD_REQUEST(400),FORBIDDEN(403), NOT_FOUND(404),see

    Example:
        ```python
        >>> await get_routine_information(client, "module_value")
        <Response [200]>
        ```
    """
    return await client.get(
        f"/rw/rapid/modules/{module}/routine",
        params={
            k: v
            for k, v in {
                "task": task,
                "row": row,
                "column": column
            }.items()
            if v is not None
        },
    )

async def get_routineargs_information(
    client: RWSClient,
    module: str,
    resource: str | None = None,
    mark: str | None = None,
    limit: str | None = None,
    task: str | None = None,
    row: str | None = None,
    column: str | None = None,
) -> httpx.Response:
    """
    Get Routineargs information.

    Route: ``GET /rw/rapid/modules/{module}/routine``
    ABB constraints: Routineargs will show a list of arguments based on the mark and limit.
        Default value of mark is 0. Absence of next link indicates last page. You will get
        routine argument information only on lines having proceure call. Not supported in
        bootserver mode.

    Args:
        client: Open RWSClient instance.
        module: URL path parameter.
        resource: Query parameter. Optional.
        mark: Query parameter. Optional.
        limit: Query parameter. Optional.
        task: Query parameter. Optional.
        row: Query parameter. Optional.
        column: Query parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD_REQUEST(400),FORBIDDEN(403), NOT_FOUND(404), see

    Example:
        ```python
        >>> await get_routineargs_information(client, "module_value")
        <Response [200]>
        ```
    """
    return await client.get(
        f"/rw/rapid/modules/{module}/routine",
        params={
            k: v
            for k, v in {
                "resource": resource,
                "mark": mark,
                "limit": limit,
                "task": task,
                "row": row,
                "column": column
            }.items()
            if v is not None
        },
    )
