# This file is AUTO-GENERATED by contrib/generator/main.py
# DO NOT EDIT MANUALLY — run the generator to regenerate.
#  Generator author: Clément RACINET
"""
RWS module: RobotWare Services → RAPID Service → Operations on RAPID symbols properties

1:1 mirror of the ABB RobotWare 6 REST API.
Each function maps to exactly one HTTP endpoint.
No composed logic — see highlevel/ for wrappers.
"""
from __future__ import annotations

import httpx

from abb_rws_client._core.client import RWSClient


async def get_rapid_symbols_resources(client: RWSClient) -> httpx.Response:
    """
    Get RAPID symbols resources.

    Route: ``GET /rw/rapid/symbols``
    ABB constraints: Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.

    Example:
        # curl --digest -u "Default User":robotics" "
    """
    return await client.get("/rw/rapid/symbols")

async def get_rapid_symbols_actions(
    client: RWSClient,
    action: str | None = None,
) -> httpx.Response:
    """
    Get rapid symbols actions.

    Route: ``GET /rw/rapid/symbols``
    ABB constraints: Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        action: Query parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD_REQUEST(400)

    Example:
        # curl --digest -u "Default User":robotics" "
    """
    return await client.get(
        "/rw/rapid/symbols",
        params={k: v for k, v in {"action": action}.items() if v is not None},
    )

async def post_search_rapid_symbols(
    client: RWSClient,
    action: str | None = None,
    view: str | None = None,
    vartyp: str | None = None,
    blockurl: str | None = None,
    recursive: str | None = None,
    posl: str | None = None,
    posc: str | None = None,
    stack: str | None = None,
    onlyused: str | None = None,
    skipshared: str | None = None,
    regexp: str | None = None,
) -> httpx.Response:
    """
    Search RAPID symbols.

    Route: ``POST /rw/rapid/symbols``
    ABB constraints: Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        action: Query parameter. Optional.
        view: Body parameter. Optional.
        vartyp: Body parameter. Optional.
        blockurl: Body parameter. Optional.
        recursive: Body parameter. Optional.
        posl: Body parameter. Optional.
        posc: Body parameter. Optional.
        stack: Body parameter. Optional.
        onlyused: Body parameter. Optional.
        skipshared: Body parameter. Optional.
        regexp: Body parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD REQUEST(400) see

    Example:
        # curl --digest -u "Default User":robotics -d
            "view=block&vartyp=any&blockurl=RAPID/T_ROB1&symtyp=var&recursive=true&datty
    """
    return await client.post(
        "/rw/rapid/symbols",
        params={k: v for k, v in {"action": action}.items() if v is not None},
        data={k: v for k, v in {"view": view, "vartyp": vartyp, "blockurl": blockurl, "recursive": recursive, "posl": posl, "posc": posc, "stack": stack, "onlyused": onlyused, "skipshared": skipshared, "regexp": regexp}.items() if v is not None},
    )

async def get_object_extension_list(
    client: RWSClient,
    symbol_url: str,
    info: str | None = None,
    type: str | None = None,
    statements: str | None = None,
    backwardstmts: str | None = None,
    undostmts: str | None = None,
    typedecls: str | None = None,
) -> httpx.Response:
    """
    Get Object Extension List.

    Route: ``GET /rw/rapid/symbols/{symbol URL}``
    ABB constraints: Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        symbol_url: URL path parameter.
        info: Query parameter. Optional.
        type: Query parameter. Optional.
        statements: Query parameter. Optional.
        backwardstmts: Query parameter. Optional.
        undostmts: Query parameter. Optional.
        typedecls: Query parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD_REQUEST (400)

    Example:
        # curl --digest -u "Default User":robotics" "
    """
    return await client.get(
        f"/rw/rapid/symbols/{symbol_url}",
        params={k: v for k, v in {"info": info, "type": type, "statements": statements, "backwardstmts": backwardstmts, "undostmts": undostmts, "typedecls": typedecls}.items() if v is not None},
    )
