# This file is AUTO-GENERATED by contrib/generator/main.py
# DO NOT EDIT MANUALLY — run the generator to regenerate.
#  Generator author: Clement RACINET
"""
RWS module: RobotWare Services → RAPID Service → Operations on Rapid taskpanel

1:1 mirror of the ABB RobotWare 6 REST API.
Each function maps to exactly one HTTP endpoint.
No composed logic — see highlevel/ for wrappers.
"""
from __future__ import annotations

import httpx

from abb_rws_client._core.client import RWSClient


async def get_user_modify_from_taskpanel(client: RWSClient) -> httpx.Response:
    """
    Get user modify from taskpanel.

    Route: ``GET /rw/rapid/taskselection``
    ABB constraints: Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD_REQUEST(400) , see

    Example:
        ```python
        >>> await get_user_modify_from_taskpanel(client)
        <Response [200]>
        ```
    """
    return await client.get("/rw/rapid/taskselection")

async def subscribe_on_tasks_panel_change(
    client: RWSClient,
    identifier: str | None = None,
    identifier_p: str | None = None,
) -> httpx.Response:
    """
    Subscribe on Tasks panel change.

    Route: ``POST /subscription``
    ABB constraints: Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        identifier: Body parameter. Optional.
        identifier_p: Body parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 201.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD_REQUEST(400), UNSUPPORTED_MEDIA(415)

    Example:
        ```python
        >>> await subscribe_on_tasks_panel_change(client)
        <Response [201]>
        ```
    """
    return await client.post(
        "/subscription",
        data={
            k: v
            for k, v in {
                "identifier": identifier,
                "identifier_p": identifier_p
            }.items()
            if v is not None
        },
    )
