# This file is AUTO-GENERATED by contrib/generator/main.py
# DO NOT EDIT MANUALLY — run the generator to regenerate.
"""
RWS module : RobotWare Services → RAPID Service → Operations on RAPID UI instructions

Miroir 1:1 de l'API REST ABB RobotWare 6.
Chaque fonction correspond à exactement un endpoint HTTP.
Aucune logique composée — voir highlevel/ pour les wrappers.
"""
from __future__ import annotations

import httpx

from abb_rws_client._core.client import RWSClient


async def get_ui_instruction_resource(client: RWSClient) -> httpx.Response:
    """
    Get UI instruction resource.

    Route: ``GET /rw/rapid/uiinstr``
    Contraintes ABB: Not supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 200.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: NOT FOUND(404), see

    Example:
        # curl --digest -u "Default User":robotics "http://127.0.0.1/rw/rapid/uiinstr"
    """
    return await client.get("/rw/rapid/uiinstr")

async def get_ui_instruction_actions(
    client: RWSClient,
    action: str | None = None,
) -> httpx.Response:
    """
    Get UI instruction actions.

    Route: ``GET /rw/rapid/uiinstr``
    Contraintes ABB: Not supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        action: Paramètre query. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 200.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: Bad Request(400), see

    Example:
        # curl --digest -u "Default User":robotics "http://127.0.0.1/rw/rapid/uiinstr?action=show"
    """
    return await client.get("/rw/rapid/uiinstr", params={k: v for k, v in {"action": action}.items() if v is not None})

async def subscribe_on_ui_instruction(
    client: RWSClient,
    resources: str | None = None,
) -> httpx.Response:
    """
    Subscribe on UI instruction.

    Route: ``POST /subscription``
    Contraintes ABB: Not supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        resources: Paramètre body. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 201.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD_REQUEST(400), see

    Example:
        # Subscribe on UI Events
    """
    return await client.post("/subscription", data={k: v for k, v in {"resources": resources}.items() if v is not None})

async def get_active_ui_instruction(client: RWSClient) -> httpx.Response:
    """
    Get Active UI Instruction.

    Route: ``GET /rw/rapid/uiinstr/active``
    Contraintes ABB: Not supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 200.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD REQUEST(400),NOT_FOUND(404) see

    Example:
        # curl --digest -u "Default User":robotics "http://127.0.0.1/rw/rapid/uiinstr/active"
    """
    return await client.get("/rw/rapid/uiinstr/active")

async def get_active_ui_instruction_actions(
    client: RWSClient,
    action: str | None = None,
) -> httpx.Response:
    """
    Get Active UI instruction actions.

    Route: ``GET /rw/rapid/uiinstr/active``
    Contraintes ABB: Not supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        action: Paramètre query. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 200.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: Bad Request(400), see

    Example:
        # curl --digest -u "Default User":robotics "http://localhost/rw/rapid/uiinstr/active?action=show"
    """
    return await client.get("/rw/rapid/uiinstr/active", params={k: v for k, v in {"action": action}.items() if v is not None})

async def update_an_active_ui_instruction_parameter(
    client: RWSClient,
    stackurl: str,
    uiparam: str,
    action: str | None = None,
    value: str | None = None,
) -> httpx.Response:
    """
    Update an Active UI Instruction Parameter.

    Route: ``POST /rw/rapid/uiinstr/active/param/{stackurl}/{uiparam}``
    Contraintes ABB: -Not supported in bootserver mode -{stackurl} ends with a variable number, which can be obtained from "Get Active UI Instruction" API. -RAPID program should be running -Example of {uiparam} are TPFK1, TPFK2, TPFK3, TPCompleted etc

    Args:
        client: Instance RWSClient ouverte.
        stackurl: Paramètre de chemin URL.
        uiparam: Paramètre de chemin URL.
        action: Paramètre query. Optionnel.
        value: Paramètre body. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 204.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD REQUEST(400),NOT_FOUND(404),FORBIDDEN(403) see

    Example:
        # curl --digest -u "Default User":robotics -d "value=0" -X POST "http://127.0.0.1/rw/rapid/uiinstr/active/param/RAPID/T_RO
    """
    return await client.post(f"/rw/rapid/uiinstr/active/param/{stackurl}/{uiparam}", params={k: v for k, v in {"action": action}.items() if v is not None}, data={k: v for k, v in {"value": value}.items() if v is not None})

async def get_parameter_value_for_an_active_ui(
    client: RWSClient,
    stackurl: str,
    uiparam: str,
) -> httpx.Response:
    """
    Get parameter value for an active UI instruction.

    Route: ``GET /rw/rapid/uiinstr/active/param/{stackurl}/{uiparam}``
    Contraintes ABB: Not supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        stackurl: Paramètre de chemin URL.
        uiparam: Paramètre de chemin URL.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 200.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD_REQUEST(400) , NOT_FOUND(404) see

    Example:
        # curl --digest -u "Default User":robotics "http://127.0.0.1/rw/rapid/uiinstr/active/param/RAPID/T_ROB1/%25%2499/Result"
    """
    return await client.get(f"/rw/rapid/uiinstr/active/param/{stackurl}/{uiparam}")

async def get_active_ui_instruction_parameters(
    client: RWSClient,
    stackurl: str,
) -> httpx.Response:
    """
    Get active UI instruction parameters.

    Route: ``GET /rw/rapid/uiinstr/active/params/{stackurl}``
    Contraintes ABB: Not supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        stackurl: Paramètre de chemin URL.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 200.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD_REQUEST(400), NOT_FOUND(404), see

    Example:
        # curl --digest -u "Default User":robotics "http://127.0.0.1/rw/rapid/uiinstr/active/params/RAPID/T_ROB1/%25%2499"
    """
    return await client.get(f"/rw/rapid/uiinstr/active/params/{stackurl}")
