# This file is AUTO-GENERATED by utils/generator/main.py
# DO NOT EDIT MANUALLY — run the generator to regenerate.
#  Generator author: Clement RACINET
"""
RWS module: RobotWare Services → CFG Service → Get CFG resources

1:1 mirror of the ABB RobotWare 6 REST API.
Each function maps to exactly one HTTP endpoint.
No composed logic — see highlevel/ for wrappers.
"""
from __future__ import annotations

import httpx

from abb_rws_client_python_rw6.core.client import RWSClient


async def get_cfg_resources(client: RWSClient) -> httpx.Response:
    """
    Get CFG resources.

    Route: ``GET /rw/cfg``
    ABB constraints: Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.

    Example:
        ```python
        >>> await get_cfg_resources(client)
        <Response [200]>
        ```
    """
    return await client.get("/rw/cfg")

async def get_cfg_actions(
    client: RWSClient,
    action: str | None = None,
) -> httpx.Response:
    """
    Get CFG actions.

    Route: ``GET /rw/cfg``
    ABB constraints: Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        action: Query parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD_REQUEST(400)

    Example:
        ```python
        >>> await get_cfg_actions(client)
        <Response [200]>
        ```
    """
    return await client.get(
        "/rw/cfg",
        params={k: v for k, v in {"action": action}.items() if v is not None},
    )

async def validate_cfg_file(
    client: RWSClient,
    action: str | None = None,
) -> httpx.Response:
    """
    Validate CFG file.

    Route: ``POST /rw/cfg``
    ABB constraints: Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        action: Query parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD_REQUEST(400), UNSUPPORTED_MEDIA(415)

    Example:
        ```python
        >>> await validate_cfg_file(client)
        <Response [200]>
        ```
    """
    return await client.post(
        "/rw/cfg",
        params={k: v for k, v in {"action": action}.items() if v is not None},
        data={},
    )

async def load_cfg_file(
    client: RWSClient,
    action: str | None = None,
) -> httpx.Response:
    """
    Load CFG file.

    Route: ``POST /rw/cfg``
    ABB constraints: Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        action: Query parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 204.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD_REQUEST(400)

    Example:
        ```python
        >>> await load_cfg_file(client)
        <Response [204]>
        ```
    """
    return await client.post(
        "/rw/cfg",
        params={k: v for k, v in {"action": action}.items() if v is not None},
        data={},
    )

async def validate_cfg_instance_before_delete(
    client: RWSClient,
    action: str | None = None,
    name: str | None = None,
) -> httpx.Response:
    """
    Validate CFG Instance before Delete.

    Route: ``POST /rw/cfg``
    ABB constraints: Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        action: Query parameter. Optional.
        name: Body parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 204.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD_REQUEST(400), NOT_FOUND(404), see

    Example:
        ```python
        >>> await validate_cfg_instance_before_delete(client)
        <Response [204]>
        ```
    """
    return await client.post(
        "/rw/cfg",
        params={k: v for k, v in {"action": action}.items() if v is not None},
        data={k: v for k, v in {"name": name}.items() if v is not None},
    )

async def validate_cfg_instances(
    client: RWSClient,
    action: str | None = None,
    operation: str | None = None,
    cfgdomain: str | None = None,
    cfgtype: str | None = None,
    instances: str | None = None,
    instancescount: str | None = None,
) -> httpx.Response:
    """
    Validate CFG Instances.

    Route: ``POST /rw/cfg``
    ABB constraints: Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        action: Query parameter. Optional.
        operation: Body parameter. Optional.
        cfgdomain: Body parameter. Optional.
        cfgtype: Body parameter. Optional.
        instances: Body parameter. Optional.
        instancescount: Body parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 204.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD_REQUEST(400), NOT_FOUND(404), see

    Example:
        ```python
        >>> await validate_cfg_instances(client)
        <Response [204]>
        ```
    """
    return await client.post(
        "/rw/cfg",
        params={k: v for k, v in {"action": action}.items() if v is not None},
        data={
            k: v
            for k, v in {
                "operation": operation,
                "cfgdomain": cfgdomain,
                "cfgtype": cfgtype,
                "instances": instances,
                "instancescount": instancescount
            }.items()
            if v is not None
        },
    )

async def post_keyless_motor_on(
    client: RWSClient,
    action: str | None = None,
    state: str | None = None,
) -> httpx.Response:
    """
    Keyless motor ON.

    Route: ``POST /rw/cfg``
    ABB constraints: Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        action: Query parameter. Optional.
        state: Body parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 204.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD_REQUEST(400) see

    Example:
        ```python
        >>> await post_keyless_motor_on(client)
        <Response [204]>
        ```
    """
    return await client.post(
        "/rw/cfg",
        params={k: v for k, v in {"action": action}.items() if v is not None},
        data={k: v for k, v in {"state": state}.items() if v is not None},
    )

async def subscribe_on_cfg_changecount(
    client: RWSClient,
    identifier: str | None = None,
    identifier_p: str | None = None,
) -> httpx.Response:
    """
    Subscribe on cfg ChangeCount.

    Route: ``POST /subscription``
    ABB constraints: Not supported in bootserver mode.

    Args:
        client: Open RWSClient instance.
        identifier: Body parameter. Optional.
        identifier_p: Body parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 201.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD_REQUEST(400), UNSUPPORTED_MEDIA(415)

    Example:
        ```python
        >>> await subscribe_on_cfg_changecount(client)
        <Response [201]>
        ```
    """
    return await client.post(
        "/subscription",
        data={
            k: v
            for k, v in {
                "identifier": identifier,
                "identifier_p": identifier_p
            }.items()
            if v is not None
        },
    )

async def get_cfg_domain_types(
    client: RWSClient,
    domain: str,
    start: str | None = None,
    limit: str | None = None,
) -> httpx.Response:
    """
    Get CFG Domain Types.

    Route: ``GET /rw/cfg/{domain}``
    ABB constraints: Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        domain: URL path parameter.
        start: Query parameter. Optional.
        limit: Query parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.

    Example:
        ```python
        >>> await get_cfg_domain_types(client, "domain_value")
        <Response [200]>
        ```
    """
    return await client.get(
        f"/rw/cfg/{domain}",
        params={k: v for k, v in {"start": start, "limit": limit}.items() if v is not None},
    )

async def get_actions_on_cfg_domain(
    client: RWSClient,
    domain: str,
    action: str | None = None,
) -> httpx.Response:
    """
    Get Actions on a CFG domain.

    Route: ``GET /rw/cfg/{domain}``
    ABB constraints: CFG Mastership is handled internally if not explicit held by the client. Not
        supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        domain: URL path parameter.
        action: Query parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD_REQUEST(400)

    Example:
        ```python
        >>> await get_actions_on_cfg_domain(client, "domain_value")
        <Response [200]>
        ```
    """
    return await client.get(
        f"/rw/cfg/{domain}",
        params={k: v for k, v in {"action": action}.items() if v is not None},
    )

async def save_cfg_domain(
    client: RWSClient,
    domain: str,
    action: str | None = None,
) -> httpx.Response:
    """
    Save CFG domain.

    Route: ``POST /rw/cfg/{domain}``
    ABB constraints: Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        domain: URL path parameter.
        action: Query parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 204.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD_REQUEST(400), FORBIDDEN(403), UNAUTHORIZED(401)

    Example:
        ```python
        >>> await save_cfg_domain(client, "domain_value")
        <Response [204]>
        ```
    """
    return await client.post(
        f"/rw/cfg/{domain}",
        params={k: v for k, v in {"action": action}.items() if v is not None},
        data={},
    )

async def reset_cfg_domain(
    client: RWSClient,
    domain: str,
    action: str | None = None,
) -> httpx.Response:
    """
    Reset CFG domain.

    Route: ``POST /rw/cfg/{domain}``
    ABB constraints: Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        domain: URL path parameter.
        action: Query parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD_REQUEST(400)

    Example:
        ```python
        >>> await reset_cfg_domain(client, "domain_value")
        <Response [200]>
        ```
    """
    return await client.post(
        f"/rw/cfg/{domain}",
        params={k: v for k, v in {"action": action}.items() if v is not None},
        data={},
    )

async def get_cfg_type(
    client: RWSClient,
    domain: str,
    type: str,
) -> httpx.Response:
    """
    Get CFG type.

    Route: ``GET /rw/cfg/{domain}/{type}``
    ABB constraints: Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        domain: URL path parameter.
        type: URL path parameter.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: NOT_FOUND(404)

    Example:
        ```python
        >>> await get_cfg_type(client, "domain_value", "type_value")
        <Response [200]>
        ```
    """
    return await client.get(f"/rw/cfg/{domain}/{type}")

async def get_all_attributes_of_the_given_domain(
    client: RWSClient,
    domain: str,
    type: str,
) -> httpx.Response:
    """
    Get all attributes of the given domain type.

    Route: ``GET /rw/cfg/{domain}/{type}/attributes``
    ABB constraints: Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        domain: URL path parameter.
        type: URL path parameter.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD_REQUEST(400)

    Example:
        ```python
        >>> await get_all_attributes_of_the_given_domain(client, "domain_value", "type_value")
        <Response [200]>
        ```
    """
    return await client.get(f"/rw/cfg/{domain}/{type}/attributes")

async def get_all_instances_of_the_given_domain(
    client: RWSClient,
    domain: str,
    type: str,
) -> httpx.Response:
    """
    Get all instances of the given domain type.

    Route: ``GET /rw/cfg/{domain}/{type}/instances``
    ABB constraints: Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        domain: URL path parameter.
        type: URL path parameter.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD_REQUEST(400)

    Example:
        ```python
        >>> await get_all_instances_of_the_given_domain(client, "domain_value", "type_value")
        <Response [200]>
        ```
    """
    return await client.get(f"/rw/cfg/{domain}/{type}/instances")

async def get_actions_on_cfg_instances(
    client: RWSClient,
    domain: str,
    type: str,
    action: str | None = None,
) -> httpx.Response:
    """
    Get actions on CFG instances.

    Route: ``GET /rw/cfg/{domain}/{type}/instances``
    ABB constraints: Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        domain: URL path parameter.
        type: URL path parameter.
        action: Query parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD_REQUEST(400)

    Example:
        ```python
        >>> await get_actions_on_cfg_instances(client, "domain_value", "type_value")
        <Response [200]>
        ```
    """
    return await client.get(
        f"/rw/cfg/{domain}/{type}/instances",
        params={k: v for k, v in {"action": action}.items() if v is not None},
    )

async def reset_cfg_instances(
    client: RWSClient,
    domain: str,
    type: str,
    action: str | None = None,
) -> httpx.Response:
    """
    Reset CFG instances.

    Route: ``POST /rw/cfg/{domain}/{type}/instances``
    ABB constraints: Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        domain: URL path parameter.
        type: URL path parameter.
        action: Query parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 204.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD_REQUEST(400)

    Example:
        ```python
        >>> await reset_cfg_instances(client, "domain_value", "type_value")
        <Response [204]>
        ```
    """
    return await client.post(
        f"/rw/cfg/{domain}/{type}/instances",
        params={k: v for k, v in {"action": action}.items() if v is not None},
        data={},
    )

async def create_default_cfg_instance(
    client: RWSClient,
    domain: str,
    type: str,
    action: str | None = None,
) -> httpx.Response:
    """
    Create default CFG instance.

    Route: ``POST /rw/cfg/{domain}/{type}/instances``
    ABB constraints: Use location header to fetch information about newly created resource. Not
        supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        domain: URL path parameter.
        type: URL path parameter.
        action: Query parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 201.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD_REQUEST(400)

    Example:
        ```python
        >>> await create_default_cfg_instance(client, "domain_value", "type_value")
        <Response [201]>
        ```
    """
    return await client.post(
        f"/rw/cfg/{domain}/{type}/instances",
        params={k: v for k, v in {"action": action}.items() if v is not None},
        data={},
    )

async def get_cfg_instance(
    client: RWSClient,
    domain: str,
    type: str,
    instance_name: str,
) -> httpx.Response:
    """
    Get CFG instance.

    Route: ``GET /rw/cfg/{domain}/{type}/instances/{instance name}``
    ABB constraints: Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        domain: URL path parameter.
        type: URL path parameter.
        instance_name: URL path parameter.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD_REQUEST(400)

    Example:
        ```python
        >>> await get_cfg_instance(client, "domain_value", "type_value", "instance_name_value")
        <Response [200]>
        ```
    """
    return await client.get(f"/rw/cfg/{domain}/{type}/instances/{instance_name}")

async def get_cfg_instance_actions(
    client: RWSClient,
    domain: str,
    type: str,
    instance: str,
    action: str | None = None,
) -> httpx.Response:
    """
    Get CFG instance actions.

    Route: ``GET /rw/cfg/{domain}/{type}/instances/{instance}``
    ABB constraints: Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        domain: URL path parameter.
        type: URL path parameter.
        instance: URL path parameter.
        action: Query parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD_REQUEST(400)

    Example:
        ```python
        >>> await get_cfg_instance_actions(
        ...     client,
        ...     "domain_value",
        ...     "type_value",
        ...     "instance_value"
        ... )
        <Response [200]>
        ```
    """
    return await client.get(
        f"/rw/cfg/{domain}/{type}/instances/{instance}",
        params={k: v for k, v in {"action": action}.items() if v is not None},
    )

async def update_cfg_instance(
    client: RWSClient,
    domain: str,
    type: str,
    instance: str,
    action: str | None = None,
    attribute_name: str | None = None,
) -> httpx.Response:
    """
    Update CFG instance.

    Route: ``POST /rw/cfg/{domain}/{type}/instances/{instance}``
    ABB constraints: Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        domain: URL path parameter.
        type: URL path parameter.
        instance: URL path parameter.
        action: Query parameter. Optional.
        attribute_name: Body parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 204.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: UNSUPPORTED_MEDIA(415), BAD_REQUEST(400)

    Example:
        ```python
        >>> await update_cfg_instance(client, "domain_value", "type_value", "instance_value")
        <Response [204]>
        ```
    """
    return await client.post(
        f"/rw/cfg/{domain}/{type}/instances/{instance}",
        params={k: v for k, v in {"action": action}.items() if v is not None},
        data={k: v for k, v in {"attribute_name": attribute_name}.items() if v is not None},
    )

async def delete_cfg_instance(
    client: RWSClient,
    domain: str,
    type: str,
    instance: str,
) -> httpx.Response:
    """
    Delete CFG instance.

    Route: ``DELETE /rw/cfg/{domain}/{type}/instances/{instance}``
    ABB constraints: Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        domain: URL path parameter.
        type: URL path parameter.
        instance: URL path parameter.

    Returns:
        Raw HTTP response. Expected success: HTTP 204.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD_REQUEST(400)

    Example:
        ```python
        >>> await delete_cfg_instance(client, "domain_value", "type_value", "instance_value")
        <Response [204]>
        ```
    """
    return await client.delete(f"/rw/cfg/{domain}/{type}/instances/{instance}")
