# This file is AUTO-GENERATED by contrib/generator/main.py
# DO NOT EDIT MANUALLY — run the generator to regenerate.
"""Tests unitaires auto-générés pour rws/ctrl/clock."""
from __future__ import annotations

import pytest
import httpx

from abb_rws_client._core.client import RWSClient
from abb_rws_client.rws.ctrl.clock import (
    get_clock_resource,
    get_clock_actions,
    set_the_clock_of_the_controller,
    get_timezone_resource,
    get_timezone_actions,
    set_the_time_zone,
    get_time_server_resource,
    get_time_server_actions,
    set_the_time_server,
    get_test_time_server,
)


class _MockTransport(httpx.AsyncBaseTransport):
    """Transport mock retournant une réponse HTTP configurable."""

    def __init__(self, status_code: int = 200, content: bytes = b"") -> None:
        self.status_code = status_code
        self.content = content
        self.last_request: httpx.Request | None = None

    async def handle_async_request(self, request: httpx.Request) -> httpx.Response:
        self.last_request = request
        return httpx.Response(self.status_code, content=self.content, request=request)


def _make_client(transport: _MockTransport) -> RWSClient:
    """Construit un RWSClient branché sur le transport mock."""
    client = RWSClient.__new__(RWSClient)
    client._http = httpx.AsyncClient(
        transport=transport,
        base_url="http://localhost/",
    )
    client.host = "localhost"
    return client


@pytest.mark.asyncio
async def test_get_clock_resource() -> None:
    """Vérifie que get_clock_resource émet GET /ctrl/clock."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_clock_resource(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/ctrl/clock"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_clock_actions() -> None:
    """Vérifie que get_clock_actions émet GET /ctrl/clock."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_clock_actions(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/ctrl/clock"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_set_the_clock_of_the_controller() -> None:
    """Vérifie que set_the_clock_of_the_controller émet PUT /ctrl/clock."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await set_the_clock_of_the_controller(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "PUT"
    assert transport.last_request.url.path == "/ctrl/clock"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_get_timezone_resource() -> None:
    """Vérifie que get_timezone_resource émet GET /ctrl/clock/timezone."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_timezone_resource(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/ctrl/clock/timezone"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_timezone_actions() -> None:
    """Vérifie que get_timezone_actions émet GET /ctrl/clock/timezone?action=show."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_timezone_actions(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/ctrl/clock/timezone"
    assert transport.last_request.url.params["action"] == "show"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_set_the_time_zone() -> None:
    """Vérifie que set_the_time_zone émet POST /ctrl/clock/timezone."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await set_the_time_zone(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/ctrl/clock/timezone"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_get_time_server_resource() -> None:
    """Vérifie que get_time_server_resource émet GET /ctrl/clock/timeserver."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_time_server_resource(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/ctrl/clock/timeserver"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_time_server_actions() -> None:
    """Vérifie que get_time_server_actions émet GET /ctrl/clock/timeserver?action=show."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_time_server_actions(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/ctrl/clock/timeserver"
    assert transport.last_request.url.params["action"] == "show"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_set_the_time_server() -> None:
    """Vérifie que set_the_time_server émet POST /ctrl/clock/timeserver."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await set_the_time_server(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/ctrl/clock/timeserver"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_get_test_time_server() -> None:
    """Vérifie que get_test_time_server émet GET /ctrl/clock/timeserver."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_test_time_server(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/ctrl/clock/timeserver"
    assert resp.status_code == 200
