# This file is AUTO-GENERATED by contrib/generator/main.py
# DO NOT EDIT MANUALLY — run the generator to regenerate.
#  Generator author: Clément RACINET
"""Auto-generated unit tests for rws/ctrl/backup."""
from __future__ import annotations

import pytest
import httpx

from abb_rws_client._core.client import RWSClient
from abb_rws_client.rws.ctrl.backup import (
    get_backup_resources,
    get_backup_actions,
    create_backup,
    post_restore_backup,
    get_check_restore,
    get_backup_state,
    subscribe_on_backup_system_information,
    get_backup_system_information,
)


class _MockTransport(httpx.AsyncBaseTransport):
    """Mock transport returning a configurable HTTP response."""

    def __init__(self, status_code: int = 200, content: bytes = b"") -> None:
        self.status_code = status_code
        self.content = content
        self.last_request: httpx.Request | None = None

    async def handle_async_request(self, request: httpx.Request) -> httpx.Response:
        self.last_request = request
        return httpx.Response(self.status_code, content=self.content, request=request)


def _make_client(transport: _MockTransport) -> RWSClient:
    """Build an RWSClient connected to the mock transport."""
    client = RWSClient.__new__(RWSClient)
    client._http = httpx.AsyncClient(
        transport=transport,
        base_url="http://localhost/",
    )
    client.host = "localhost"
    return client


@pytest.mark.asyncio
async def test_get_backup_resources() -> None:
    """Verify that get_backup_resources sends GET /ctrl/backup."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_backup_resources(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/ctrl/backup"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_backup_actions() -> None:
    """Verify that get_backup_actions sends GET /ctrl/backup."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_backup_actions(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/ctrl/backup"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_create_backup() -> None:
    """Verify that create_backup sends POST /ctrl/backup."""
    transport = _MockTransport(status_code=202)
    client = _make_client(transport)

    resp = await create_backup(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/ctrl/backup"
    assert resp.status_code == 202

@pytest.mark.asyncio
async def test_post_restore_backup() -> None:
    """Verify that post_restore_backup sends POST /ctrl/backup."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await post_restore_backup(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/ctrl/backup"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_get_check_restore() -> None:
    """Verify that get_check_restore sends GET /ctrl/backup."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_check_restore(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/ctrl/backup"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_backup_state() -> None:
    """Verify that get_backup_state sends GET /ctrl/backup."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_backup_state(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/ctrl/backup"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_subscribe_on_backup_system_information() -> None:
    """Verify that subscribe_on_backup_system_information sends POST /subscription."""
    transport = _MockTransport(status_code=201)
    client = _make_client(transport)

    resp = await subscribe_on_backup_system_information(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/subscription"
    assert resp.status_code == 201

@pytest.mark.asyncio
async def test_get_backup_system_information() -> None:
    """Verify that get_backup_system_information sends GET /ctrl/backup/info/."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_backup_system_information(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/ctrl/backup/info/"
    assert resp.status_code == 200
