# This file is AUTO-GENERATED by contrib/generator/main.py
# DO NOT EDIT MANUALLY — run the generator to regenerate.
"""
RWS module : RobotWare Services → IO Service → Operations on IO Networks

Miroir 1:1 de l'API REST ABB RobotWare 6.
Chaque fonction correspond à exactement un endpoint HTTP.
Aucune logique composée — voir highlevel/ pour les wrappers.
"""
from __future__ import annotations

import httpx

from abb_rws_client._core.client import RWSClient


async def get_io_networks_resources(client: RWSClient) -> httpx.Response:
    """
    Get IO Networks resources.

    Route: ``GET /rw/iosystem/networks``
    Contraintes ABB: Not supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 200.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD_REQUEST(400)

    Example:
        # curl --digest -u "Default User":robotics "http://localhost/rw/iosystem/networks"
    """
    return await client.get("/rw/iosystem/networks")

async def get_actions_on_io_networks(
    client: RWSClient,
    action: str | None = None,
) -> httpx.Response:
    """
    Get Actions on IO Networks.

    Route: ``GET /rw/iosystem/networks``
    Contraintes ABB: Not supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        action: Paramètre query. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 200.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD_REQUEST(400)

    Example:
        # curl --digest -u "Default User":robotics "http://localhost/rw/iosystem/networks?action=show"
    """
    return await client.get("/rw/iosystem/networks", params={k: v for k, v in {"action": action}.items() if v is not None})

async def post_search_io_networks(
    client: RWSClient,
    action: str | None = None,
    name_or_state_example_name: str | None = None,
) -> httpx.Response:
    """
    Search IO Networks.

    Route: ``POST /rw/iosystem/networks``
    Contraintes ABB: Not supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        action: Paramètre query. Optionnel.
        name_or_state_example_name: Paramètre body. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 200.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD_REQUEST(400)

    Example:
        # Search IO Networks
    """
    return await client.post("/rw/iosystem/networks", params={k: v for k, v in {"action": action}.items() if v is not None}, data={k: v for k, v in {"name_or_state_example_name": name_or_state_example_name}.items() if v is not None})
