# This file is AUTO-GENERATED by contrib/generator/main.py
# DO NOT EDIT MANUALLY — run the generator to regenerate.
"""Tests unitaires auto-générés pour rws/iosystem/devices."""
from __future__ import annotations

import pytest
import httpx

from abb_rws_client._core.client import RWSClient
from abb_rws_client.rws.iosystem.devices import (
    get_io_devices,
    get_actions_io_devices,
    post_search_io_devices,
)


class _MockTransport(httpx.AsyncBaseTransport):
    """Transport mock retournant une réponse HTTP configurable."""

    def __init__(self, status_code: int = 200, content: bytes = b"") -> None:
        self.status_code = status_code
        self.content = content
        self.last_request: httpx.Request | None = None

    async def handle_async_request(self, request: httpx.Request) -> httpx.Response:
        self.last_request = request
        return httpx.Response(self.status_code, content=self.content, request=request)


def _make_client(transport: _MockTransport) -> RWSClient:
    """Construit un RWSClient branché sur le transport mock."""
    client = RWSClient.__new__(RWSClient)
    client._http = httpx.AsyncClient(
        transport=transport,
        base_url="http://localhost/",
    )
    client.host = "localhost"
    return client


@pytest.mark.asyncio
async def test_get_io_devices() -> None:
    """Vérifie que get_io_devices émet GET /rw/iosystem/devices."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_io_devices(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/iosystem/devices"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_actions_io_devices() -> None:
    """Vérifie que get_actions_io_devices émet GET /rw/iosystem/devices."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_actions_io_devices(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/iosystem/devices"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_post_search_io_devices() -> None:
    """Vérifie que post_search_io_devices émet POST /rw/iosystem/devices."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await post_search_io_devices(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/iosystem/devices"
    assert resp.status_code == 200
