# This file is AUTO-GENERATED by contrib/generator/main.py
# DO NOT EDIT MANUALLY — run the generator to regenerate.
#  Generator author: Clement RACINET
"""Auto-generated unit tests for rws/iosystem/iosystem."""
from __future__ import annotations

import httpx
import pytest

from abb_rws_client._core.client import RWSClient
from abb_rws_client.rws.iosystem.iosystem import (
    get_an_io_signal,
    get_eio_device_status_information,
    get_io_device,
    get_io_device_actions,
    get_io_device_configuration_properties,
    get_io_network,
    get_io_network_actions,
    get_io_network_configuration_properties,
    get_io_signal_actions,
    get_io_signal_configuration_properties,
    get_io_system_resources,
    options_send_device_command_actions,
    post_send_device_command,
    set_input_data,
    set_output_data,
    subscribe_io_device,
    subscribe_io_network,
    subscribe_io_signal,
    update_io_device,
    update_io_network,
    update_io_network_configuration_type,
    update_io_signal_state,
    update_io_signal_value,
)


class _MockTransport(httpx.AsyncBaseTransport):
    """Mock transport returning a configurable HTTP response."""

    def __init__(self, status_code: int = 200, content: bytes = b"") -> None:
        self.status_code = status_code
        self.content = content
        self.last_request: httpx.Request | None = None

    async def handle_async_request(self, request: httpx.Request) -> httpx.Response:
        self.last_request = request
        return httpx.Response(self.status_code, content=self.content, request=request)


def _make_client(transport: _MockTransport) -> RWSClient:
    """Build an RWSClient connected to the mock transport."""
    client = RWSClient.__new__(RWSClient)
    client._http = httpx.AsyncClient(
        transport=transport,
        base_url="http://localhost/",
    )
    client.host = "localhost"
    return client


@pytest.mark.asyncio
async def test_get_io_system_resources() -> None:
    """
    Verify that get_io_system_resources sends GET /rw/iosystem.
    """
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_io_system_resources(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/iosystem"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_io_network() -> None:
    """
    Verify that get_io_network sends GET /rw/iosystem/networks/{network}.
    """
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_io_network(client, "network_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/iosystem/networks/network_test"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_io_network_actions() -> None:
    """
    Verify that get_io_network_actions sends GET /rw/iosystem/networks/{network}.
    """
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_io_network_actions(client, "network_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/iosystem/networks/network_test"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_update_io_network() -> None:
    """
    Verify that update_io_network sends POST /rw/iosystem/networks/{network}.
    """
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await update_io_network(client, "network_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/iosystem/networks/network_test"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_subscribe_io_network() -> None:
    """
    Verify that subscribe_io_network sends POST /subscription.
    """
    transport = _MockTransport(status_code=201)
    client = _make_client(transport)

    resp = await subscribe_io_network(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/subscription"
    assert resp.status_code == 201

@pytest.mark.asyncio
async def test_get_io_network_configuration_properties() -> None:
    """
    Verify that get_io_network_configuration_properties sends GET
        /rw/iosystem/networks/{network}.
    """
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_io_network_configuration_properties(client, "network_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/iosystem/networks/network_test"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_update_io_network_configuration_type() -> None:
    """
    Verify that update_io_network_configuration_type sends POST /rw/iosystem/networks/{network}.
    """
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await update_io_network_configuration_type(client, "network_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/iosystem/networks/network_test"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_get_io_device() -> None:
    """
    Verify that get_io_device sends GET /rw/iosystem/devices/{device}.
    """
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_io_device(client, "device_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/iosystem/devices/device_test"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_io_device_actions() -> None:
    """
    Verify that get_io_device_actions sends GET /rw/iosystem/devices/{device}.
    """
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_io_device_actions(client, "device_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/iosystem/devices/device_test"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_update_io_device() -> None:
    """
    Verify that update_io_device sends POST /rw/iosystem/devices/{device}.
    """
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await update_io_device(client, "device_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/iosystem/devices/device_test"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_subscribe_io_device() -> None:
    """
    Verify that subscribe_io_device sends POST /subscription.
    """
    transport = _MockTransport(status_code=201)
    client = _make_client(transport)

    resp = await subscribe_io_device(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/subscription"
    assert resp.status_code == 201

@pytest.mark.asyncio
async def test_set_input_data() -> None:
    """
    Verify that set_input_data sends POST /rw/iosystem/devices/{device}.
    """
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await set_input_data(client, "device_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/iosystem/devices/device_test"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_set_output_data() -> None:
    """
    Verify that set_output_data sends POST /rw/iosystem/devices/{device}.
    """
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await set_output_data(client, "device_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/iosystem/devices/device_test"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_get_io_device_configuration_properties() -> None:
    """
    Verify that get_io_device_configuration_properties sends GET /rw/iosystem/devices/{device}.
    """
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_io_device_configuration_properties(client, "device_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/iosystem/devices/device_test"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_eio_device_status_information() -> None:
    """
    Verify that get_eio_device_status_information sends GET
        /rw/iosystem/devices/{network}/{device}/upgradeinfo.
    """
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_eio_device_status_information(client, "network_test", "device_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    expected_path = "/rw/iosystem/devices/network_test/device_test/upgradeinfo"
    assert transport.last_request.url.path == expected_path
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_post_send_device_command() -> None:
    """
    Verify that post_send_device_command sends POST /rw/iosystem/devices/{device}/command.
    """
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await post_send_device_command(client, "device_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/iosystem/devices/device_test/command"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_options_send_device_command_actions() -> None:
    """
    Verify that options_send_device_command_actions sends OPTIONS
        /rw/iosystem/devices/{device}/command.
    """
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await options_send_device_command_actions(client, "device_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "OPTIONS"
    assert transport.last_request.url.path == "/rw/iosystem/devices/device_test/command"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_an_io_signal() -> None:
    """
    Verify that get_an_io_signal sends GET /rw/iosystem/signals/{network}/{unit}/{signal}.
    """
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_an_io_signal(client, "network_test", "unit_test", "signal_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    expected_path = "/rw/iosystem/signals/network_test/unit_test/signal_test"
    assert transport.last_request.url.path == expected_path
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_io_signal_actions() -> None:
    """
    Verify that get_io_signal_actions sends GET /rw/iosystem/signals/{network}/{unit}/{signal}.
    """
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_io_signal_actions(client, "network_test", "unit_test", "signal_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    expected_path = "/rw/iosystem/signals/network_test/unit_test/signal_test"
    assert transport.last_request.url.path == expected_path
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_update_io_signal_state() -> None:
    """
    Verify that update_io_signal_state sends POST
        /rw/iosystem/signals/{network}/{device}/{signal}.
    """
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await update_io_signal_state(client, "network_test", "device_test", "signal_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    expected_path = "/rw/iosystem/signals/network_test/device_test/signal_test"
    assert transport.last_request.url.path == expected_path
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_update_io_signal_value() -> None:
    """
    Verify that update_io_signal_value sends POST
        /rw/iosystem/signals/{network}/{device}/{signal}.
    """
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await update_io_signal_value(client, "network_test", "device_test", "signal_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    expected_path = "/rw/iosystem/signals/network_test/device_test/signal_test"
    assert transport.last_request.url.path == expected_path
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_subscribe_io_signal() -> None:
    """
    Verify that subscribe_io_signal sends POST /subscription.
    """
    transport = _MockTransport(status_code=201)
    client = _make_client(transport)

    resp = await subscribe_io_signal(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/subscription"
    assert resp.status_code == 201

@pytest.mark.asyncio
async def test_get_io_signal_configuration_properties() -> None:
    """
    Verify that get_io_signal_configuration_properties sends GET
        /rw/iosystem/signals/{network}/{unit}/{signal}.
    """
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_io_signal_configuration_properties(
        client,
        "network_test",
        "unit_test",
        "signal_test"
    )

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    expected_path = "/rw/iosystem/signals/network_test/unit_test/signal_test"
    assert transport.last_request.url.path == expected_path
    assert resp.status_code == 200
