# tests/highlevel/test_subscription.py
# Copyright (c) 2026 Clément RACINET
"""Unit tests for abb_rws_client_python_rw6.highlevel.subscription.

Author: Clement RACINET

Covers: payload/limit validation, resource lookup construction, XML event
parsing, WebSocket URL / group id extraction, loopback normalization, and the
full create/delete/watch lifecycle with httpx and websockets mocked.

The tests do not require a real ABB controller.
"""

from __future__ import annotations

from collections.abc import Sequence
import contextlib
from urllib.parse import parse_qsl

import httpx
import pytest

from abb_rws_client_python_rw6.core.client import RWSClient
from abb_rws_client_python_rw6.highlevel import subscription as sub
from abb_rws_client_python_rw6.highlevel.subscription import (
    SubscribedResource,
    SubscriptionHandle,
)

# ---------------------------------------------------------------------------
# Test doubles
# ---------------------------------------------------------------------------


def _build_fake_response(
    headers: dict[str, str],
    text: str,
    status_code: int = 201,
) -> httpx.Response:
    """Build a real httpx.Response for tests.

    Route: N/A — local test helper.

    ABB constraints: The fake response mirrors the response shape consumed by
        ``create_subscription`` after ``POST /subscription``.

    Args:
        headers: Response headers to simulate, e.g. ``Location``.
        text: Response body text.
        status_code: HTTP status code.

    Returns:
        A real ``httpx.Response`` instance.

    Raises:
        No exception is raised by this helper.

    Example:
        ```python
        response = _build_fake_response(
            {"Location": "ws://192.168.125.1:80/poll/1"},
            "<li></li>",
        )
        ```
    """
    return httpx.Response(status_code=status_code, headers=headers, text=text)


def _decode_form_pairs(payload: str) -> list[tuple[str, str]]:
    """Decode a form-urlencoded payload while preserving repeated keys.

    Route: N/A — local test helper.

    ABB constraints: ``POST /subscription`` must repeat the ``resources`` key
        once per resource. A dictionary cannot represent this correctly, so
        tests assert on ordered key-value pairs.

    Args:
        payload: Form-urlencoded payload generated by
            ``_build_subscription_payload``.

    Returns:
        Ordered decoded form key-value pairs.

    Raises:
        No exception is raised by this helper.

    Example:
        ```python
        >>> _decode_form_pairs("resources=1&1=A&1-p=2")
        [('resources', '1'), ('1', 'A'), ('1-p', '2')]
        ```
    """
    return parse_qsl(payload, keep_blank_values=True)


class _FakeRWSClient(RWSClient):
    """Test double for RWSClient.

    Route: N/A — local test double.

    ABB constraints: Only the network-touching methods used by
        ``highlevel.subscription`` are overridden. No real controller is
        contacted.

    Args:
        host: Fake controller host.

    Returns:
        Fake RWS client instance.

    Raises:
        No exception is raised by this test double constructor.

    Example:
        ```python
        client = _FakeRWSClient()
        ```
    """

    def __init__(self, host: str = "192.168.125.1") -> None:
        super().__init__(host=host)
        self.post_calls: list[tuple[str, dict[str, object]]] = []
        self.delete_calls: list[tuple[str, dict[str, object]]] = []
        self._post_response: httpx.Response | None = None
        self._delete_response = httpx.Response(status_code=204)
        self._fake_cookie_header = "-http-session-=abc123; ABBCX=xyz789"

    def set_post_response(self, response: httpx.Response) -> None:
        """Configure the response returned by the next ``post`` call.

        Route: N/A — local test helper.

        ABB constraints: None.

        Args:
            response: Fake response returned by ``post``.

        Returns:
            None.

        Raises:
            No exception is raised by this helper.

        Example:
            ```python
            client.set_post_response(httpx.Response(201))
            ```
        """
        self._post_response = response

    async def post(self, path: str, **kwargs: object) -> httpx.Response:
        """Record a fake POST call and return the configured response.

        Route: Fake ``POST`` transport method.

        ABB constraints: Used to simulate ``POST /subscription``.

        Args:
            path: Requested RWS path.
            **kwargs: Request arguments.

        Returns:
            Configured fake response.

        Raises:
            AssertionError: If no fake response was configured.

        Example:
            ```python
            response = await client.post("/subscription", content="...")
            ```
        """
        self.post_calls.append((path, kwargs))
        assert self._post_response is not None, "post() called without a response"
        return self._post_response

    async def delete(self, path: str, **kwargs: object) -> httpx.Response:
        """Record a fake DELETE call and return the configured response.

        Route: Fake ``DELETE`` transport method.

        ABB constraints: Used to simulate ``DELETE /subscription/{group-id}``.

        Args:
            path: Requested RWS path.
            **kwargs: Request arguments.

        Returns:
            Fake delete response.

        Raises:
            No exception is raised by this fake method.

        Example:
            ```python
            response = await client.delete("/subscription/7")
            ```
        """
        self.delete_calls.append((path, kwargs))
        return self._delete_response

    def session_cookie_header(self) -> str:
        """Return a fixed fake cookie header.

        Route: N/A — local fake session helper.

        ABB constraints: RWS WebSocket subscription handshakes must reuse the
            HTTP session cookies.

        Args:
            None.

        Returns:
            Fake cookie header.

        Raises:
            No exception is raised by this fake method.

        Example:
            ```python
            cookie = client.session_cookie_header()
            ```
        """
        return self._fake_cookie_header


class _FakeWebSocketConnection:
    """Async context manager and iterator standing in for a WebSocket.

    Route: Fake WebSocket ``ws://.../poll/{group-id}``.

    ABB constraints: Mimics the message stream consumed by ``watch_resources``.

    Args:
        messages: Text messages yielded by the fake WebSocket.

    Returns:
        Fake WebSocket connection.

    Raises:
        No exception is raised by this fake constructor.

    Example:
        ```python
        websocket = _FakeWebSocketConnection(["<li></li>"])
        ```
    """

    def __init__(self, messages: list[str]) -> None:
        self._messages = list(messages)

    async def __aenter__(self) -> _FakeWebSocketConnection:
        """Enter the fake WebSocket context.

        Route: Fake WebSocket context manager.

        ABB constraints: None.

        Args:
            None.

        Returns:
            The fake WebSocket connection itself.

        Raises:
            No exception is raised by this fake method.

        Example:
            ```python
            async with _FakeWebSocketConnection([]) as websocket:
                ...
            ```
        """
        return self

    async def __aexit__(self, *exc_info: object) -> bool:
        """Exit the fake WebSocket context.

        Route: Fake WebSocket context manager.

        ABB constraints: Closing the real WebSocket cleans up ABB subscription
            groups server-side. This fake simply exits.

        Args:
            *exc_info: Exception information from the context manager.

        Returns:
            ``False`` so exceptions are not suppressed.

        Raises:
            No exception is raised by this fake method.

        Example:
            ```python
            async with _FakeWebSocketConnection([]):
                ...
            ```
        """
        return False

    def __aiter__(self) -> _FakeWebSocketConnection:
        """Return the async iterator.

        Route: Fake WebSocket message iterator.

        ABB constraints: None.

        Args:
            None.

        Returns:
            The fake WebSocket connection itself.

        Raises:
            No exception is raised by this fake method.

        Example:
            ```python
            async for message in websocket:
                ...
            ```
        """
        return self

    async def __anext__(self) -> str:
        """Yield the next fake WebSocket message.

        Route: Fake WebSocket message iterator.

        ABB constraints: None.

        Args:
            None.

        Returns:
            Next fake WebSocket message.

        Raises:
            StopAsyncIteration: When all messages have been consumed.

        Example:
            ```python
            message = await websocket.__anext__()
            ```
        """
        if not self._messages:
            raise StopAsyncIteration
        return self._messages.pop(0)


def _fake_connect(url: str, **kwargs: object) -> _FakeWebSocketConnection:
    """Return a no-message fake WebSocket connection.

    Route: Fake ``websockets.asyncio.client.connect``.

    ABB constraints: None.

    Args:
        url: WebSocket URL.
        **kwargs: WebSocket connection arguments.

    Returns:
        Fake WebSocket connection.

    Raises:
        No exception is raised by this fake helper.

    Example:
        ```python
        websocket = _fake_connect("ws://192.168.125.1:80/poll/1")
        ```
    """
    return _FakeWebSocketConnection([])


def _failing_connect(url: str, **kwargs: object) -> _FakeWebSocketConnection:
    """Raise before a fake WebSocket can be opened.

    Route: Fake ``websockets.asyncio.client.connect``.

    ABB constraints: This simulates a setup failure after ``POST /subscription``
        but before the WebSocket stream is opened. In that case,
        ``watch_resources`` must perform HTTP fallback cleanup.

    Args:
        url: WebSocket URL.
        **kwargs: WebSocket connection arguments.

    Returns:
        Never returns.

    Raises:
        OSError: Always raised to simulate connection failure.

    Example:
        ```python
        _failing_connect("ws://192.168.125.1:80/poll/1")
        ```
    """
    raise OSError("websocket setup failed")


# ---------------------------------------------------------------------------
# build_rapid_pers_resource_uri
# ---------------------------------------------------------------------------


def test_build_rapid_pers_resource_uri_nominal() -> None:
    """Nominal case: build the exact ABB symbol-data URI for a PERS variable."""
    uri = sub.build_rapid_pers_resource_uri("T_ROB1", "Subscription", "WatchedValue")
    assert uri == "/rw/rapid/symbol/data/RAPID/T_ROB1/Subscription/WatchedValue;value"


# ---------------------------------------------------------------------------
# _validate_resources
# ---------------------------------------------------------------------------


def test_validate_resources_empty_raises() -> None:
    """Error case: reject an empty resource list before any HTTP call."""
    with pytest.raises(ValueError, match="at least one"):
        sub._validate_resources([])


def test_validate_resources_too_many_total_raises() -> None:
    """Error case: reject more than ABB's 1000 low/medium-resource limit."""
    resources = [
        SubscribedResource(f"r{i}", f"/rw/iosystem/signals/S{i};state", "0")
        for i in range(sub._MAX_RESOURCES_TOTAL + 1)
    ]
    with pytest.raises(ValueError, match="1000"):
        sub._validate_resources(resources)


def test_validate_resources_too_many_high_priority_raises() -> None:
    """Error case: reject more than ABB's 64 High-priority-resource limit."""
    resources = [
        SubscribedResource(f"r{i}", f"/rw/iosystem/signals/S{i};state", "2")
        for i in range(sub._MAX_HIGH_PRIORITY_RESOURCES + 1)
    ]
    with pytest.raises(ValueError, match="64"):
        sub._validate_resources(resources)


def test_validate_resources_valid_passes() -> None:
    """Nominal case: accept a valid resource list."""
    resources = [SubscribedResource("a", "/rw/iosystem/signals/A;state", "1")]
    sub._validate_resources(resources)


# ---------------------------------------------------------------------------
# _build_subscription_payload
# ---------------------------------------------------------------------------


def test_build_subscription_payload_single_resource() -> None:
    """Nominal case: one resource produces one repeated-key resource group."""
    resources = [SubscribedResource("a", "/rw/iosystem/signals/A;state", "2")]
    payload = sub._build_subscription_payload(resources)

    assert payload == "resources=1&1=%2Frw%2Fiosystem%2Fsignals%2FA%3Bstate&1-p=2"
    assert _decode_form_pairs(payload) == [
        ("resources", "1"),
        ("1", "/rw/iosystem/signals/A;state"),
        ("1-p", "2"),
    ]


def test_build_subscription_payload_multiple_resources() -> None:
    """Edge case: multiple resources repeat the ``resources`` key in order."""
    resources = [
        SubscribedResource("a", "/rw/iosystem/signals/A;state", "1"),
        SubscribedResource("b", "/rw/iosystem/signals/B;state", "0"),
    ]
    payload = sub._build_subscription_payload(resources)

    assert _decode_form_pairs(payload) == [
        ("resources", "1"),
        ("1", "/rw/iosystem/signals/A;state"),
        ("1-p", "1"),
        ("resources", "2"),
        ("2", "/rw/iosystem/signals/B;state"),
        ("2-p", "0"),
    ]


# ---------------------------------------------------------------------------
# _build_resource_lookup
# ---------------------------------------------------------------------------


def test_build_resource_lookup_rapid_symbol_registers_both_forms() -> None:
    """Nominal case: RAPID PERS resources resolve by full URI and symbolurl."""
    resource = SubscribedResource(
        "watched",
        sub.build_rapid_pers_resource_uri("T_ROB1", "M", "X"),
        "1",
    )
    lookup = sub._build_resource_lookup([resource])
    assert lookup["/rw/rapid/symbol/data/RAPID/T_ROB1/M/X;value"] == "watched"
    assert lookup["RAPID/T_ROB1/M/X"] == "watched"


def test_build_resource_lookup_io_signal_registers_only_full_uri() -> None:
    """Edge case: IO resources do not get a bare RAPID symbol alias."""
    resource = SubscribedResource("do1", "/rw/iosystem/signals/Virtual1/Board1/do1;state", "0")
    lookup = sub._build_resource_lookup([resource])
    assert lookup == {"/rw/iosystem/signals/Virtual1/Board1/do1;state": "do1"}


# ---------------------------------------------------------------------------
# _extract_li_blocks
# ---------------------------------------------------------------------------


def test_extract_li_blocks_splits_multiple_blocks() -> None:
    """Nominal case: return sibling ``<li>`` blocks separately."""
    text = '<li class="a">1</li><li class="b">2</li>'
    blocks = sub._extract_li_blocks(text)
    assert len(blocks) == 2
    assert '"a"' in blocks[0]
    assert '"b"' in blocks[1]


def test_extract_li_blocks_no_match_returns_empty_list() -> None:
    """Edge case: text with no ``<li>`` block returns an empty list."""
    assert sub._extract_li_blocks("<div>no list here</div>") == []


# ---------------------------------------------------------------------------
# _extract_resource_identity
# ---------------------------------------------------------------------------


def test_extract_resource_identity_from_href() -> None:
    """Nominal case: an ``href`` carries the full resource URI."""
    block = (
        '<li class="ios-signalstate-ev"><a href="/rw/iosystem/signals/A;state" rel="self"/></li>'
    )
    assert sub._extract_resource_identity(block) == "/rw/iosystem/signals/A;state"


def test_extract_resource_identity_from_title_with_slash() -> None:
    """Nominal case: a title containing ``/`` is treated as an identity."""
    block = '<li class="rap-data" title="RAPID/T_ROB1/M/X"><span class="value">1</span></li>'
    assert sub._extract_resource_identity(block) == "RAPID/T_ROB1/M/X"


def test_extract_resource_identity_from_generic_title_returns_none() -> None:
    """Edge case: a generic title with no ``/`` is not a resource identity."""
    block = '<li class="rap-value-ev" title="value"><span class="value">1</span></li>'
    assert sub._extract_resource_identity(block) is None


def test_extract_resource_identity_no_match_returns_none() -> None:
    """Error case: a block with no href/title has no identity."""
    assert sub._extract_resource_identity("<li>plain</li>") is None


# ---------------------------------------------------------------------------
# _extract_value
# ---------------------------------------------------------------------------


def test_extract_value_from_value_class() -> None:
    """Nominal case: extract value from RAPID ``class="value"`` span."""
    block = '<li><span class="value">42</span></li>'
    assert sub._extract_value(block) == "42"


def test_extract_value_from_lvalue_class() -> None:
    """Nominal case: extract value from IO ``class="lvalue"`` span."""
    block = '<li><span class="lvalue">1</span></li>'
    assert sub._extract_value(block) == "1"


def test_extract_value_no_span_returns_none() -> None:
    """Edge case: a block with no value span returns ``None``."""
    assert sub._extract_value("<li>no value here</li>") is None


# ---------------------------------------------------------------------------
# _parse_events
# ---------------------------------------------------------------------------


def test_parse_events_single_block_io_signal() -> None:
    """Nominal case: parse an IO event with identity and value in one block."""
    text = (
        '<li class="ios-signalstate-ev">'
        '<a href="/rw/iosystem/signals/Virtual1/Board1/do1;state" rel="self"/>'
        '<span class="lvalue">1</span>'
        "</li>"
    )
    lookup = {"/rw/iosystem/signals/Virtual1/Board1/do1;state": "do1"}
    assert sub._parse_events(text, lookup) == {"do1": "1"}


def test_parse_events_split_block_rapid_pers_variable() -> None:
    """Nominal case: parse RAPID PERS event split across ABB XHTML blocks."""
    text = (
        '<li class="rap-value-ev" title="value">'
        '<a href="/rw/rapid/symbol/data/RAPID/T_ROB1/M/X;value" rel="self"/>'
        "</li>"
        '<li class="rap-data" title="RAPID/T_ROB1/M/X">'
        '<span class="value">99</span>'
        "</li>"
    )
    lookup = sub._build_resource_lookup(
        [SubscribedResource("watched", "/rw/rapid/symbol/data/RAPID/T_ROB1/M/X;value", "1")]
    )
    assert sub._parse_events(text, lookup) == {"watched": "99"}


def test_parse_events_unsubscribed_resource_ignored() -> None:
    """Edge case: ignore an event for a resource outside the lookup."""
    text = (
        '<li class="ios-signalstate-ev">'
        '<a href="/rw/iosystem/signals/Other;state" rel="self"/>'
        '<span class="lvalue">1</span>'
        "</li>"
    )
    assert sub._parse_events(text, lookup={}) == {}


def test_parse_events_value_with_no_pending_identity_ignored() -> None:
    """Edge case: ignore a value span with no prior resolvable identity."""
    text = '<li class="rap-data" title="value"><span class="value">1</span></li>'
    assert sub._parse_events(text, lookup={"x": "name"}) == {}


# ---------------------------------------------------------------------------
# _extract_ws_url_and_group_id
# ---------------------------------------------------------------------------


def test_extract_ws_url_and_group_id_from_location_header() -> None:
    """Nominal case: take the WebSocket URL from the ``Location`` header."""
    ws_url, group_id = sub._extract_ws_url_and_group_id(
        response_text="",
        headers={"Location": "ws://192.168.125.1:80/poll/9"},
    )
    assert ws_url == "ws://192.168.125.1:80/poll/9"
    assert group_id == "9"


def test_extract_ws_url_and_group_id_fallback_to_body_href() -> None:
    """Edge case: recover the WebSocket URL from a body href."""
    ws_url, group_id = sub._extract_ws_url_and_group_id(
        response_text='<a href="ws://192.168.125.1:80/poll/3" rel="self"/>',
        headers={"Content-Type": "text/xml"},
    )
    assert ws_url == "ws://192.168.125.1:80/poll/3"
    assert group_id == "3"


def test_extract_ws_url_and_group_id_missing_url_raises() -> None:
    """Error case: raise when no WebSocket URL is present."""
    with pytest.raises(ValueError, match="Could not extract WebSocket URL"):
        sub._extract_ws_url_and_group_id(response_text="<li>no ws url</li>", headers={})


def test_extract_ws_url_and_group_id_missing_group_id_raises() -> None:
    """Error case: raise when the WebSocket URL has no ``/poll/{id}``."""
    with pytest.raises(ValueError, match="group id"):
        sub._extract_ws_url_and_group_id(
            response_text="",
            headers={"Location": "ws://192.168.125.1:80/other/path"},
        )


# ---------------------------------------------------------------------------
# _normalize_ws_url
# ---------------------------------------------------------------------------


def test_normalize_ws_url_replaces_loopback_ip() -> None:
    """Nominal case: replace ABB loopback URL host by the controller host."""
    client = _FakeRWSClient(host="192.168.125.1")
    result = sub._normalize_ws_url("ws://127.0.0.1:80/poll/9", client)
    assert result == "ws://192.168.125.1:80/poll/9"


def test_normalize_ws_url_replaces_localhost() -> None:
    """Edge case: replace ``localhost`` the same way as ``127.0.0.1``."""
    client = _FakeRWSClient(host="192.168.125.1")
    result = sub._normalize_ws_url("ws://localhost:80/poll/9", client)
    assert result == "ws://192.168.125.1:80/poll/9"


def test_normalize_ws_url_leaves_real_host_unchanged() -> None:
    """Nominal case: leave a non-loopback host untouched."""
    client = _FakeRWSClient(host="192.168.125.1")
    result = sub._normalize_ws_url("ws://10.0.0.5:80/poll/9", client)
    assert result == "ws://10.0.0.5:80/poll/9"


# ---------------------------------------------------------------------------
# create_subscription
# ---------------------------------------------------------------------------


async def test_create_subscription_nominal() -> None:
    """Nominal case: create a subscription from one fake ABB response."""
    client = _FakeRWSClient()
    client.set_post_response(
        _build_fake_response(
            headers={"Location": "ws://127.0.0.1:80/poll/7"},
            text=(
                '<li class="ios-signalstate-ev">'
                '<a href="/rw/iosystem/signals/A;state" rel="self"/>'
                '<span class="lvalue">1</span>'
                "</li>"
            ),
        )
    )
    resources = [SubscribedResource("a", "/rw/iosystem/signals/A;state", "1")]

    handle = await sub.create_subscription(client, resources)

    assert handle.group_id == "7"
    assert handle.ws_url == "ws://192.168.125.1:80/poll/7"
    assert handle.cookie_header == "-http-session-=abc123; ABBCX=xyz789"
    assert handle.initial_values == {"a": "1"}

    path, kwargs = client.post_calls[0]
    assert path == "/subscription"
    assert kwargs["content"] == ("resources=1&1=%2Frw%2Fiosystem%2Fsignals%2FA%3Bstate&1-p=1")


async def test_create_subscription_invalid_resources_raises_before_http_call() -> None:
    """Error case: validation failure happens before any HTTP request."""
    client = _FakeRWSClient()
    with pytest.raises(ValueError, match="at least one"):
        await sub.create_subscription(client, [])
    assert client.post_calls == []


async def test_create_subscription_unparsable_response_raises() -> None:
    """Error case: raise when ABB response contains no WebSocket URL."""
    client = _FakeRWSClient()
    client.set_post_response(_build_fake_response(headers={}, text="<li>nothing usable</li>"))
    resources = [SubscribedResource("a", "/rw/iosystem/signals/A;state", "1")]

    with pytest.raises(ValueError, match="Could not extract WebSocket URL"):
        await sub.create_subscription(client, resources)


# ---------------------------------------------------------------------------
# delete_subscription
# ---------------------------------------------------------------------------


async def test_delete_subscription_calls_rws_delete_endpoint() -> None:
    """Nominal case: call ``DELETE /subscription/{group-id}`` directly."""
    client = _FakeRWSClient()
    handle = SubscriptionHandle(
        group_id="7",
        ws_url="ws://192.168.125.1:80/poll/7",
        cookie_header="cookie",
        resources=(),
        initial_values={},
    )

    await sub.delete_subscription(client, handle)

    assert client.delete_calls == [("/subscription/7", {})]


# ---------------------------------------------------------------------------
# watch_resources
# ---------------------------------------------------------------------------


async def test_watch_resources_yields_initial_then_ws_events(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Nominal case: yield initial values, then WebSocket events."""
    handle = SubscriptionHandle(
        group_id="7",
        ws_url="ws://192.168.125.1:80/poll/7",
        cookie_header="-http-session-=abc; ABBCX=xyz",
        resources=(SubscribedResource("a", "/rw/iosystem/signals/A;state", "1"),),
        initial_values={"a": "0"},
    )

    async def fake_create_subscription(
        client: RWSClient,
        resources: Sequence[SubscribedResource],
    ) -> SubscriptionHandle:
        return handle

    delete_calls: list[SubscriptionHandle] = []

    async def fake_delete_subscription(client: RWSClient, h: SubscriptionHandle) -> None:
        delete_calls.append(h)

    ws_message = (
        '<li class="ios-signalstate-ev">'
        '<a href="/rw/iosystem/signals/A;state" rel="self"/>'
        '<span class="lvalue">1</span>'
        "</li>"
    )
    connect_calls: list[dict[str, object]] = []

    def fake_connect(url: str, **kwargs: object) -> _FakeWebSocketConnection:
        connect_calls.append({"url": url, **kwargs})
        return _FakeWebSocketConnection([ws_message])

    monkeypatch.setattr(sub, "create_subscription", fake_create_subscription)
    monkeypatch.setattr(sub, "delete_subscription", fake_delete_subscription)
    monkeypatch.setattr(sub.websockets.asyncio.client, "connect", fake_connect)

    client = _FakeRWSClient()
    resources = [SubscribedResource("a", "/rw/iosystem/signals/A;state", "1")]

    events = [event async for event in sub.watch_resources(client, resources)]

    assert events == [("a", "0"), ("a", "1")]
    assert delete_calls == []
    assert connect_calls[0]["url"] == "ws://192.168.125.1:80/poll/7"
    assert connect_calls[0]["additional_headers"] == {"Cookie": "-http-session-=abc; ABBCX=xyz"}
    assert connect_calls[0]["subprotocols"] == sub._RWS_SUBPROTOCOLS
    assert connect_calls[0]["compression"] is None
    assert connect_calls[0]["ping_interval"] is None


async def test_watch_resources_skips_initial_values_when_disabled(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Edge case: ``yield_initial_values=False`` skips initial values."""
    handle = SubscriptionHandle(
        group_id="7",
        ws_url="ws://192.168.125.1:80/poll/7",
        cookie_header="cookie",
        resources=(SubscribedResource("a", "/rw/iosystem/signals/A;state", "1"),),
        initial_values={"a": "0"},
    )

    async def fake_create_subscription(
        client: RWSClient,
        resources: Sequence[SubscribedResource],
    ) -> SubscriptionHandle:
        return handle

    delete_calls: list[SubscriptionHandle] = []

    async def fake_delete_subscription(client: RWSClient, h: SubscriptionHandle) -> None:
        delete_calls.append(h)

    monkeypatch.setattr(sub, "create_subscription", fake_create_subscription)
    monkeypatch.setattr(sub, "delete_subscription", fake_delete_subscription)
    monkeypatch.setattr(sub.websockets.asyncio.client, "connect", _fake_connect)

    client = _FakeRWSClient()
    resources = [SubscribedResource("a", "/rw/iosystem/signals/A;state", "1")]

    events = [
        event async for event in sub.watch_resources(client, resources, yield_initial_values=False)
    ]

    assert events == []
    assert delete_calls == []


async def test_watch_resources_deletes_subscription_if_websocket_never_opens(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Error case: fallback DELETE is used if the WebSocket never opens."""
    handle = SubscriptionHandle(
        group_id="7",
        ws_url="ws://192.168.125.1:80/poll/7",
        cookie_header="cookie",
        resources=(SubscribedResource("a", "/rw/iosystem/signals/A;state", "1"),),
        initial_values={},
    )

    async def fake_create_subscription(
        client: RWSClient,
        resources: Sequence[SubscribedResource],
    ) -> SubscriptionHandle:
        return handle

    delete_calls: list[SubscriptionHandle] = []

    async def fake_delete_subscription(client: RWSClient, h: SubscriptionHandle) -> None:
        delete_calls.append(h)

    monkeypatch.setattr(sub, "create_subscription", fake_create_subscription)
    monkeypatch.setattr(sub, "delete_subscription", fake_delete_subscription)
    monkeypatch.setattr(sub.websockets.asyncio.client, "connect", _failing_connect)

    client = _FakeRWSClient()
    resources = [SubscribedResource("a", "/rw/iosystem/signals/A;state", "1")]

    with pytest.raises(OSError, match="websocket setup failed"):
        async with contextlib.aclosing(sub.watch_resources(client, resources)) as events:
            async for _event in events:
                raise AssertionError("No event should be yielded")

    assert delete_calls == [handle]


async def test_watch_resources_does_not_delete_after_websocket_opened_on_consumer_exception(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Error case: once WebSocket opened, cleanup is delegated to WebSocket close."""
    handle = SubscriptionHandle(
        group_id="7",
        ws_url="ws://192.168.125.1:80/poll/7",
        cookie_header="cookie",
        resources=(SubscribedResource("a", "/rw/iosystem/signals/A;state", "1"),),
        initial_values={},
    )

    async def fake_create_subscription(
        client: RWSClient,
        resources: Sequence[SubscribedResource],
    ) -> SubscriptionHandle:
        return handle

    delete_calls: list[SubscriptionHandle] = []

    async def fake_delete_subscription(client: RWSClient, h: SubscriptionHandle) -> None:
        delete_calls.append(h)

    ws_message = (
        '<li class="ios-signalstate-ev">'
        '<a href="/rw/iosystem/signals/A;state" rel="self"/>'
        '<span class="lvalue">1</span>'
        "</li>"
    )

    def fake_connect(url: str, **kwargs: object) -> _FakeWebSocketConnection:
        return _FakeWebSocketConnection([ws_message])

    monkeypatch.setattr(sub, "create_subscription", fake_create_subscription)
    monkeypatch.setattr(sub, "delete_subscription", fake_delete_subscription)
    monkeypatch.setattr(sub.websockets.asyncio.client, "connect", fake_connect)

    client = _FakeRWSClient()
    resources = [SubscribedResource("a", "/rw/iosystem/signals/A;state", "1")]

    with pytest.raises(RuntimeError, match="boom"):
        async with contextlib.aclosing(
            sub.watch_resources(client, resources, yield_initial_values=False)
        ) as events:
            async for _name, _value in events:
                raise RuntimeError("boom")

    assert delete_calls == []


async def test_watch_resources_teardown_failure_does_not_mask_original_error(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Error case: failed fallback DELETE does not mask the original error."""
    handle = SubscriptionHandle(
        group_id="7",
        ws_url="ws://192.168.125.1:80/poll/7",
        cookie_header="cookie",
        resources=(SubscribedResource("a", "/rw/iosystem/signals/A;state", "1"),),
        initial_values={},
    )

    async def fake_create_subscription(
        client: RWSClient,
        resources: Sequence[SubscribedResource],
    ) -> SubscriptionHandle:
        return handle

    async def failing_delete_subscription(client: RWSClient, h: SubscriptionHandle) -> None:
        raise RuntimeError("controller unreachable during teardown")

    monkeypatch.setattr(sub, "create_subscription", fake_create_subscription)
    monkeypatch.setattr(sub, "delete_subscription", failing_delete_subscription)
    monkeypatch.setattr(sub.websockets.asyncio.client, "connect", _failing_connect)

    client = _FakeRWSClient()
    resources = [SubscribedResource("a", "/rw/iosystem/signals/A;state", "1")]

    with pytest.raises(OSError, match="websocket setup failed"):
        async with contextlib.aclosing(sub.watch_resources(client, resources)) as events:
            async for _event in events:
                raise AssertionError("No event should be yielded")
