# This file is AUTO-GENERATED by contrib/generator/main.py
# DO NOT EDIT MANUALLY — run the generator to regenerate.
"""Tests unitaires auto-générés pour rws/rapid/tasks."""
from __future__ import annotations

import pytest
import httpx

from abb_rws_client._core.client import RWSClient
from abb_rws_client.rws.rapid.tasks import (
    get_rapid_tasks,
    get_rapid_tasks_actions,
    start_rapid_spy_logging,
    get_rapid_spy_logging_status,
    stop_rapid_spy_logging,
    post_activate_deactivate_rapid_tasks,
    get_program_motion_pointer_sync_state_for,
    subscribe_on_build_log_change,
    get_rapid_task_state,
    get_rapid_task_actions,
    load_rapid_module_into_rapid_task,
    post_unload_module_from_rapid_task,
    post_abort_current_execution_level,
    post_activate_deactivate_rapid_task,
    get_activation_record,
    get_structural_change_count,
    get_preferable_data_types,
    get_program_pointer_sync_state,
    get_motion_pointer_sync_state,
    post_link_rapid_task,
    get_pallet,
    get_pallet_head,
    subscribe_on_rapid_task_change,
    subscribe_on_rapid_pp_sync_state_change,
    subscribe_on_rapid_task_pgmexecution_state_change,
    get_rapid_motion,
    get_robtarget,
    get_joint_target,
    get_mechanical_units,
    get_external_joint_states,
    post_calibration_for_displacement,
    post_calibration_for_tcp,
    get_rapid_program_resource,
    get_rapid_program_actions,
    load_program_into_rapid_task,
    post_unload_program_from_rapid_task,
    save_program,
    set_program_name,
    set_entry_point,
    get_build_errors,
    get_rapid_breakpoint_actions,
    set_break_point,
    get_break_points,
    get_rapid_task_motion_program_pointer_positions,
    get_rapid_task_pcp_actions,
    set_the_program_pointer_pp_position_to,
    set_the_program_pointer_pp_position_to,
    set_the_program_pointer_pp_position_to,
    set_the_program_pointer_pp_position_to,
    set_the_program_pointer_pp_position_to,
    subscribe_on_program_pointer,
    subscribe_on_motion_pointer,
    get_rapid_service_routine,
    get_rapid_program_counter_position,
)


class _MockTransport(httpx.AsyncBaseTransport):
    """Transport mock retournant une réponse HTTP configurable."""

    def __init__(self, status_code: int = 200, content: bytes = b"") -> None:
        self.status_code = status_code
        self.content = content
        self.last_request: httpx.Request | None = None

    async def handle_async_request(self, request: httpx.Request) -> httpx.Response:
        self.last_request = request
        return httpx.Response(self.status_code, content=self.content, request=request)


def _make_client(transport: _MockTransport) -> RWSClient:
    """Construit un RWSClient branché sur le transport mock."""
    client = RWSClient.__new__(RWSClient)
    client._http = httpx.AsyncClient(
        transport=transport,
        base_url="http://localhost/",
    )
    client.host = "localhost"
    return client


@pytest.mark.asyncio
async def test_get_rapid_tasks() -> None:
    """Vérifie que get_rapid_tasks émet GET /rw/rapid/tasks."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_rapid_tasks(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/rapid/tasks"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_rapid_tasks_actions() -> None:
    """Vérifie que get_rapid_tasks_actions émet GET /rw/rapid/tasks."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_rapid_tasks_actions(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/rapid/tasks"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_start_rapid_spy_logging() -> None:
    """Vérifie que start_rapid_spy_logging émet POST /rw/rapid/tasks."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await start_rapid_spy_logging(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/rapid/tasks"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_get_rapid_spy_logging_status() -> None:
    """Vérifie que get_rapid_spy_logging_status émet GET /rw/rapid/tasks."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_rapid_spy_logging_status(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/rapid/tasks"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_stop_rapid_spy_logging() -> None:
    """Vérifie que stop_rapid_spy_logging émet POST /rw/rapid/tasks."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await stop_rapid_spy_logging(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/rapid/tasks"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_post_activate_deactivate_rapid_tasks() -> None:
    """Vérifie que post_activate_deactivate_rapid_tasks émet POST /rw/rapid/tasks."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await post_activate_deactivate_rapid_tasks(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/rapid/tasks"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_get_program_motion_pointer_sync_state_for() -> None:
    """Vérifie que get_program_motion_pointer_sync_state_for émet GET /rw/rapid/tasks."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_program_motion_pointer_sync_state_for(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/rapid/tasks"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_subscribe_on_build_log_change() -> None:
    """Vérifie que subscribe_on_build_log_change émet POST /subscription."""
    transport = _MockTransport(status_code=201)
    client = _make_client(transport)

    resp = await subscribe_on_build_log_change(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/subscription"
    assert resp.status_code == 201

@pytest.mark.asyncio
async def test_get_rapid_task_state() -> None:
    """Vérifie que get_rapid_task_state émet GET /rw/rapid/tasks/{task}."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_rapid_task_state(client, "task_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/rapid/tasks/task_test"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_rapid_task_actions() -> None:
    """Vérifie que get_rapid_task_actions émet GET /rw/rapid/tasks/{task}."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_rapid_task_actions(client, "task_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/rapid/tasks/task_test"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_load_rapid_module_into_rapid_task() -> None:
    """Vérifie que load_rapid_module_into_rapid_task émet POST /rw/rapid/tasks/{task}."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await load_rapid_module_into_rapid_task(client, "task_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/rapid/tasks/task_test"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_post_unload_module_from_rapid_task() -> None:
    """Vérifie que post_unload_module_from_rapid_task émet POST /rw/rapid/tasks/{task}."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await post_unload_module_from_rapid_task(client, "task_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/rapid/tasks/task_test"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_post_abort_current_execution_level() -> None:
    """Vérifie que post_abort_current_execution_level émet POST /rw/rapid/tasks/{task}."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await post_abort_current_execution_level(client, "task_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/rapid/tasks/task_test"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_post_activate_deactivate_rapid_task() -> None:
    """Vérifie que post_activate_deactivate_rapid_task émet POST /rw/rapid/tasks/{task}."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await post_activate_deactivate_rapid_task(client, "task_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/rapid/tasks/task_test"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_get_activation_record() -> None:
    """Vérifie que get_activation_record émet GET /rw/rapid/tasks/{task_name}."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_activation_record(client, "task_name_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/rapid/tasks/task_name_test"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_structural_change_count() -> None:
    """Vérifie que get_structural_change_count émet GET /rw/rapid/tasks/{task_name}."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_structural_change_count(client, "task_name_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/rapid/tasks/task_name_test"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_preferable_data_types() -> None:
    """Vérifie que get_preferable_data_types émet GET /rw/rapid/tasks/{task_name}."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_preferable_data_types(client, "task_name_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/rapid/tasks/task_name_test"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_program_pointer_sync_state() -> None:
    """Vérifie que get_program_pointer_sync_state émet GET /rw/rapid/tasks/{task_name}."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_program_pointer_sync_state(client, "task_name_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/rapid/tasks/task_name_test"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_motion_pointer_sync_state() -> None:
    """Vérifie que get_motion_pointer_sync_state émet GET /rw/rapid/tasks/{task_name}."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_motion_pointer_sync_state(client, "task_name_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/rapid/tasks/task_name_test"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_post_link_rapid_task() -> None:
    """Vérifie que post_link_rapid_task émet POST /rw/rapid/tasks/{task}."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await post_link_rapid_task(client, "task_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/rapid/tasks/task_test"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_get_pallet() -> None:
    """Vérifie que get_pallet émet GET /rw/rapid/tasks/{task_name}."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_pallet(client, "task_name_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/rapid/tasks/task_name_test"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_pallet_head() -> None:
    """Vérifie que get_pallet_head émet GET /rw/rapid/tasks/{task_name}."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_pallet_head(client, "task_name_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/rapid/tasks/task_name_test"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_subscribe_on_rapid_task_change() -> None:
    """Vérifie que subscribe_on_rapid_task_change émet POST /subscription."""
    transport = _MockTransport(status_code=201)
    client = _make_client(transport)

    resp = await subscribe_on_rapid_task_change(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/subscription"
    assert resp.status_code == 201

@pytest.mark.asyncio
async def test_subscribe_on_rapid_pp_sync_state_change() -> None:
    """Vérifie que subscribe_on_rapid_pp_sync_state_change émet POST /subscription."""
    transport = _MockTransport(status_code=201)
    client = _make_client(transport)

    resp = await subscribe_on_rapid_pp_sync_state_change(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/subscription"
    assert resp.status_code == 201

@pytest.mark.asyncio
async def test_subscribe_on_rapid_task_pgmexecution_state_change() -> None:
    """Vérifie que subscribe_on_rapid_task_pgmexecution_state_change émet POST /subscription."""
    transport = _MockTransport(status_code=201)
    client = _make_client(transport)

    resp = await subscribe_on_rapid_task_pgmexecution_state_change(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/subscription"
    assert resp.status_code == 201

@pytest.mark.asyncio
async def test_get_rapid_motion() -> None:
    """Vérifie que get_rapid_motion émet GET /rw/rapid/tasks/{task}/motion."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_rapid_motion(client, "task_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/rapid/tasks/task_test/motion"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_robtarget() -> None:
    """Vérifie que get_robtarget émet GET /rw/rapid/tasks/{task}/motion."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_robtarget(client, "task_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/rapid/tasks/task_test/motion"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_joint_target() -> None:
    """Vérifie que get_joint_target émet GET /rw/rapid/tasks/{task}/motion."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_joint_target(client, "task_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/rapid/tasks/task_test/motion"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_mechanical_units() -> None:
    """Vérifie que get_mechanical_units émet GET /rw/rapid/tasks/{task}/motion."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_mechanical_units(client, "task_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/rapid/tasks/task_test/motion"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_external_joint_states() -> None:
    """Vérifie que get_external_joint_states émet GET /rw/rapid/tasks/{task}/motion."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_external_joint_states(client, "task_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/rapid/tasks/task_test/motion"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_post_calibration_for_displacement() -> None:
    """Vérifie que post_calibration_for_displacement émet POST /rw/rapid/tasks/{task}/motion/calib."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await post_calibration_for_displacement(client, "task_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/rapid/tasks/task_test/motion/calib"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_post_calibration_for_tcp() -> None:
    """Vérifie que post_calibration_for_tcp émet POST /rw/rapid/tasks/{task}/motion/calib."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await post_calibration_for_tcp(client, "task_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/rapid/tasks/task_test/motion/calib"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_rapid_program_resource() -> None:
    """Vérifie que get_rapid_program_resource émet GET /rw/rapid/tasks/{task}/program."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_rapid_program_resource(client, "task_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/rapid/tasks/task_test/program"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_rapid_program_actions() -> None:
    """Vérifie que get_rapid_program_actions émet GET /rw/rapid/tasks/{task}/program."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_rapid_program_actions(client, "task_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/rapid/tasks/task_test/program"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_load_program_into_rapid_task() -> None:
    """Vérifie que load_program_into_rapid_task émet POST /rw/rapid/tasks/{task}/program."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await load_program_into_rapid_task(client, "task_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/rapid/tasks/task_test/program"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_post_unload_program_from_rapid_task() -> None:
    """Vérifie que post_unload_program_from_rapid_task émet POST /rw/rapid/tasks/{task}/program."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await post_unload_program_from_rapid_task(client, "task_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/rapid/tasks/task_test/program"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_save_program() -> None:
    """Vérifie que save_program émet POST /rw/rapid/tasks/{task}/program."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await save_program(client, "task_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/rapid/tasks/task_test/program"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_set_program_name() -> None:
    """Vérifie que set_program_name émet POST /rw/rapid/tasks/{task}/program."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await set_program_name(client, "task_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/rapid/tasks/task_test/program"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_set_entry_point() -> None:
    """Vérifie que set_entry_point émet POST /rw/rapid/tasks/{task}/program."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await set_entry_point(client, "task_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/rapid/tasks/task_test/program"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_get_build_errors() -> None:
    """Vérifie que get_build_errors émet GET /rw/rapid/tasks/{task}/program/builderror."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_build_errors(client, "task_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/rapid/tasks/task_test/program/builderror"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_rapid_breakpoint_actions() -> None:
    """Vérifie que get_rapid_breakpoint_actions émet GET /rw/rapid/tasks/{task}/program/breakpoint."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_rapid_breakpoint_actions(client, "task_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/rapid/tasks/task_test/program/breakpoint"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_set_break_point() -> None:
    """Vérifie que set_break_point émet POST /rw/rapid/tasks/{task}/program/breakpoint."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await set_break_point(client, "task_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/rapid/tasks/task_test/program/breakpoint"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_get_break_points() -> None:
    """Vérifie que get_break_points émet GET /rw/rapid/tasks/{task}/program/breakpoint."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_break_points(client, "task_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/rapid/tasks/task_test/program/breakpoint"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_rapid_task_motion_program_pointer_positions() -> None:
    """Vérifie que get_rapid_task_motion_program_pointer_positions émet GET /rw/rapid/tasks/{task}/pcp."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_rapid_task_motion_program_pointer_positions(client, "task_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/rapid/tasks/task_test/pcp"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_rapid_task_pcp_actions() -> None:
    """Vérifie que get_rapid_task_pcp_actions émet GET /rw/rapid/tasks/{task}/pcp."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_rapid_task_pcp_actions(client, "task_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/rapid/tasks/task_test/pcp"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_set_the_program_pointer_pp_position_to() -> None:
    """Vérifie que set_the_program_pointer_pp_position_to émet POST /rw/rapid/tasks/{task}/pcp."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await set_the_program_pointer_pp_position_to(client, "task_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/rapid/tasks/task_test/pcp"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_set_the_program_pointer_pp_position_to() -> None:
    """Vérifie que set_the_program_pointer_pp_position_to émet POST /rw/rapid/tasks/{task}/pcp."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await set_the_program_pointer_pp_position_to(client, "task_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/rapid/tasks/task_test/pcp"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_set_the_program_pointer_pp_position_to() -> None:
    """Vérifie que set_the_program_pointer_pp_position_to émet POST /rw/rapid/tasks/{task}/pcp."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await set_the_program_pointer_pp_position_to(client, "task_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/rapid/tasks/task_test/pcp"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_set_the_program_pointer_pp_position_to() -> None:
    """Vérifie que set_the_program_pointer_pp_position_to émet POST /rw/rapid/tasks/{task}/pcp."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await set_the_program_pointer_pp_position_to(client, "task_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/rapid/tasks/task_test/pcp"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_set_the_program_pointer_pp_position_to() -> None:
    """Vérifie que set_the_program_pointer_pp_position_to émet POST /rw/rapid/tasks/{task}/pcp."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await set_the_program_pointer_pp_position_to(client, "task_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/rapid/tasks/task_test/pcp"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_subscribe_on_program_pointer() -> None:
    """Vérifie que subscribe_on_program_pointer émet POST /subscription."""
    transport = _MockTransport(status_code=201)
    client = _make_client(transport)

    resp = await subscribe_on_program_pointer(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/subscription"
    assert resp.status_code == 201

@pytest.mark.asyncio
async def test_subscribe_on_motion_pointer() -> None:
    """Vérifie que subscribe_on_motion_pointer émet POST /subscription."""
    transport = _MockTransport(status_code=201)
    client = _make_client(transport)

    resp = await subscribe_on_motion_pointer(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/subscription"
    assert resp.status_code == 201

@pytest.mark.asyncio
async def test_get_rapid_service_routine() -> None:
    """Vérifie que get_rapid_service_routine émet GET /rw/rapid/tasks/{task}/serviceroutine."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_rapid_service_routine(client, "task_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/rapid/tasks/task_test/serviceroutine"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_rapid_program_counter_position() -> None:
    """Vérifie que get_rapid_program_counter_position émet GET /rw/rapid/tasks/{task}/execution."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_rapid_program_counter_position(client, "task_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/rapid/tasks/task_test/execution"
    assert resp.status_code == 200
