# This file is AUTO-GENERATED by contrib/generator/main.py
# DO NOT EDIT MANUALLY — run the generator to regenerate.
"""Tests unitaires auto-générés pour rws/rapid/symbols."""
from __future__ import annotations

import pytest
import httpx

from abb_rws_client._core.client import RWSClient
from abb_rws_client.rws.rapid.symbols import (
    get_rapid_symbols_resources,
    get_rapid_symbols_actions,
    post_search_rapid_symbols,
    get_object_extension_list,
)


class _MockTransport(httpx.AsyncBaseTransport):
    """Transport mock retournant une réponse HTTP configurable."""

    def __init__(self, status_code: int = 200, content: bytes = b"") -> None:
        self.status_code = status_code
        self.content = content
        self.last_request: httpx.Request | None = None

    async def handle_async_request(self, request: httpx.Request) -> httpx.Response:
        self.last_request = request
        return httpx.Response(self.status_code, content=self.content, request=request)


def _make_client(transport: _MockTransport) -> RWSClient:
    """Construit un RWSClient branché sur le transport mock."""
    client = RWSClient.__new__(RWSClient)
    client._http = httpx.AsyncClient(
        transport=transport,
        base_url="http://localhost/",
    )
    client.host = "localhost"
    return client


@pytest.mark.asyncio
async def test_get_rapid_symbols_resources() -> None:
    """Vérifie que get_rapid_symbols_resources émet GET /rw/rapid/symbols."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_rapid_symbols_resources(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/rapid/symbols"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_rapid_symbols_actions() -> None:
    """Vérifie que get_rapid_symbols_actions émet GET /rw/rapid/symbols."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_rapid_symbols_actions(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/rapid/symbols"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_post_search_rapid_symbols() -> None:
    """Vérifie que post_search_rapid_symbols émet POST /rw/rapid/symbols."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await post_search_rapid_symbols(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/rapid/symbols"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_object_extension_list() -> None:
    """Vérifie que get_object_extension_list émet GET /rw/rapid/symbols/{symbol URL}."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_object_extension_list(client, "symbol_url_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/rapid/symbols/symbol_url_test"
    assert resp.status_code == 200
