# This file is AUTO-GENERATED by contrib/generator/main.py
# DO NOT EDIT MANUALLY — run the generator to regenerate.
"""Tests unitaires auto-générés pour rws/rapid/uiinstr."""
from __future__ import annotations

import pytest
import httpx

from abb_rws_client._core.client import RWSClient
from abb_rws_client.rws.rapid.uiinstr import (
    get_ui_instruction_resource,
    get_ui_instruction_actions,
    subscribe_on_ui_instruction,
    get_active_ui_instruction,
    get_active_ui_instruction_actions,
    update_an_active_ui_instruction_parameter,
    get_parameter_value_for_an_active_ui,
    get_active_ui_instruction_parameters,
)


class _MockTransport(httpx.AsyncBaseTransport):
    """Transport mock retournant une réponse HTTP configurable."""

    def __init__(self, status_code: int = 200, content: bytes = b"") -> None:
        self.status_code = status_code
        self.content = content
        self.last_request: httpx.Request | None = None

    async def handle_async_request(self, request: httpx.Request) -> httpx.Response:
        self.last_request = request
        return httpx.Response(self.status_code, content=self.content, request=request)


def _make_client(transport: _MockTransport) -> RWSClient:
    """Construit un RWSClient branché sur le transport mock."""
    client = RWSClient.__new__(RWSClient)
    client._http = httpx.AsyncClient(
        transport=transport,
        base_url="http://localhost/",
    )
    client.host = "localhost"
    return client


@pytest.mark.asyncio
async def test_get_ui_instruction_resource() -> None:
    """Vérifie que get_ui_instruction_resource émet GET /rw/rapid/uiinstr."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_ui_instruction_resource(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/rapid/uiinstr"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_ui_instruction_actions() -> None:
    """Vérifie que get_ui_instruction_actions émet GET /rw/rapid/uiinstr."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_ui_instruction_actions(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/rapid/uiinstr"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_subscribe_on_ui_instruction() -> None:
    """Vérifie que subscribe_on_ui_instruction émet POST /subscription."""
    transport = _MockTransport(status_code=201)
    client = _make_client(transport)

    resp = await subscribe_on_ui_instruction(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/subscription"
    assert resp.status_code == 201

@pytest.mark.asyncio
async def test_get_active_ui_instruction() -> None:
    """Vérifie que get_active_ui_instruction émet GET /rw/rapid/uiinstr/active."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_active_ui_instruction(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/rapid/uiinstr/active"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_active_ui_instruction_actions() -> None:
    """Vérifie que get_active_ui_instruction_actions émet GET /rw/rapid/uiinstr/active."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_active_ui_instruction_actions(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/rapid/uiinstr/active"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_update_an_active_ui_instruction_parameter() -> None:
    """Vérifie que update_an_active_ui_instruction_parameter émet POST /rw/rapid/uiinstr/active/param/{stackurl}/{uiparam}."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await update_an_active_ui_instruction_parameter(client, "stackurl_test", "uiparam_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/rapid/uiinstr/active/param/stackurl_test/uiparam_test"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_get_parameter_value_for_an_active_ui() -> None:
    """Vérifie que get_parameter_value_for_an_active_ui émet GET /rw/rapid/uiinstr/active/param/{stackurl}/{uiparam}."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_parameter_value_for_an_active_ui(client, "stackurl_test", "uiparam_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/rapid/uiinstr/active/param/stackurl_test/uiparam_test"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_active_ui_instruction_parameters() -> None:
    """Vérifie que get_active_ui_instruction_parameters émet GET /rw/rapid/uiinstr/active/params/{stackurl}."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_active_ui_instruction_parameters(client, "stackurl_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/rapid/uiinstr/active/params/stackurl_test"
    assert resp.status_code == 200
