# This file is AUTO-GENERATED by contrib/generator/main.py
# DO NOT EDIT MANUALLY — run the generator to regenerate.
"""Tests unitaires auto-générés pour rws/vision."""
from __future__ import annotations

import pytest
import httpx

from abb_rws_client._core.client import RWSClient
from abb_rws_client.rws.vision import (
    get_vision_manager_resource,
    get_number_of_cameras_of_iv,
    get_iv_camera_validity,
    get_vision_camera_resource_actions,
    get_camera_jobname,
    restart_camera,
    post_flash_led_of_camera,
    set_camera_state,
    post_refesh_the_camera,
    set_hostname_of_the_camera,
    set_camera_to_be_dhcp_client,
    set_camera_dns_settings,
    get_camera_status,
    get_camera_info_using_index_of_the,
    set_camera_name,
    set_camera_user_credentials,
    set_camera_ip_settings,
    get_iv_camera_info,
)


class _MockTransport(httpx.AsyncBaseTransport):
    """Transport mock retournant une réponse HTTP configurable."""

    def __init__(self, status_code: int = 200, content: bytes = b"") -> None:
        self.status_code = status_code
        self.content = content
        self.last_request: httpx.Request | None = None

    async def handle_async_request(self, request: httpx.Request) -> httpx.Response:
        self.last_request = request
        return httpx.Response(self.status_code, content=self.content, request=request)


def _make_client(transport: _MockTransport) -> RWSClient:
    """Construit un RWSClient branché sur le transport mock."""
    client = RWSClient.__new__(RWSClient)
    client._http = httpx.AsyncClient(
        transport=transport,
        base_url="http://localhost/",
    )
    client.host = "localhost"
    return client


@pytest.mark.asyncio
async def test_get_vision_manager_resource() -> None:
    """Vérifie que get_vision_manager_resource émet GET /rw/vision."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_vision_manager_resource(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/vision"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_number_of_cameras_of_iv() -> None:
    """Vérifie que get_number_of_cameras_of_iv émet GET /rw/vision."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_number_of_cameras_of_iv(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/vision"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_iv_camera_validity() -> None:
    """Vérifie que get_iv_camera_validity émet GET /rw/vision."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_iv_camera_validity(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/vision"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_vision_camera_resource_actions() -> None:
    """Vérifie que get_vision_camera_resource_actions émet GET /rw/vision."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_vision_camera_resource_actions(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/vision"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_camera_jobname() -> None:
    """Vérifie que get_camera_jobname émet GET /rw/vision."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_camera_jobname(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/vision"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_restart_camera() -> None:
    """Vérifie que restart_camera émet POST /rw/vision."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await restart_camera(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/vision"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_post_flash_led_of_camera() -> None:
    """Vérifie que post_flash_led_of_camera émet POST /rw/vision."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await post_flash_led_of_camera(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/vision"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_set_camera_state() -> None:
    """Vérifie que set_camera_state émet POST /rw/vision."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await set_camera_state(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/vision"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_post_refesh_the_camera() -> None:
    """Vérifie que post_refesh_the_camera émet POST /rw/vision."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await post_refesh_the_camera(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/vision"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_set_hostname_of_the_camera() -> None:
    """Vérifie que set_hostname_of_the_camera émet POST /rw/vision."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await set_hostname_of_the_camera(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/vision"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_set_camera_to_be_dhcp_client() -> None:
    """Vérifie que set_camera_to_be_dhcp_client émet POST /rw/vision."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await set_camera_to_be_dhcp_client(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/vision"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_set_camera_dns_settings() -> None:
    """Vérifie que set_camera_dns_settings émet POST /rw/vision."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await set_camera_dns_settings(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/vision"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_get_camera_status() -> None:
    """Vérifie que get_camera_status émet GET /rw/vision."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_camera_status(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/vision"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_camera_info_using_index_of_the() -> None:
    """Vérifie que get_camera_info_using_index_of_the émet GET /rw/vision."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_camera_info_using_index_of_the(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/vision"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_set_camera_name() -> None:
    """Vérifie que set_camera_name émet POST /rw/vision."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await set_camera_name(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/vision"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_set_camera_user_credentials() -> None:
    """Vérifie que set_camera_user_credentials émet POST /rw/vision."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await set_camera_user_credentials(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/vision"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_set_camera_ip_settings() -> None:
    """Vérifie que set_camera_ip_settings émet POST /rw/vision."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await set_camera_ip_settings(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/vision"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_get_iv_camera_info() -> None:
    """Vérifie que get_iv_camera_info émet GET /rw/vision."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_iv_camera_info(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/vision"
    assert resp.status_code == 200
