# This file is AUTO-GENERATED by contrib/generator/main.py
# DO NOT EDIT MANUALLY — run the generator to regenerate.
"""Tests unitaires auto-générés pour rws/subscription."""
from __future__ import annotations

import pytest
import httpx

from abb_rws_client._core.client import RWSClient
from abb_rws_client.rws.subscription import (
    get_subscription_actions,
    subscribe_on_resources,
    get_subscription_group_actions,
    add_new_resources_remove_existing_resources_or,
    unsubscribe_or_remove_the_subscription_group_resources,
    unsubscribe_or_remove_the_resource_from_subscription,
)


class _MockTransport(httpx.AsyncBaseTransport):
    """Transport mock retournant une réponse HTTP configurable."""

    def __init__(self, status_code: int = 200, content: bytes = b"") -> None:
        self.status_code = status_code
        self.content = content
        self.last_request: httpx.Request | None = None

    async def handle_async_request(self, request: httpx.Request) -> httpx.Response:
        self.last_request = request
        return httpx.Response(self.status_code, content=self.content, request=request)


def _make_client(transport: _MockTransport) -> RWSClient:
    """Construit un RWSClient branché sur le transport mock."""
    client = RWSClient.__new__(RWSClient)
    client._http = httpx.AsyncClient(
        transport=transport,
        base_url="http://localhost/",
    )
    client.host = "localhost"
    return client


@pytest.mark.asyncio
async def test_get_subscription_actions() -> None:
    """Vérifie que get_subscription_actions émet GET /subscription."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_subscription_actions(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/subscription"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_subscribe_on_resources() -> None:
    """Vérifie que subscribe_on_resources émet POST /subscription."""
    transport = _MockTransport(status_code=201)
    client = _make_client(transport)

    resp = await subscribe_on_resources(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/subscription"
    assert resp.status_code == 201

@pytest.mark.asyncio
async def test_get_subscription_group_actions() -> None:
    """Vérifie que get_subscription_group_actions émet GET /subscription/{group-id}."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_subscription_group_actions(client, "group_id_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/subscription/group_id_test"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_add_new_resources_remove_existing_resources_or() -> None:
    """Vérifie que add_new_resources_remove_existing_resources_or émet PUT /subscripion/{group-id}."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await add_new_resources_remove_existing_resources_or(client, "group_id_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "PUT"
    assert transport.last_request.url.path == "/subscripion/group_id_test"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_unsubscribe_or_remove_the_subscription_group_resources() -> None:
    """Vérifie que unsubscribe_or_remove_the_subscription_group_resources émet DELETE /subscripion/{group-id}."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await unsubscribe_or_remove_the_subscription_group_resources(client, "group_id_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "DELETE"
    assert transport.last_request.url.path == "/subscripion/group_id_test"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_unsubscribe_or_remove_the_resource_from_subscription() -> None:
    """Vérifie que unsubscribe_or_remove_the_resource_from_subscription émet DELETE /subscripion/{group-d}/{resource-uri}."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await unsubscribe_or_remove_the_resource_from_subscription(client, "group_d_test", "resource_uri_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "DELETE"
    assert transport.last_request.url.path == "/subscripion/group_d_test/resource_uri_test"
    assert resp.status_code == 200
