# This file is AUTO-GENERATED by contrib/generator/main.py
# DO NOT EDIT MANUALLY — run the generator to regenerate.
"""Tests unitaires auto-générés pour rws/cfg."""
from __future__ import annotations

import pytest
import httpx

from abb_rws_client._core.client import RWSClient
from abb_rws_client.rws.cfg import (
    get_cfg_resources,
    get_cfg_actions,
    validate_cfg_file,
    load_cfg_file,
    validate_cfg_instance_before_delete,
    validate_cfg_instances,
    post_keyless_motor_on,
    subscribe_on_cfg_changecount,
    get_cfg_domain_types,
    get_actions_on_cfg_domain,
    save_cfg_domain,
    reset_cfg_domain,
    get_cfg_type,
    get_all_attributes_of_the_given_domain,
    get_all_instances_of_the_given_domain,
    get_actions_on_cfg_instances,
    reset_cfg_instances,
    create_default_cfg_instance,
    get_cfg_instance,
    get_cfg_instance_actions,
    update_cfg_instance,
    delete_cfg_instance,
)


class _MockTransport(httpx.AsyncBaseTransport):
    """Transport mock retournant une réponse HTTP configurable."""

    def __init__(self, status_code: int = 200, content: bytes = b"") -> None:
        self.status_code = status_code
        self.content = content
        self.last_request: httpx.Request | None = None

    async def handle_async_request(self, request: httpx.Request) -> httpx.Response:
        self.last_request = request
        return httpx.Response(self.status_code, content=self.content, request=request)


def _make_client(transport: _MockTransport) -> RWSClient:
    """Construit un RWSClient branché sur le transport mock."""
    client = RWSClient.__new__(RWSClient)
    client._http = httpx.AsyncClient(
        transport=transport,
        base_url="http://localhost/",
    )
    client.host = "localhost"
    return client


@pytest.mark.asyncio
async def test_get_cfg_resources() -> None:
    """Vérifie que get_cfg_resources émet GET /rw/cfg."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_cfg_resources(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/cfg"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_cfg_actions() -> None:
    """Vérifie que get_cfg_actions émet GET /rw/cfg."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_cfg_actions(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/cfg"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_validate_cfg_file() -> None:
    """Vérifie que validate_cfg_file émet POST /rw/cfg."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await validate_cfg_file(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/cfg"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_load_cfg_file() -> None:
    """Vérifie que load_cfg_file émet POST /rw/cfg."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await load_cfg_file(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/cfg"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_validate_cfg_instance_before_delete() -> None:
    """Vérifie que validate_cfg_instance_before_delete émet POST /rw/cfg."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await validate_cfg_instance_before_delete(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/cfg"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_validate_cfg_instances() -> None:
    """Vérifie que validate_cfg_instances émet POST /rw/cfg."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await validate_cfg_instances(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/cfg"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_post_keyless_motor_on() -> None:
    """Vérifie que post_keyless_motor_on émet POST /rw/cfg."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await post_keyless_motor_on(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/cfg"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_subscribe_on_cfg_changecount() -> None:
    """Vérifie que subscribe_on_cfg_changecount émet POST /subscription."""
    transport = _MockTransport(status_code=201)
    client = _make_client(transport)

    resp = await subscribe_on_cfg_changecount(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/subscription"
    assert resp.status_code == 201

@pytest.mark.asyncio
async def test_get_cfg_domain_types() -> None:
    """Vérifie que get_cfg_domain_types émet GET /rw/cfg/{domain}."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_cfg_domain_types(client, "domain_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/cfg/domain_test"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_actions_on_cfg_domain() -> None:
    """Vérifie que get_actions_on_cfg_domain émet GET /rw/cfg/{domain}."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_actions_on_cfg_domain(client, "domain_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/cfg/domain_test"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_save_cfg_domain() -> None:
    """Vérifie que save_cfg_domain émet POST /rw/cfg/{domain}."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await save_cfg_domain(client, "domain_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/cfg/domain_test"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_reset_cfg_domain() -> None:
    """Vérifie que reset_cfg_domain émet POST /rw/cfg/{domain}."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await reset_cfg_domain(client, "domain_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/cfg/domain_test"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_cfg_type() -> None:
    """Vérifie que get_cfg_type émet GET /rw/cfg/{domain}/{type}."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_cfg_type(client, "domain_test", "type_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/cfg/domain_test/type_test"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_all_attributes_of_the_given_domain() -> None:
    """Vérifie que get_all_attributes_of_the_given_domain émet GET /rw/cfg/{domain}/{type}/attributes."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_all_attributes_of_the_given_domain(client, "domain_test", "type_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/cfg/domain_test/type_test/attributes"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_all_instances_of_the_given_domain() -> None:
    """Vérifie que get_all_instances_of_the_given_domain émet GET /rw/cfg/{domain}/{type}/instances."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_all_instances_of_the_given_domain(client, "domain_test", "type_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/cfg/domain_test/type_test/instances"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_actions_on_cfg_instances() -> None:
    """Vérifie que get_actions_on_cfg_instances émet GET /rw/cfg/{domain}/{type}/instances."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_actions_on_cfg_instances(client, "domain_test", "type_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/cfg/domain_test/type_test/instances"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_reset_cfg_instances() -> None:
    """Vérifie que reset_cfg_instances émet POST /rw/cfg/{domain}/{type}/instances."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await reset_cfg_instances(client, "domain_test", "type_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/cfg/domain_test/type_test/instances"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_create_default_cfg_instance() -> None:
    """Vérifie que create_default_cfg_instance émet POST /rw/cfg/{domain}/{type}/instances."""
    transport = _MockTransport(status_code=201)
    client = _make_client(transport)

    resp = await create_default_cfg_instance(client, "domain_test", "type_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/cfg/domain_test/type_test/instances"
    assert resp.status_code == 201

@pytest.mark.asyncio
async def test_get_cfg_instance() -> None:
    """Vérifie que get_cfg_instance émet GET /rw/cfg/{domain}/{type}/instances/{instance name}."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_cfg_instance(client, "domain_test", "type_test", "instance_name_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/cfg/domain_test/type_test/instances/instance_name_test"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_cfg_instance_actions() -> None:
    """Vérifie que get_cfg_instance_actions émet GET /rw/cfg/{domain}/{type}/instances/{instance}."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_cfg_instance_actions(client, "domain_test", "type_test", "instance_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/cfg/domain_test/type_test/instances/instance_test"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_update_cfg_instance() -> None:
    """Vérifie que update_cfg_instance émet POST /rw/cfg/{domain}/{type}/instances/{instance}."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await update_cfg_instance(client, "domain_test", "type_test", "instance_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/cfg/domain_test/type_test/instances/instance_test"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_delete_cfg_instance() -> None:
    """Vérifie que delete_cfg_instance émet DELETE /rw/cfg/{domain}/{type}/instances/{instance}."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await delete_cfg_instance(client, "domain_test", "type_test", "instance_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "DELETE"
    assert transport.last_request.url.path == "/rw/cfg/domain_test/type_test/instances/instance_test"
    assert resp.status_code == 204
