# This file is AUTO-GENERATED by contrib/generator/main.py
# DO NOT EDIT MANUALLY — run the generator to regenerate.
"""Tests unitaires auto-générés pour rws/motionsystem."""
from __future__ import annotations

import pytest
import httpx

from abb_rws_client._core.client import RWSClient
from abb_rws_client.rws.motionsystem import (
    get_motion_system,
    get_motion_system_action,
    set_mechunit_for_jogging,
    post_perform_jogging,
    set_robo_target_position,
    get_check_change_count,
    subscribe_on_error_eventchange,
    get_error_state,
    get_motion_supervision,
    get_motion_supervision_actions,
    set_motion_supervision_mode_jog_supervision_mode,
    set_motion_supervision_sensitivity_jog_supervision_sensitivity,
    get_motion_supervision_collision_prediction_mode,
    set_motion_supervision_collision_prediction_mode,
    get_path_supervision,
    get_path_supervision_actions,
    set_path_supervision_mode,
    set_path_supervision_level,
    get_non_motion_execution_mode,
    get_nonmotion_execution_actions,
    set_nonmotion_execution_mode,
    get_mechunits,
    get_mechunit,
    get_mechunit_action,
    set_mechunit,
    set_compliance_lead_through,
    get_compliance_lead_through,
    set_fine_calibration,
    update_syncronize_revolution_counter,
    get_physical_joints,
    get_cartesian_value,
    set_mechanical_unit,
    get_robtarget,
    get_joint_target,
    subscribe_on_mechunit_mode_change,
    get_joints_from_position,
    get_position_from_joints,
    get_all_joint_solution,
    get_joints_from_cartesian,
    get_calibration_info,
    post_calibration_for_baseframe,
    post_calibration_for_baseframemoving,
    post_calibration_for_externalrobotnombasenew,
    post_calibration_for_robotaxisrot,
    post_calibration_for_singleuserrotnew,
    post_calibration_for_rotextctrlzdef,
    post_calibration_for_singleuserlin,
    post_calibration_for_singletrack,
    post_calibration_for_robotaxisrot2,
    get_base_frame,
    get_base_frame_actions,
    set_base_frame,
    get_axes,
    get_axis,
    get_axis_actions,
    get_axis_pose,
    set_axis_pose,
    update_commutate,
    update_sync_revolution_counter,
    set_smb_data,
    post_clear_smb_data,
    get_smb_data,
    get_smb_data_actions,
    get_motor_calib_names,
)


class _MockTransport(httpx.AsyncBaseTransport):
    """Transport mock retournant une réponse HTTP configurable."""

    def __init__(self, status_code: int = 200, content: bytes = b"") -> None:
        self.status_code = status_code
        self.content = content
        self.last_request: httpx.Request | None = None

    async def handle_async_request(self, request: httpx.Request) -> httpx.Response:
        self.last_request = request
        return httpx.Response(self.status_code, content=self.content, request=request)


def _make_client(transport: _MockTransport) -> RWSClient:
    """Construit un RWSClient branché sur le transport mock."""
    client = RWSClient.__new__(RWSClient)
    client._http = httpx.AsyncClient(
        transport=transport,
        base_url="http://localhost/",
    )
    client.host = "localhost"
    return client


@pytest.mark.asyncio
async def test_get_motion_system() -> None:
    """Vérifie que get_motion_system émet GET /rw/motionsystem."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_motion_system(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/motionsystem"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_motion_system_action() -> None:
    """Vérifie que get_motion_system_action émet GET /rw/motionsystem."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_motion_system_action(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/motionsystem"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_set_mechunit_for_jogging() -> None:
    """Vérifie que set_mechunit_for_jogging émet POST /rw/motionsystem."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await set_mechunit_for_jogging(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/motionsystem"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_post_perform_jogging() -> None:
    """Vérifie que post_perform_jogging émet POST /rw/motionsystem."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await post_perform_jogging(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/motionsystem"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_set_robo_target_position() -> None:
    """Vérifie que set_robo_target_position émet POST /rw/motionsystem."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await set_robo_target_position(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/motionsystem"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_get_check_change_count() -> None:
    """Vérifie que get_check_change_count émet GET /rw/motionsystem/checkchangecount."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_check_change_count(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/motionsystem/checkchangecount"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_subscribe_on_error_eventchange() -> None:
    """Vérifie que subscribe_on_error_eventchange émet POST /subscription."""
    transport = _MockTransport(status_code=201)
    client = _make_client(transport)

    resp = await subscribe_on_error_eventchange(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/subscription"
    assert resp.status_code == 201

@pytest.mark.asyncio
async def test_get_error_state() -> None:
    """Vérifie que get_error_state émet GET /rw/motionsystem/errorstate."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_error_state(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/motionsystem/errorstate"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_motion_supervision() -> None:
    """Vérifie que get_motion_supervision émet GET /rw/motionsystem/motionsupervision."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_motion_supervision(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/motionsystem/motionsupervision"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_motion_supervision_actions() -> None:
    """Vérifie que get_motion_supervision_actions émet GET /rw/motionsystem/motionsupervision."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_motion_supervision_actions(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/motionsystem/motionsupervision"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_set_motion_supervision_mode_jog_supervision_mode() -> None:
    """Vérifie que set_motion_supervision_mode_jog_supervision_mode émet POST /rw/motionsystem/motionsupervision."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await set_motion_supervision_mode_jog_supervision_mode(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/motionsystem/motionsupervision"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_set_motion_supervision_sensitivity_jog_supervision_sensitivity() -> None:
    """Vérifie que set_motion_supervision_sensitivity_jog_supervision_sensitivity émet POST /rw/motionsystem/motionsupervision."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await set_motion_supervision_sensitivity_jog_supervision_sensitivity(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/motionsystem/motionsupervision"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_get_motion_supervision_collision_prediction_mode() -> None:
    """Vérifie que get_motion_supervision_collision_prediction_mode émet GET /rw/motionsystem/motionsupervision."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_motion_supervision_collision_prediction_mode(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/motionsystem/motionsupervision"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_set_motion_supervision_collision_prediction_mode() -> None:
    """Vérifie que set_motion_supervision_collision_prediction_mode émet POST /rw/motionsystem/motionsupervision."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await set_motion_supervision_collision_prediction_mode(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/motionsystem/motionsupervision"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_get_path_supervision() -> None:
    """Vérifie que get_path_supervision émet GET /rw/motionsystem/pathsupervision."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_path_supervision(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/motionsystem/pathsupervision"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_path_supervision_actions() -> None:
    """Vérifie que get_path_supervision_actions émet GET /rw/motionsystem/pathsupervision."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_path_supervision_actions(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/motionsystem/pathsupervision"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_set_path_supervision_mode() -> None:
    """Vérifie que set_path_supervision_mode émet POST /rw/motionsystem/pathsupervision."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await set_path_supervision_mode(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/motionsystem/pathsupervision"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_set_path_supervision_level() -> None:
    """Vérifie que set_path_supervision_level émet POST /rw/motionsystem/pathsupervision."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await set_path_supervision_level(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/motionsystem/pathsupervision"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_get_non_motion_execution_mode() -> None:
    """Vérifie que get_non_motion_execution_mode émet GET /rw/motionsystem/nonmotionexecution."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_non_motion_execution_mode(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/motionsystem/nonmotionexecution"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_nonmotion_execution_actions() -> None:
    """Vérifie que get_nonmotion_execution_actions émet GET /rw/motionsystem/nonmotionexecution."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_nonmotion_execution_actions(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/motionsystem/nonmotionexecution"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_set_nonmotion_execution_mode() -> None:
    """Vérifie que set_nonmotion_execution_mode émet POST /rw/motionsystem/nonmotionexecution."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await set_nonmotion_execution_mode(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/motionsystem/nonmotionexecution"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_get_mechunits() -> None:
    """Vérifie que get_mechunits émet GET /rw/motionsystem/mechunits."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_mechunits(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/motionsystem/mechunits"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_mechunit() -> None:
    """Vérifie que get_mechunit émet GET /rw/motionsystem/mechunits/{mechunit}."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_mechunit(client, "mechunit_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/motionsystem/mechunits/mechunit_test"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_mechunit_action() -> None:
    """Vérifie que get_mechunit_action émet GET /rw/motionsystem/mechunits/{mechunit}."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_mechunit_action(client, "mechunit_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/motionsystem/mechunits/mechunit_test"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_set_mechunit() -> None:
    """Vérifie que set_mechunit émet POST /rw/motionsystem/mechunits/{mechunit}."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await set_mechunit(client, "mechunit_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/motionsystem/mechunits/mechunit_test"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_set_compliance_lead_through() -> None:
    """Vérifie que set_compliance_lead_through émet POST /rw/motionsystem/mechunits/{mechunit}."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await set_compliance_lead_through(client, "mechunit_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/motionsystem/mechunits/mechunit_test"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_get_compliance_lead_through() -> None:
    """Vérifie que get_compliance_lead_through émet GET /rw/motionsystem/mechunits/{mechunit}."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_compliance_lead_through(client, "mechunit_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/motionsystem/mechunits/mechunit_test"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_set_fine_calibration() -> None:
    """Vérifie que set_fine_calibration émet POST /rw/motionsystem/mechunits/{mechunit}."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await set_fine_calibration(client, "mechunit_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/motionsystem/mechunits/mechunit_test"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_update_syncronize_revolution_counter() -> None:
    """Vérifie que update_syncronize_revolution_counter émet POST /rw/motionsystem/mechunits/{mechunit}."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await update_syncronize_revolution_counter(client, "mechunit_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/motionsystem/mechunits/mechunit_test"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_get_physical_joints() -> None:
    """Vérifie que get_physical_joints émet GET /rw/motionsystem/mechunits/{mechunit}/pjoints."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_physical_joints(client, "mechunit_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/motionsystem/mechunits/mechunit_test/pjoints"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_cartesian_value() -> None:
    """Vérifie que get_cartesian_value émet GET /rw/motionsystem/mechunits/{mechunit}/cartesian."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_cartesian_value(client, "mechunit_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/motionsystem/mechunits/mechunit_test/cartesian"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_set_mechanical_unit() -> None:
    """Vérifie que set_mechanical_unit émet POST /rw/motionsystem/mechunits/{mechunit}."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await set_mechanical_unit(client, "mechunit_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/motionsystem/mechunits/mechunit_test"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_get_robtarget() -> None:
    """Vérifie que get_robtarget émet GET /rw/motionsystem/mechunits/{mechunit}/robtarget."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_robtarget(client, "mechunit_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/motionsystem/mechunits/mechunit_test/robtarget"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_joint_target() -> None:
    """Vérifie que get_joint_target émet GET /rw/motionsystem/mechunits/{mechunit}/jointtarget."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_joint_target(client, "mechunit_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/motionsystem/mechunits/mechunit_test/jointtarget"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_subscribe_on_mechunit_mode_change() -> None:
    """Vérifie que subscribe_on_mechunit_mode_change émet POST /subscription."""
    transport = _MockTransport(status_code=201)
    client = _make_client(transport)

    resp = await subscribe_on_mechunit_mode_change(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/subscription"
    assert resp.status_code == 201

@pytest.mark.asyncio
async def test_get_joints_from_position() -> None:
    """Vérifie que get_joints_from_position émet POST /rw/motionsystem/mechunits/{mechunit}."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_joints_from_position(client, "mechunit_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/motionsystem/mechunits/mechunit_test"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_position_from_joints() -> None:
    """Vérifie que get_position_from_joints émet POST /rw/motionsystem/mechunits/{mechunit}."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_position_from_joints(client, "mechunit_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/motionsystem/mechunits/mechunit_test"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_all_joint_solution() -> None:
    """Vérifie que get_all_joint_solution émet POST /rw/motionsystem/mechunits/{mechunit}."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_all_joint_solution(client, "mechunit_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/motionsystem/mechunits/mechunit_test"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_joints_from_cartesian() -> None:
    """Vérifie que get_joints_from_cartesian émet POST /rw/motionsystem/mechunits/{mechunit}."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_joints_from_cartesian(client, "mechunit_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/motionsystem/mechunits/mechunit_test"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_calibration_info() -> None:
    """Vérifie que get_calibration_info émet GET /rw/motionsystem/mechunits/{mechunit}/calibrationinfo."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_calibration_info(client, "mechunit_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/motionsystem/mechunits/mechunit_test/calibrationinfo"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_post_calibration_for_baseframe() -> None:
    """Vérifie que post_calibration_for_baseframe émet POST /rw/motionsystem/mechunits/{mechunit}/calib."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await post_calibration_for_baseframe(client, "mechunit_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/motionsystem/mechunits/mechunit_test/calib"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_post_calibration_for_baseframemoving() -> None:
    """Vérifie que post_calibration_for_baseframemoving émet POST /rw/motionsystem/mechunits/{mechunit}/calib."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await post_calibration_for_baseframemoving(client, "mechunit_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/motionsystem/mechunits/mechunit_test/calib"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_post_calibration_for_externalrobotnombasenew() -> None:
    """Vérifie que post_calibration_for_externalrobotnombasenew émet POST /rw/motionsystem/mechunits/{mechunit}/calib."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await post_calibration_for_externalrobotnombasenew(client, "mechunit_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/motionsystem/mechunits/mechunit_test/calib"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_post_calibration_for_robotaxisrot() -> None:
    """Vérifie que post_calibration_for_robotaxisrot émet POST /rw/motionsystem/mechunits/{mechunit}/calib."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await post_calibration_for_robotaxisrot(client, "mechunit_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/motionsystem/mechunits/mechunit_test/calib"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_post_calibration_for_singleuserrotnew() -> None:
    """Vérifie que post_calibration_for_singleuserrotnew émet POST /rw/motionsystem/mechunits/{mechunit}/calib."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await post_calibration_for_singleuserrotnew(client, "mechunit_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/motionsystem/mechunits/mechunit_test/calib"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_post_calibration_for_rotextctrlzdef() -> None:
    """Vérifie que post_calibration_for_rotextctrlzdef émet POST /rw/motionsystem/mechunits/{mechunit}/calib."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await post_calibration_for_rotextctrlzdef(client, "mechunit_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/motionsystem/mechunits/mechunit_test/calib"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_post_calibration_for_singleuserlin() -> None:
    """Vérifie que post_calibration_for_singleuserlin émet POST /rw/motionsystem/mechunits/{mechunit}/calib."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await post_calibration_for_singleuserlin(client, "mechunit_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/motionsystem/mechunits/mechunit_test/calib"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_post_calibration_for_singletrack() -> None:
    """Vérifie que post_calibration_for_singletrack émet POST /rw/motionsystem/mechunits/{mechunit}/calib."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await post_calibration_for_singletrack(client, "mechunit_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/motionsystem/mechunits/mechunit_test/calib"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_post_calibration_for_robotaxisrot2() -> None:
    """Vérifie que post_calibration_for_robotaxisrot2 émet POST /rw/motionsystem/mechunits/{mechunit}/calib."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await post_calibration_for_robotaxisrot2(client, "mechunit_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/motionsystem/mechunits/mechunit_test/calib"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_base_frame() -> None:
    """Vérifie que get_base_frame émet GET /rw/motionsystem/mechunits/{mechunit}/baseframe."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_base_frame(client, "mechunit_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/motionsystem/mechunits/mechunit_test/baseframe"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_base_frame_actions() -> None:
    """Vérifie que get_base_frame_actions émet GET /rw/motionsystem/mechunits/{mechunit}/baseframe."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_base_frame_actions(client, "mechunit_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/motionsystem/mechunits/mechunit_test/baseframe"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_set_base_frame() -> None:
    """Vérifie que set_base_frame émet POST /rw/motionsystem/mechunits/{mechunit}/baseframe."""
    transport = _MockTransport(status_code=202)
    client = _make_client(transport)

    resp = await set_base_frame(client, "mechunit_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/motionsystem/mechunits/mechunit_test/baseframe"
    assert resp.status_code == 202

@pytest.mark.asyncio
async def test_get_axes() -> None:
    """Vérifie que get_axes émet GET /rw/motionsystem/mechunits/{mechunit}/axes."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_axes(client, "mechunit_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/motionsystem/mechunits/mechunit_test/axes"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_axis() -> None:
    """Vérifie que get_axis émet GET /rw/motionsystem/mechunits/{mechunit}/axes/{axis_num}."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_axis(client, "mechunit_test", "axis_num_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/motionsystem/mechunits/mechunit_test/axes/axis_num_test"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_axis_actions() -> None:
    """Vérifie que get_axis_actions émet GET /rw/motionsystem/mechunits/{mechunit}/axes/{axis_num}."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_axis_actions(client, "mechunit_test", "axis_num_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/motionsystem/mechunits/mechunit_test/axes/axis_num_test"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_axis_pose() -> None:
    """Vérifie que get_axis_pose émet GET /rw/motionsystem/mechunits/{mechunit}/axes/{axis_num}."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_axis_pose(client, "mechunit_test", "axis_num_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/motionsystem/mechunits/mechunit_test/axes/axis_num_test"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_set_axis_pose() -> None:
    """Vérifie que set_axis_pose émet POST /rw/motionsystem/mechunits/{mechunit}/axes/{axis_num}."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await set_axis_pose(client, "mechunit_test", "axis_num_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/motionsystem/mechunits/mechunit_test/axes/axis_num_test"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_update_commutate() -> None:
    """Vérifie que update_commutate émet POST /rw/motionsystem/mechunits/{mechunit}/axes/{axis_num}."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await update_commutate(client, "mechunit_test", "axis_num_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/motionsystem/mechunits/mechunit_test/axes/axis_num_test"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_update_sync_revolution_counter() -> None:
    """Vérifie que update_sync_revolution_counter émet POST /rw/motionsystem/mechunits/{mechunit}/axes/{axis_num}."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await update_sync_revolution_counter(client, "mechunit_test", "axis_num_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/motionsystem/mechunits/mechunit_test/axes/axis_num_test"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_set_smb_data() -> None:
    """Vérifie que set_smb_data émet POST /rw/motionsystem/mechunits/{mechunit}/smbdata."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await set_smb_data(client, "mechunit_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/motionsystem/mechunits/mechunit_test/smbdata"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_post_clear_smb_data() -> None:
    """Vérifie que post_clear_smb_data émet POST /rw/motionsystem/mechunits/{mechunit}/smbdata."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await post_clear_smb_data(client, "mechunit_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/motionsystem/mechunits/mechunit_test/smbdata"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_get_smb_data() -> None:
    """Vérifie que get_smb_data émet GET /rw/motionsystem/mechunits/{mechunit}/smbdata."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_smb_data(client, "mechunit_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/motionsystem/mechunits/mechunit_test/smbdata"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_smb_data_actions() -> None:
    """Vérifie que get_smb_data_actions émet GET /rw/motionsystem/mechunits/{mechunit}/smbdata."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_smb_data_actions(client, "mechunit_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/motionsystem/mechunits/mechunit_test/smbdata"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_motor_calib_names() -> None:
    """Vérifie que get_motor_calib_names émet GET /rw/motionsystem/mechunits/{mechunit}/motorcalib."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_motor_calib_names(client, "mechunit_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/motionsystem/mechunits/mechunit_test/motorcalib"
    assert resp.status_code == 200
