# This file is AUTO-GENERATED by contrib/generator/main.py
# DO NOT EDIT MANUALLY — run the generator to regenerate.
"""Tests unitaires auto-générés pour rws/operations_on_io_profinet_device."""
from __future__ import annotations

import pytest
import httpx

from abb_rws_client._core.client import RWSClient
from abb_rws_client.rws.operations_on_io_profinet_device import (
    get_profinet_device_read_record_implicit_data,
    post_read_record_implicit_data_from_device_in,
    get_forms,
    get_profinet_device_read_record_data,
    get_profinet_device_read_record_data,
    get_forms,
    get_profinet_device_alarms_xml_response,
    post_clear_the_alarms,
    get_forms,
)


class _MockTransport(httpx.AsyncBaseTransport):
    """Transport mock retournant une réponse HTTP configurable."""

    def __init__(self, status_code: int = 200, content: bytes = b"") -> None:
        self.status_code = status_code
        self.content = content
        self.last_request: httpx.Request | None = None

    async def handle_async_request(self, request: httpx.Request) -> httpx.Response:
        self.last_request = request
        return httpx.Response(self.status_code, content=self.content, request=request)


def _make_client(transport: _MockTransport) -> RWSClient:
    """Construit un RWSClient branché sur le transport mock."""
    client = RWSClient.__new__(RWSClient)
    client._http = httpx.AsyncClient(
        transport=transport,
        base_url="http://localhost/",
    )
    client.host = "localhost"
    return client


@pytest.mark.asyncio
async def test_get_profinet_device_read_record_implicit_data() -> None:
    """Vérifie que get_profinet_device_read_record_implicit_data émet GET rw/iosystem/devices/{network}/{device}/implicitdata."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_profinet_device_read_record_implicit_data(client, "network_test", "device_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/iosystem/devices/network_test/device_test/implicitdata"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_post_read_record_implicit_data_from_device_in() -> None:
    """Vérifie que post_read_record_implicit_data_from_device_in émet POST rw/iosystem/devices/{network}/{device}/implicitdata."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await post_read_record_implicit_data_from_device_in(client, "network_test", "device_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/iosystem/devices/network_test/device_test/implicitdata"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_forms() -> None:
    """Vérifie que get_forms émet OPTIONS rw/iosystem/devices/{network}/{device}/implicitdata."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_forms(client, "network_test", "device_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "OPTIONS"
    assert transport.last_request.url.path == "/rw/iosystem/devices/network_test/device_test/implicitdata"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_profinet_device_read_record_data() -> None:
    """Vérifie que get_profinet_device_read_record_data émet GET rw/iosystem/devices/{network}/{device}/explicitdata."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_profinet_device_read_record_data(client, "network_test", "device_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/iosystem/devices/network_test/device_test/explicitdata"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_profinet_device_read_record_data() -> None:
    """Vérifie que get_profinet_device_read_record_data émet POST rw/iosystem/devices/{network}/{device}/explicitdata."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_profinet_device_read_record_data(client, "network_test", "device_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/iosystem/devices/network_test/device_test/explicitdata"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_forms() -> None:
    """Vérifie que get_forms émet OPTIONS rw/iosystem/devices/{network}/{device}/explicitdata."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_forms(client, "network_test", "device_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "OPTIONS"
    assert transport.last_request.url.path == "/rw/iosystem/devices/network_test/device_test/explicitdata"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_profinet_device_alarms_xml_response() -> None:
    """Vérifie que get_profinet_device_alarms_xml_response émet GET rw/iosystem/devices/{network}/{device}/alarms."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_profinet_device_alarms_xml_response(client, "network_test", "device_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/iosystem/devices/network_test/device_test/alarms"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_post_clear_the_alarms() -> None:
    """Vérifie que post_clear_the_alarms émet POST rw/iosystem/devices/{network}/{device}/alarms/clear."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await post_clear_the_alarms(client, "network_test", "device_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/iosystem/devices/network_test/device_test/alarms/clear"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_forms() -> None:
    """Vérifie que get_forms émet OPTIONS rw/iosystem/devices/{network}/{device}/alarms/clear."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_forms(client, "network_test", "device_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "OPTIONS"
    assert transport.last_request.url.path == "/rw/iosystem/devices/network_test/device_test/alarms/clear"
    assert resp.status_code == 200
