# This file is AUTO-GENERATED by contrib/generator/main.py
# DO NOT EDIT MANUALLY — run the generator to regenerate.
"""Tests unitaires auto-générés pour rws/elog."""
from __future__ import annotations

import pytest
import httpx

from abb_rws_client._core.client import RWSClient
from abb_rws_client.rws.elog import (
    get_elog_resources,
    get_elog_actions,
    post_clear_elog_messages,
    save_elog_in_system_dump_format,
    get_elog_messages_in_domain,
    get_actions_on_elog_domain,
    post_clear_elog_messages,
    subscribe_on_elog_domain,
    get_elog_message_in_domain,
)


class _MockTransport(httpx.AsyncBaseTransport):
    """Transport mock retournant une réponse HTTP configurable."""

    def __init__(self, status_code: int = 200, content: bytes = b"") -> None:
        self.status_code = status_code
        self.content = content
        self.last_request: httpx.Request | None = None

    async def handle_async_request(self, request: httpx.Request) -> httpx.Response:
        self.last_request = request
        return httpx.Response(self.status_code, content=self.content, request=request)


def _make_client(transport: _MockTransport) -> RWSClient:
    """Construit un RWSClient branché sur le transport mock."""
    client = RWSClient.__new__(RWSClient)
    client._http = httpx.AsyncClient(
        transport=transport,
        base_url="http://localhost/",
    )
    client.host = "localhost"
    return client


@pytest.mark.asyncio
async def test_get_elog_resources() -> None:
    """Vérifie que get_elog_resources émet GET /rw/elog."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_elog_resources(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/elog"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_elog_actions() -> None:
    """Vérifie que get_elog_actions émet GET /rw/elog."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_elog_actions(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/elog"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_post_clear_elog_messages() -> None:
    """Vérifie que post_clear_elog_messages émet POST /rw/elog."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await post_clear_elog_messages(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/elog"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_save_elog_in_system_dump_format() -> None:
    """Vérifie que save_elog_in_system_dump_format émet POST /rw/elog."""
    transport = _MockTransport(status_code=202)
    client = _make_client(transport)

    resp = await save_elog_in_system_dump_format(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/elog"
    assert resp.status_code == 202

@pytest.mark.asyncio
async def test_get_elog_messages_in_domain() -> None:
    """Vérifie que get_elog_messages_in_domain émet GET /rw/elog/{domain-number}."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_elog_messages_in_domain(client, "domain_number_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/elog/domain_number_test"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_actions_on_elog_domain() -> None:
    """Vérifie que get_actions_on_elog_domain émet GET /rw/elog/{domain-number}."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_actions_on_elog_domain(client, "domain_number_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/elog/domain_number_test"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_post_clear_elog_messages() -> None:
    """Vérifie que post_clear_elog_messages émet POST /rw/elog/{domain-number}."""
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await post_clear_elog_messages(client, "domain_number_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/elog/domain_number_test"
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_subscribe_on_elog_domain() -> None:
    """Vérifie que subscribe_on_elog_domain émet POST /subscription."""
    transport = _MockTransport(status_code=201)
    client = _make_client(transport)

    resp = await subscribe_on_elog_domain(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/subscription"
    assert resp.status_code == 201

@pytest.mark.asyncio
async def test_get_elog_message_in_domain() -> None:
    """Vérifie que get_elog_message_in_domain émet GET /rw/elog/{domain-number}/{sequence-number}."""
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_elog_message_in_domain(client, "domain_number_test", "sequence_number_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/elog/domain_number_test/sequence_number_test"
    assert resp.status_code == 200
