# This file is AUTO-GENERATED by utils/generator/main.py
# DO NOT EDIT MANUALLY — run the generator to regenerate.
#  Generator author: Clement RACINET
"""Auto-generated unit tests for rws/operations_on_io_profinet_device."""
from __future__ import annotations

import httpx
import pytest

from abb_rws_client.core.client import RWSClient
from abb_rws_client.rws.operations_on_io_profinet_device import (
    get_forms,
    get_forms_2,
    get_forms_3,
    get_profinet_device_alarms_xml_response,
    get_profinet_device_read_record_data,
    get_profinet_device_read_record_data_2,
    get_profinet_device_read_record_implicit_data,
    post_clear_the_alarms,
    post_read_record_implicit_data_from_device_in,
)


class _MockTransport(httpx.AsyncBaseTransport):
    """Mock transport returning a configurable HTTP response."""

    def __init__(self, status_code: int = 200, content: bytes = b"") -> None:
        self.status_code = status_code
        self.content = content
        self.last_request: httpx.Request | None = None

    async def handle_async_request(self, request: httpx.Request) -> httpx.Response:
        self.last_request = request
        return httpx.Response(self.status_code, content=self.content, request=request)


def _make_client(transport: _MockTransport) -> RWSClient:
    """Build an RWSClient connected to the mock transport."""
    client = RWSClient.__new__(RWSClient)
    client._http = httpx.AsyncClient(
        transport=transport,
        base_url="http://localhost/",
    )
    client.host = "localhost"
    return client


@pytest.mark.asyncio
async def test_get_profinet_device_read_record_implicit_data() -> None:
    """
    Verify that get_profinet_device_read_record_implicit_data sends GET
        rw/iosystem/devices/{network}/{device}/implicitdata.
    """
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_profinet_device_read_record_implicit_data(
        client,
        "network_test",
        "device_test"
    )

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    expected_path = "/rw/iosystem/devices/network_test/device_test/implicitdata"
    assert transport.last_request.url.path == expected_path
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_post_read_record_implicit_data_from_device_in() -> None:
    """
    Verify that post_read_record_implicit_data_from_device_in sends POST
        rw/iosystem/devices/{network}/{device}/implicitdata.
    """
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await post_read_record_implicit_data_from_device_in(
        client,
        "network_test",
        "device_test"
    )

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    expected_path = "/rw/iosystem/devices/network_test/device_test/implicitdata"
    assert transport.last_request.url.path == expected_path
    ct = transport.last_request.headers.get("content-type") or ""
    assert "application/x-www-form-urlencoded" in ct
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_forms() -> None:
    """
    Verify that get_forms sends OPTIONS rw/iosystem/devices/{network}/{device}/implicitdata.
    """
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_forms(client, "network_test", "device_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "OPTIONS"
    expected_path = "/rw/iosystem/devices/network_test/device_test/implicitdata"
    assert transport.last_request.url.path == expected_path
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_profinet_device_read_record_data() -> None:
    """
    Verify that get_profinet_device_read_record_data sends GET
        rw/iosystem/devices/{network}/{device}/explicitdata.
    """
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_profinet_device_read_record_data(client, "network_test", "device_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    expected_path = "/rw/iosystem/devices/network_test/device_test/explicitdata"
    assert transport.last_request.url.path == expected_path
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_profinet_device_read_record_data_2() -> None:
    """
    Verify that get_profinet_device_read_record_data_2 sends POST
        rw/iosystem/devices/{network}/{device}/explicitdata.
    """
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_profinet_device_read_record_data_2(client, "network_test", "device_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    expected_path = "/rw/iosystem/devices/network_test/device_test/explicitdata"
    assert transport.last_request.url.path == expected_path
    ct = transport.last_request.headers.get("content-type") or ""
    assert "application/x-www-form-urlencoded" in ct
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_forms_2() -> None:
    """
    Verify that get_forms_2 sends OPTIONS rw/iosystem/devices/{network}/{device}/explicitdata.
    """
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_forms_2(client, "network_test", "device_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "OPTIONS"
    expected_path = "/rw/iosystem/devices/network_test/device_test/explicitdata"
    assert transport.last_request.url.path == expected_path
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_profinet_device_alarms_xml_response() -> None:
    """
    Verify that get_profinet_device_alarms_xml_response sends GET
        rw/iosystem/devices/{network}/{device}/alarms.
    """
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_profinet_device_alarms_xml_response(client, "network_test", "device_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    expected_path = "/rw/iosystem/devices/network_test/device_test/alarms"
    assert transport.last_request.url.path == expected_path
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_post_clear_the_alarms() -> None:
    """
    Verify that post_clear_the_alarms sends POST
        rw/iosystem/devices/{network}/{device}/alarms/clear.
    """
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await post_clear_the_alarms(client, "network_test", "device_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    expected_path = "/rw/iosystem/devices/network_test/device_test/alarms/clear"
    assert transport.last_request.url.path == expected_path
    ct = transport.last_request.headers.get("content-type") or ""
    assert "application/x-www-form-urlencoded" in ct
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_forms_3() -> None:
    """
    Verify that get_forms_3 sends OPTIONS rw/iosystem/devices/{network}/{device}/alarms/clear.
    """
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_forms_3(client, "network_test", "device_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "OPTIONS"
    expected_path = "/rw/iosystem/devices/network_test/device_test/alarms/clear"
    assert transport.last_request.url.path == expected_path
    assert resp.status_code == 200
