# This file is AUTO-GENERATED by utils/generator/main.py
# DO NOT EDIT MANUALLY — run the generator to regenerate.
#  Generator author: Clement RACINET
"""Auto-generated unit tests for rws/elog."""
from __future__ import annotations

import httpx
import pytest

from abb_rws_client_python_rw6.core.client import RWSClient
from abb_rws_client_python_rw6.rws.elog import (
    get_actions_on_elog_domain,
    get_elog_actions,
    get_elog_message_in_domain,
    get_elog_messages_in_domain,
    get_elog_resources,
    post_clear_elog_messages,
    post_clear_elog_messages_2,
    save_elog_in_system_dump_format,
    subscribe_on_elog_domain,
)


class _MockTransport(httpx.AsyncBaseTransport):
    """Mock transport returning a configurable HTTP response."""

    def __init__(self, status_code: int = 200, content: bytes = b"") -> None:
        self.status_code = status_code
        self.content = content
        self.last_request: httpx.Request | None = None

    async def handle_async_request(self, request: httpx.Request) -> httpx.Response:
        self.last_request = request
        return httpx.Response(self.status_code, content=self.content, request=request)


def _make_client(transport: _MockTransport) -> RWSClient:
    """Build an RWSClient connected to the mock transport."""
    client = RWSClient.__new__(RWSClient)
    client._http = httpx.AsyncClient(
        transport=transport,
        base_url="http://localhost/",
    )
    client.host = "localhost"
    return client


@pytest.mark.asyncio
async def test_get_elog_resources() -> None:
    """
    Verify that get_elog_resources sends GET /rw/elog.
    """
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_elog_resources(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/elog"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_elog_actions() -> None:
    """
    Verify that get_elog_actions sends GET /rw/elog.
    """
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_elog_actions(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/elog"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_post_clear_elog_messages() -> None:
    """
    Verify that post_clear_elog_messages sends POST /rw/elog.
    """
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await post_clear_elog_messages(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/elog"
    ct = transport.last_request.headers.get("content-type") or ""
    assert "application/x-www-form-urlencoded" in ct
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_save_elog_in_system_dump_format() -> None:
    """
    Verify that save_elog_in_system_dump_format sends POST /rw/elog.
    """
    transport = _MockTransport(status_code=202)
    client = _make_client(transport)

    resp = await save_elog_in_system_dump_format(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/elog"
    ct = transport.last_request.headers.get("content-type") or ""
    assert "application/x-www-form-urlencoded" in ct
    assert resp.status_code == 202

@pytest.mark.asyncio
async def test_get_elog_messages_in_domain() -> None:
    """
    Verify that get_elog_messages_in_domain sends GET /rw/elog/{domain-number}.
    """
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_elog_messages_in_domain(client, "domain_number_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/elog/domain_number_test"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_get_actions_on_elog_domain() -> None:
    """
    Verify that get_actions_on_elog_domain sends GET /rw/elog/{domain-number}.
    """
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_actions_on_elog_domain(client, "domain_number_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/elog/domain_number_test"
    assert resp.status_code == 200

@pytest.mark.asyncio
async def test_post_clear_elog_messages_2() -> None:
    """
    Verify that post_clear_elog_messages_2 sends POST /rw/elog/{domain-number}.
    """
    transport = _MockTransport(status_code=204)
    client = _make_client(transport)

    resp = await post_clear_elog_messages_2(client, "domain_number_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/rw/elog/domain_number_test"
    ct = transport.last_request.headers.get("content-type") or ""
    assert "application/x-www-form-urlencoded" in ct
    assert resp.status_code == 204

@pytest.mark.asyncio
async def test_subscribe_on_elog_domain() -> None:
    """
    Verify that subscribe_on_elog_domain sends POST /subscription.
    """
    transport = _MockTransport(status_code=201)
    client = _make_client(transport)

    resp = await subscribe_on_elog_domain(client)

    assert transport.last_request is not None
    assert transport.last_request.method == "POST"
    assert transport.last_request.url.path == "/subscription"
    ct = transport.last_request.headers.get("content-type") or ""
    assert "application/x-www-form-urlencoded" in ct
    assert resp.status_code == 201

@pytest.mark.asyncio
async def test_get_elog_message_in_domain() -> None:
    """
    Verify that get_elog_message_in_domain sends GET /rw/elog/{domain-number}/{sequence-number}.
    """
    transport = _MockTransport(status_code=200)
    client = _make_client(transport)

    resp = await get_elog_message_in_domain(client, "domain_number_test", "sequence_number_test")

    assert transport.last_request is not None
    assert transport.last_request.method == "GET"
    assert transport.last_request.url.path == "/rw/elog/domain_number_test/sequence_number_test"
    assert resp.status_code == 200
