# This file is AUTO-GENERATED by contrib/generator/main.py
# DO NOT EDIT MANUALLY — run the generator to regenerate.
#  Generator author: Clément RACINET
"""
RWS module: Controller Service → Operations on Backup Resource → Get backup resources

1:1 mirror of the ABB RobotWare 6 REST API.
Each function maps to exactly one HTTP endpoint.
No composed logic — see highlevel/ for wrappers.
"""

from __future__ import annotations

import httpx

from abb_rws_client._core.client import RWSClient


async def get_backup_resources(client: RWSClient) -> httpx.Response:
    """
    Get backup resources.

    Route: ``GET /ctrl/backup``
    ABB constraints: Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.

    Example:
        # curl --digest -u "Default User":robotics "http://localhost/ctrl/backup"
    """
    return await client.get("/ctrl/backup")


async def get_backup_actions(
    client: RWSClient,
    action: str | None = None,
) -> httpx.Response:
    """
    Get backup actions.

    Route: ``GET /ctrl/backup``
    ABB constraints: Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        action: Query parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD_REQUEST(400)

    Example:
        # curl --digest -u "Default User":robotics "http://localhost/ctrl/backup?action=show"
    """
    return await client.get(
        "/ctrl/backup", params={k: v for k, v in {"action": action}.items() if v is not None}
    )


async def create_backup(
    client: RWSClient,
    action: str | None = None,
    environment_variables_such_as_temp_system_shall_be_possible_to_have_in_the_path_but_home_directory_cannot_be_used_as_backup_path_example_backup: str
    | None = None,
    archive: str | None = None,
) -> httpx.Response:
    """
    Create a Backup.

    Route: ``POST /ctrl/backup``
    ABB constraints: Requires UAS grant UAS_BACKUP. It is not possible to create backup with the same path and name as an environment variable directory (SYSTEM, HOME, SYSPAR etc). It is not possible create backup under HOME directory. Since backup is an asynchronous task, the location header can be subscribed on to ...

    Args:
        client: Open RWSClient instance.
        action: Query parameter. Optional.
        environment_variables_such_as_temp_system_shall_be_possible_to_have_in_the_path_but_home_directory_cannot_be_used_as_backup_path_example_backup: Body parameter. Optional.
        archive: Body parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 202.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: UNAUTHORIZED(401), FORBIDDEN(403), BAD_REQUEST(400), CONFLICT(409)

    Example:
        # curl --digest -u "Default User":robotics -d "backup=/fileservice/$syspar/tempfolder" -X POST "http://localhost/ctrl/back
    """
    return await client.post(
        "/ctrl/backup",
        params={k: v for k, v in {"action": action}.items() if v is not None},
        data={
            k: v
            for k, v in {
                "environment_variables_such_as_temp_system_shall_be_possible_to_have_in_the_path_but_home_directory_cannot_be_used_as_backup_path_example_backup": environment_variables_such_as_temp_system_shall_be_possible_to_have_in_the_path_but_home_directory_cannot_be_used_as_backup_path_example_backup,
                "archive": archive,
            }.items()
            if v is not None
        },
    )


async def post_restore_backup(
    client: RWSClient,
    action: str | None = None,
    path_must_be_part_of_the_controller_file_system_environment_variables_such_as_temp_system_shall_be_possible_to_have_in_the_path_example_backup: str
    | None = None,
) -> httpx.Response:
    """
    Restore a backup..

    Route: ``POST /ctrl/backup``
    ABB constraints: Requires UAS grant Restore a backup Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        action: Query parameter. Optional.
        path_must_be_part_of_the_controller_file_system_environment_variables_such_as_temp_system_shall_be_possible_to_have_in_the_path_example_backup: Body parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 204.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: UNSUPPORTED_MEDIA(415), FORBIDDEN(403), BAD_REQUEST(400)

    Example:
        # `curl –digest -u "Default User":robotics -d "backup=/fileservice/$syspar/tempfolder" -X POST "http://localhost/ctrl/back
    """
    return await client.post(
        "/ctrl/backup",
        params={k: v for k, v in {"action": action}.items() if v is not None},
        data={
            k: v
            for k, v in {
                "path_must_be_part_of_the_controller_file_system_environment_variables_such_as_temp_system_shall_be_possible_to_have_in_the_path_example_backup": path_must_be_part_of_the_controller_file_system_environment_variables_such_as_temp_system_shall_be_possible_to_have_in_the_path_example_backup
            }.items()
            if v is not None
        },
    )


async def get_check_restore(
    client: RWSClient,
    path_must_be_part_of_the_controller_file_system_environment_variables_such_as_temp_system_shall_be_possible_to_have_in_the_path_example_backup: str
    | None = None,
) -> httpx.Response:
    """
    Check Restore.

    Route: ``GET /ctrl/backup``
    ABB constraints: Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        path_must_be_part_of_the_controller_file_system_environment_variables_such_as_temp_system_shall_be_possible_to_have_in_the_path_example_backup: Query parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD_REQUEST(400)

    Example:
        # curl --digest -u "Default User":robotics "http://localhost/ctrl/backup?action=check-restore&backup=/fileservice/$syspar/
    """
    return await client.get(
        "/ctrl/backup",
        params={
            k: v
            for k, v in {
                "path_must_be_part_of_the_controller_file_system_environment_variables_such_as_temp_system_shall_be_possible_to_have_in_the_path_example_backup": path_must_be_part_of_the_controller_file_system_environment_variables_such_as_temp_system_shall_be_possible_to_have_in_the_path_example_backup
            }.items()
            if v is not None
        },
    )


async def get_backup_state(
    client: RWSClient,
    action: str | None = None,
) -> httpx.Response:
    """
    Get Backup State.

    Route: ``GET /ctrl/backup``
    ABB constraints: Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        action: Query parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD_REQUEST(400)

    Example:
        # curl --digest -u "Default User":robotics "http://localhost/ctrl/backup?action=backupstate"
    """
    return await client.get(
        "/ctrl/backup", params={k: v for k, v in {"action": action}.items() if v is not None}
    )


async def subscribe_on_backup_system_information(
    client: RWSClient,
    identifier: str | None = None,
    identifier_p: str | None = None,
) -> httpx.Response:
    """
    Subscribe on Backup System Information.

    Route: ``POST /subscription``
    ABB constraints: if the subscription is created during backup creation of the System (backup.log is in progress),the state will be in "pending". Not supported in bootserver mode. Not supported on virtual controller.

    Args:
        client: Open RWSClient instance.
        identifier: Body parameter. Optional.
        identifier_p: Body parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 201.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD_REQUEST(400) See

    Example:
        # only low priority subscription(-p=0) and medium priority subscription(-p=1) are allowed on this resource
    """
    return await client.post(
        "/subscription",
        data={
            k: v
            for k, v in {"identifier": identifier, "identifier_p": identifier_p}.items()
            if v is not None
        },
    )


async def get_backup_system_information(
    client: RWSClient,
    backup_path: str | None = None,
) -> httpx.Response:
    """
    Get backup system information.

    Route: ``GET /ctrl/backup/info/``
    ABB constraints: Not Supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        backup_path: Query parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: See

    Example:
        # curl --digest -u "Default User":robotics "http://localhost/ctrl/backup/info?backup-path=C:/Users/inshsal/Documents/Robot
    """
    return await client.get(
        "/ctrl/backup/info/",
        params={k: v for k, v in {"backup_path": backup_path}.items() if v is not None},
    )
