# This file is AUTO-GENERATED by contrib/generator/main.py
# DO NOT EDIT MANUALLY — run the generator to regenerate.
"""
RWS module : Controller Service → Operations on Backup Resource → Get backup resources

Miroir 1:1 de l'API REST ABB RobotWare 6.
Chaque fonction correspond à exactement un endpoint HTTP.
Aucune logique composée — voir highlevel/ pour les wrappers.
"""
from __future__ import annotations

import httpx

from abb_rws_client._core.client import RWSClient


async def get_backup_resources(client: RWSClient) -> httpx.Response:
    """
    Get backup resources.

    Route: ``GET /ctrl/backup``
    Contraintes ABB: Not supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 200.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.

    Example:
        # curl --digest -u "Default User":robotics "http://localhost/ctrl/backup"
    """
    return await client.get("/ctrl/backup")

async def get_backup_actions(
    client: RWSClient,
    action: str | None = None,
) -> httpx.Response:
    """
    Get backup actions.

    Route: ``GET /ctrl/backup``
    Contraintes ABB: Not supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        action: Paramètre query. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 200.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD_REQUEST(400)

    Example:
        # curl --digest -u "Default User":robotics "http://localhost/ctrl/backup?action=show"
    """
    return await client.get("/ctrl/backup", params={k: v for k, v in {"action": action}.items() if v is not None})

async def create_backup(
    client: RWSClient,
    action: str | None = None,
    environment_variables_such_as_temp_system_shall_be_possible_to_have_in_the_path_but_home_directory_cannot_be_used_as_backup_path_example_backup: str | None = None,
    archive: str | None = None,
) -> httpx.Response:
    """
    Create a Backup.

    Route: ``POST /ctrl/backup``
    Contraintes ABB: Requires UAS grant UAS_BACKUP. It is not possible to create backup with the same path and name as an environment variable directory (SYSTEM, HOME, SYSPAR etc). It is not possible create backup under HOME directory. Since backup is an asynchronous task, the location header can be subscribed on to ...

    Args:
        client: Instance RWSClient ouverte.
        action: Paramètre query. Optionnel.
        environment_variables_such_as_temp_system_shall_be_possible_to_have_in_the_path_but_home_directory_cannot_be_used_as_backup_path_example_backup: Paramètre body. Optionnel.
        archive: Paramètre body. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 202.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: UNAUTHORIZED(401), FORBIDDEN(403), BAD_REQUEST(400), CONFLICT(409)

    Example:
        # curl --digest -u "Default User":robotics -d "backup=/fileservice/$syspar/tempfolder" -X POST "http://localhost/ctrl/back
    """
    return await client.post("/ctrl/backup", params={k: v for k, v in {"action": action}.items() if v is not None}, data={k: v for k, v in {"environment_variables_such_as_temp_system_shall_be_possible_to_have_in_the_path_but_home_directory_cannot_be_used_as_backup_path_example_backup": environment_variables_such_as_temp_system_shall_be_possible_to_have_in_the_path_but_home_directory_cannot_be_used_as_backup_path_example_backup, "archive": archive}.items() if v is not None})

async def post_restore_backup(
    client: RWSClient,
    action: str | None = None,
    path_must_be_part_of_the_controller_file_system_environment_variables_such_as_temp_system_shall_be_possible_to_have_in_the_path_example_backup: str | None = None,
) -> httpx.Response:
    """
    Restore a backup..

    Route: ``POST /ctrl/backup``
    Contraintes ABB: Requires UAS grant Restore a backup Not supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        action: Paramètre query. Optionnel.
        path_must_be_part_of_the_controller_file_system_environment_variables_such_as_temp_system_shall_be_possible_to_have_in_the_path_example_backup: Paramètre body. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 204.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: UNSUPPORTED_MEDIA(415), FORBIDDEN(403), BAD_REQUEST(400)

    Example:
        # `curl –digest -u "Default User":robotics -d "backup=/fileservice/$syspar/tempfolder" -X POST "http://localhost/ctrl/back
    """
    return await client.post("/ctrl/backup", params={k: v for k, v in {"action": action}.items() if v is not None}, data={k: v for k, v in {"path_must_be_part_of_the_controller_file_system_environment_variables_such_as_temp_system_shall_be_possible_to_have_in_the_path_example_backup": path_must_be_part_of_the_controller_file_system_environment_variables_such_as_temp_system_shall_be_possible_to_have_in_the_path_example_backup}.items() if v is not None})

async def get_check_restore(
    client: RWSClient,
    path_must_be_part_of_the_controller_file_system_environment_variables_such_as_temp_system_shall_be_possible_to_have_in_the_path_example_backup: str | None = None,
) -> httpx.Response:
    """
    Check Restore.

    Route: ``GET /ctrl/backup``
    Contraintes ABB: Not supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        path_must_be_part_of_the_controller_file_system_environment_variables_such_as_temp_system_shall_be_possible_to_have_in_the_path_example_backup: Paramètre query. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 200.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD_REQUEST(400)

    Example:
        # curl --digest -u "Default User":robotics "http://localhost/ctrl/backup?action=check-restore&backup=/fileservice/$syspar/
    """
    return await client.get("/ctrl/backup", params={k: v for k, v in {"path_must_be_part_of_the_controller_file_system_environment_variables_such_as_temp_system_shall_be_possible_to_have_in_the_path_example_backup": path_must_be_part_of_the_controller_file_system_environment_variables_such_as_temp_system_shall_be_possible_to_have_in_the_path_example_backup}.items() if v is not None})

async def get_backup_state(
    client: RWSClient,
    action: str | None = None,
) -> httpx.Response:
    """
    Get Backup State.

    Route: ``GET /ctrl/backup``
    Contraintes ABB: Not supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        action: Paramètre query. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 200.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD_REQUEST(400)

    Example:
        # curl --digest -u "Default User":robotics "http://localhost/ctrl/backup?action=backupstate"
    """
    return await client.get("/ctrl/backup", params={k: v for k, v in {"action": action}.items() if v is not None})

async def subscribe_on_backup_system_information(
    client: RWSClient,
    identifier: str | None = None,
    identifier_p: str | None = None,
) -> httpx.Response:
    """
    Subscribe on Backup System Information.

    Route: ``POST /subscription``
    Contraintes ABB: if the subscription is created during backup creation of the System (backup.log is in progress),the state will be in "pending". Not supported in bootserver mode. Not supported on virtual controller.

    Args:
        client: Instance RWSClient ouverte.
        identifier: Paramètre body. Optionnel.
        identifier_p: Paramètre body. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 201.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD_REQUEST(400) See

    Example:
        # only low priority subscription(-p=0) and medium priority subscription(-p=1) are allowed on this resource
    """
    return await client.post("/subscription", data={k: v for k, v in {"identifier": identifier, "identifier_p": identifier_p}.items() if v is not None})

async def get_backup_system_information(
    client: RWSClient,
    backup_path: str | None = None,
) -> httpx.Response:
    """
    Get backup system information.

    Route: ``GET /ctrl/backup/info/``
    Contraintes ABB: Not Supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        backup_path: Paramètre query. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 200.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: See

    Example:
        # curl --digest -u "Default User":robotics "http://localhost/ctrl/backup/info?backup-path=C:/Users/inshsal/Documents/Robot
    """
    return await client.get("/ctrl/backup/info/", params={k: v for k, v in {"backup_path": backup_path}.items() if v is not None})
