# This file is AUTO-GENERATED by utils/generator/main.py
# DO NOT EDIT MANUALLY — run the generator to regenerate.
#  Generator author: Clement RACINET
"""
RWS module: Controller Service → Operations on Clock Resource → Get Clock Resource

1:1 mirror of the ABB RobotWare 6 REST API.
Each function maps to exactly one HTTP endpoint.
No composed logic — see highlevel/ for wrappers.
"""
from __future__ import annotations

import httpx

from abb_rws_client.core.client import RWSClient


async def get_clock_resource(client: RWSClient) -> httpx.Response:
    """
    Get Clock Resource.

    Route: ``GET /ctrl/clock``
    ABB constraints: Not Supported in bootserver mode

    Args:
        client: Open RWSClient instance.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: NOT_FOUND(404)

    Example:
        ```python
        >>> await get_clock_resource(client)
        <Response [200]>
        ```
    """
    return await client.get("/ctrl/clock")

async def get_clock_actions(
    client: RWSClient,
    action: str | None = None,
) -> httpx.Response:
    """
    Get Clock Actions.

    Route: ``GET /ctrl/clock``
    ABB constraints: Not Supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        action: Query parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: NOT_FOUND(404) See

    Example:
        ```python
        >>> await get_clock_actions(client)
        <Response [200]>
        ```
    """
    return await client.get(
        "/ctrl/clock",
        params={k: v for k, v in {"action": action}.items() if v is not None},
    )

async def set_the_clock_of_the_controller(client: RWSClient) -> httpx.Response:
    """
    Set the Clock of the controller.

    Route: ``PUT /ctrl/clock``
    ABB constraints: Available only for RC Not Supported in bootserver mode

    Args:
        client: Open RWSClient instance.

    Returns:
        Raw HTTP response. Expected success: HTTP 204.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: UNAUTHORIZED(401), BAD_REQUEST(400), UNSUPPORTED_MEDIA(415), See

    Example:
        ```python
        >>> await set_the_clock_of_the_controller(client)
        <Response [204]>
        ```
    """
    return await client.put(
        "/ctrl/clock",
        data={},
    )

async def get_timezone_resource(client: RWSClient) -> httpx.Response:
    """
    Get timezone resource.

    Route: ``GET /ctrl/clock/timezone``
    ABB constraints: Available only for RC Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: See

    Example:
        ```python
        >>> await get_timezone_resource(client)
        <Response [200]>
        ```
    """
    return await client.get("/ctrl/clock/timezone")

async def get_timezone_actions(client: RWSClient) -> httpx.Response:
    """
    Get timezone actions.

    Route: ``GET /ctrl/clock/timezone?action=show``
    ABB constraints: Available only for RC Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: See

    Example:
        ```python
        >>> await get_timezone_actions(client)
        <Response [200]>
        ```
    """
    return await client.get(
        "/ctrl/clock/timezone",
        params={"action": "show"},
    )

async def set_the_time_zone(client: RWSClient) -> httpx.Response:
    """
    Set the time zone.

    Route: ``POST /ctrl/clock/timezone``
    ABB constraints: Available only for RC Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.

    Returns:
        Raw HTTP response. Expected success: HTTP 204.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: See

    Example:
        ```python
        >>> await set_the_time_zone(client)
        <Response [204]>
        ```
    """
    return await client.post(
        "/ctrl/clock/timezone",
        data={},
    )

async def get_time_server_resource(client: RWSClient) -> httpx.Response:
    """
    Get time server resource.

    Route: ``GET /ctrl/clock/timeserver``
    ABB constraints: Available only for RC Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: See

    Example:
        ```python
        >>> await get_time_server_resource(client)
        <Response [200]>
        ```
    """
    return await client.get("/ctrl/clock/timeserver")

async def get_time_server_actions(client: RWSClient) -> httpx.Response:
    """
    Get time server actions.

    Route: ``GET /ctrl/clock/timeserver?action=show``
    ABB constraints: Available only for RC Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: See

    Example:
        ```python
        >>> await get_time_server_actions(client)
        <Response [200]>
        ```
    """
    return await client.get(
        "/ctrl/clock/timeserver",
        params={"action": "show"},
    )

async def set_the_time_server(
    client: RWSClient,
    action: str | None = None,
) -> httpx.Response:
    """
    Set the time server.

    Route: ``POST /ctrl/clock/timeserver``
    ABB constraints: Available only for RC Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        action: Query parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 204.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: See

    Example:
        ```python
        >>> await set_the_time_server(client)
        <Response [204]>
        ```
    """
    return await client.post(
        "/ctrl/clock/timeserver",
        params={k: v for k, v in {"action": action}.items() if v is not None},
        data={},
    )

async def get_test_time_server(
    client: RWSClient,
    resource: str | None = None,
    server_ip: str | None = None,
) -> httpx.Response:
    """
    Test Time Server.

    Route: ``GET /ctrl/clock/timeserver``
    ABB constraints: Available only for RC Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        resource: Query parameter. Optional.
        server_ip: Query parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: See

    Example:
        ```python
        >>> await get_test_time_server(client)
        <Response [200]>
        ```
    """
    return await client.get(
        "/ctrl/clock/timeserver",
        params={
            k: v
            for k, v in {
                "resource": resource,
                "server_ip": server_ip
            }.items()
            if v is not None
        },
    )
