# This file is AUTO-GENERATED by contrib/generator/main.py
# DO NOT EDIT MANUALLY — run the generator to regenerate.
"""
RWS module : Controller Service → Operations on Identity Resource → Get Identity Resource

Miroir 1:1 de l'API REST ABB RobotWare 6.
Chaque fonction correspond à exactement un endpoint HTTP.
Aucune logique composée — voir highlevel/ pour les wrappers.
"""
from __future__ import annotations

import httpx

from abb_rws_client._core.client import RWSClient


async def get_identity_resource(client: RWSClient) -> httpx.Response:
    """
    Get Identity Resource.

    Route: ``GET /ctrl/identity``
    Contraintes ABB: Supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 200.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: NOT_FOUND(404) See

    Example:
        # curl --digest -u "Default User":robotics "http://localhost/ctrl/identity"
    """
    return await client.get("/ctrl/identity")

async def get_identity_actions(
    client: RWSClient,
    action: str | None = None,
) -> httpx.Response:
    """
    Get Identity Actions.

    Route: ``GET /ctrl/identity``
    Contraintes ABB: Supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        action: Paramètre query. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 200.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: NOT_FOUND(404) See

    Example:
        # curl --digest -u "Default User":robotics "http://localhost/ctrl/identity?action=show"
    """
    return await client.get("/ctrl/identity", params={k: v for k, v in {"action": action}.items() if v is not None})

async def set_the_identity_of_the_controller(client: RWSClient) -> httpx.Response:
    """
    Set the Identity of the controller.

    Route: ``PUT /ctrl/identity``
    Contraintes ABB: Supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 204.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: UNAUTHORIZED(401), BAD_REQUEST(400), UNSUPPORTED_MEDIA(415)

    Example:
        # Set the controller identity
    """
    return await client.put("/ctrl/identity")
