# This file is AUTO-GENERATED by contrib/generator/main.py
# DO NOT EDIT MANUALLY — run the generator to regenerate.
"""
RWS module : RobotWare Services → CFG Service → Get CFG resources

Miroir 1:1 de l'API REST ABB RobotWare 6.
Chaque fonction correspond à exactement un endpoint HTTP.
Aucune logique composée — voir highlevel/ pour les wrappers.
"""
from __future__ import annotations

import httpx

from abb_rws_client._core.client import RWSClient


async def get_cfg_resources(client: RWSClient) -> httpx.Response:
    """
    Get CFG resources.

    Route: ``GET /rw/cfg``
    Contraintes ABB: Not supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 200.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.

    Example:
        # curl --digest -u "Default User":robotics" "
    """
    return await client.get("/rw/cfg")

async def get_cfg_actions(
    client: RWSClient,
    action: str | None = None,
) -> httpx.Response:
    """
    Get CFG actions.

    Route: ``GET /rw/cfg``
    Contraintes ABB: Not supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        action: Paramètre query. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 200.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD_REQUEST(400)

    Example:
        # Retrieve actions on the CFG resource
    """
    return await client.get("/rw/cfg", params={k: v for k, v in {"action": action}.items() if v is not None})

async def validate_cfg_file(
    client: RWSClient,
    action: str | None = None,
) -> httpx.Response:
    """
    Validate CFG file.

    Route: ``POST /rw/cfg``
    Contraintes ABB: Not supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        action: Paramètre query. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 200.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD_REQUEST(400), UNSUPPORTED_MEDIA(415)

    Example:
        # curl --digest -u "Default User":robotics -d "filepath=$TEMP/a.cfg&action-type=add-with-reset" -X POST "http://localhost/
    """
    return await client.post("/rw/cfg", params={k: v for k, v in {"action": action}.items() if v is not None})

async def load_cfg_file(
    client: RWSClient,
    action: str | None = None,
) -> httpx.Response:
    """
    Load CFG file.

    Route: ``POST /rw/cfg``
    Contraintes ABB: Not supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        action: Paramètre query. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 204.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD_REQUEST(400)

    Example:
        # curl --digest -u "Default User":robotics -d "filepath=$TEMP/a.cfg&action-type=add-with-reset" -X POST "http://localhost/
    """
    return await client.post("/rw/cfg", params={k: v for k, v in {"action": action}.items() if v is not None})

async def validate_cfg_instance_before_delete(
    client: RWSClient,
    action: str | None = None,
    name: str | None = None,
) -> httpx.Response:
    """
    Validate CFG Instance before Delete.

    Route: ``POST /rw/cfg``
    Contraintes ABB: Not supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        action: Paramètre query. Optionnel.
        name: Paramètre body. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 204.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD_REQUEST(400), NOT_FOUND(404), see

    Example:
        # curl --digest -u "Default User":robotics -d "name=abc" -X POST "http://localhost/rw/cfg?action=validate-inst-at-del"
    """
    return await client.post("/rw/cfg", params={k: v for k, v in {"action": action}.items() if v is not None}, data={k: v for k, v in {"name": name}.items() if v is not None})

async def validate_cfg_instances(
    client: RWSClient,
    action: str | None = None,
    operation: str | None = None,
    cfgdomain: str | None = None,
    cfgtype: str | None = None,
    instances: str | None = None,
    instancescount: str | None = None,
) -> httpx.Response:
    """
    Validate CFG Instances.

    Route: ``POST /rw/cfg``
    Contraintes ABB: Not supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        action: Paramètre query. Optionnel.
        operation: Paramètre body. Optionnel.
        cfgdomain: Paramètre body. Optionnel.
        cfgtype: Paramètre body. Optionnel.
        instances: Paramètre body. Optionnel.
        instancescount: Paramètre body. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 204.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD_REQUEST(400), NOT_FOUND(404), see

    Example:
        # curl --digest -u "Default User":robotics -d "operation=1&cfgdomain=I/O&cfgtype=DeviceNetDevice&instances=TestingValid1&i
    """
    return await client.post("/rw/cfg", params={k: v for k, v in {"action": action}.items() if v is not None}, data={k: v for k, v in {"operation": operation, "cfgdomain": cfgdomain, "cfgtype": cfgtype, "instances": instances, "instancescount": instancescount}.items() if v is not None})

async def post_keyless_motor_on(
    client: RWSClient,
    action: str | None = None,
    state: str | None = None,
) -> httpx.Response:
    """
    Keyless motor ON.

    Route: ``POST /rw/cfg``
    Contraintes ABB: Not supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        action: Paramètre query. Optionnel.
        state: Paramètre body. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 204.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD_REQUEST(400) see

    Example:
        # curl --digest -u "Default User":robotics -d "state=run" -X POST "http://localhost/rw/cfg?action=keyless"
    """
    return await client.post("/rw/cfg", params={k: v for k, v in {"action": action}.items() if v is not None}, data={k: v for k, v in {"state": state}.items() if v is not None})

async def subscribe_on_cfg_changecount(
    client: RWSClient,
    identifier: str | None = None,
    identifier_p: str | None = None,
) -> httpx.Response:
    """
    Subscribe on cfg ChangeCount.

    Route: ``POST /subscription``
    Contraintes ABB: Not supported in bootserver mode.

    Args:
        client: Instance RWSClient ouverte.
        identifier: Paramètre body. Optionnel.
        identifier_p: Paramètre body. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 201.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD_REQUEST(400), UNSUPPORTED_MEDIA(415)

    Example:
        # Subscribe on cfg change count
    """
    return await client.post("/subscription", data={k: v for k, v in {"identifier": identifier, "identifier_p": identifier_p}.items() if v is not None})

async def get_cfg_domain_types(
    client: RWSClient,
    domain: str,
    start: str | None = None,
    limit: str | None = None,
) -> httpx.Response:
    """
    Get CFG Domain Types.

    Route: ``GET /rw/cfg/{domain}``
    Contraintes ABB: Not supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        domain: Paramètre de chemin URL.
        start: Paramètre query. Optionnel.
        limit: Paramètre query. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 200.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.

    Example:
        # curl --digest -u "Default User":robotics "http://localhost/rw/cfg/moc"
    """
    return await client.get(f"/rw/cfg/{domain}", params={k: v for k, v in {"start": start, "limit": limit}.items() if v is not None})

async def get_actions_on_cfg_domain(
    client: RWSClient,
    domain: str,
    action: str | None = None,
) -> httpx.Response:
    """
    Get Actions on a CFG domain.

    Route: ``GET /rw/cfg/{domain}``
    Contraintes ABB: CFG Mastership is handled internally if not explicit held by the client. Not supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        domain: Paramètre de chemin URL.
        action: Paramètre query. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 200.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD_REQUEST(400)

    Example:
        # Get actions supported by a CFG domain
    """
    return await client.get(f"/rw/cfg/{domain}", params={k: v for k, v in {"action": action}.items() if v is not None})

async def save_cfg_domain(
    client: RWSClient,
    domain: str,
    action: str | None = None,
) -> httpx.Response:
    """
    Save CFG domain.

    Route: ``POST /rw/cfg/{domain}``
    Contraintes ABB: Not supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        domain: Paramètre de chemin URL.
        action: Paramètre query. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 204.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD_REQUEST(400), FORBIDDEN(403), UNAUTHORIZED(401)

    Example:
        # Save the CFG domain to the given file
    """
    return await client.post(f"/rw/cfg/{domain}", params={k: v for k, v in {"action": action}.items() if v is not None})

async def reset_cfg_domain(
    client: RWSClient,
    domain: str,
    action: str | None = None,
) -> httpx.Response:
    """
    Reset CFG domain.

    Route: ``POST /rw/cfg/{domain}``
    Contraintes ABB: Not supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        domain: Paramètre de chemin URL.
        action: Paramètre query. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 200.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD_REQUEST(400)

    Example:
        # Remove all external instances in a CFG domain
    """
    return await client.post(f"/rw/cfg/{domain}", params={k: v for k, v in {"action": action}.items() if v is not None})

async def get_cfg_type(
    client: RWSClient,
    domain: str,
    type: str,
) -> httpx.Response:
    """
    Get CFG type.

    Route: ``GET /rw/cfg/{domain}/{type}``
    Contraintes ABB: Not supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        domain: Paramètre de chemin URL.
        type: Paramètre de chemin URL.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 200.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: NOT_FOUND(404)

    Example:
        # curl --digest -u "Default User":robotics "http://localhost/rw/cfg/eio/INDUSTRIAL_NETWORK"
    """
    return await client.get(f"/rw/cfg/{domain}/{type}")

async def get_all_attributes_of_the_given_domain(
    client: RWSClient,
    domain: str,
    type: str,
) -> httpx.Response:
    """
    Get all attributes of the given domain type.

    Route: ``GET /rw/cfg/{domain}/{type}/attributes``
    Contraintes ABB: Not supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        domain: Paramètre de chemin URL.
        type: Paramètre de chemin URL.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 200.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD_REQUEST(400)

    Example:
        # curl --digest -u "Default User":robotics "http://localhost/rw/cfg/eio/INDUSTRIAL_NETWORK/attributes"
    """
    return await client.get(f"/rw/cfg/{domain}/{type}/attributes")

async def get_all_instances_of_the_given_domain(
    client: RWSClient,
    domain: str,
    type: str,
) -> httpx.Response:
    """
    Get all instances of the given domain type.

    Route: ``GET /rw/cfg/{domain}/{type}/instances``
    Contraintes ABB: Not supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        domain: Paramètre de chemin URL.
        type: Paramètre de chemin URL.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 200.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD_REQUEST(400)

    Example:
        # curl --digest -u "Default User":robotics "http://localhost/rw/cfg/eio/EIO_BUS/instances"
    """
    return await client.get(f"/rw/cfg/{domain}/{type}/instances")

async def get_actions_on_cfg_instances(
    client: RWSClient,
    domain: str,
    type: str,
    action: str | None = None,
) -> httpx.Response:
    """
    Get actions on CFG instances.

    Route: ``GET /rw/cfg/{domain}/{type}/instances``
    Contraintes ABB: Not supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        domain: Paramètre de chemin URL.
        type: Paramètre de chemin URL.
        action: Paramètre query. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 200.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD_REQUEST(400)

    Example:
        # curl --digest -u "Default User":robotics "http://localhost/rw/cfg/eio/INDUSTRIAL_NETWORK/instances?action=show"
    """
    return await client.get(f"/rw/cfg/{domain}/{type}/instances", params={k: v for k, v in {"action": action}.items() if v is not None})

async def reset_cfg_instances(
    client: RWSClient,
    domain: str,
    type: str,
    action: str | None = None,
) -> httpx.Response:
    """
    Reset CFG instances.

    Route: ``POST /rw/cfg/{domain}/{type}/instances``
    Contraintes ABB: Not supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        domain: Paramètre de chemin URL.
        type: Paramètre de chemin URL.
        action: Paramètre query. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 204.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD_REQUEST(400)

    Example:
        # Reset CFG instances
    """
    return await client.post(f"/rw/cfg/{domain}/{type}/instances", params={k: v for k, v in {"action": action}.items() if v is not None})

async def create_default_cfg_instance(
    client: RWSClient,
    domain: str,
    type: str,
    action: str | None = None,
) -> httpx.Response:
    """
    Create default CFG instance.

    Route: ``POST /rw/cfg/{domain}/{type}/instances``
    Contraintes ABB: Use location header to fetch information about newly created resource. Not supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        domain: Paramètre de chemin URL.
        type: Paramètre de chemin URL.
        action: Paramètre query. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 201.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD_REQUEST(400)

    Example:
        # Create default CFG instance
    """
    return await client.post(f"/rw/cfg/{domain}/{type}/instances", params={k: v for k, v in {"action": action}.items() if v is not None})

async def get_cfg_instance(
    client: RWSClient,
    domain: str,
    type: str,
    instance_name: str,
) -> httpx.Response:
    """
    Get CFG instance.

    Route: ``GET /rw/cfg/{domain}/{type}/instances/{instance name}``
    Contraintes ABB: Not supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        domain: Paramètre de chemin URL.
        type: Paramètre de chemin URL.
        instance_name: Paramètre de chemin URL.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 200.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD_REQUEST(400)

    Example:
        # curl --digest -u "Default User":robotics" "
    """
    return await client.get(f"/rw/cfg/{domain}/{type}/instances/{instance_name}")

async def get_cfg_instance_actions(
    client: RWSClient,
    domain: str,
    type: str,
    instance: str,
    action: str | None = None,
) -> httpx.Response:
    """
    Get CFG instance actions.

    Route: ``GET /rw/cfg/{domain}/{type}/instances/{instance}``
    Contraintes ABB: Not supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        domain: Paramètre de chemin URL.
        type: Paramètre de chemin URL.
        instance: Paramètre de chemin URL.
        action: Paramètre query. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 200.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD_REQUEST(400)

    Example:
        # curl --digest -u "Default User":robotics" "
    """
    return await client.get(f"/rw/cfg/{domain}/{type}/instances/{instance}", params={k: v for k, v in {"action": action}.items() if v is not None})

async def update_cfg_instance(
    client: RWSClient,
    domain: str,
    type: str,
    instance: str,
    action: str | None = None,
    attribute_name: str | None = None,
) -> httpx.Response:
    """
    Update CFG instance.

    Route: ``POST /rw/cfg/{domain}/{type}/instances/{instance}``
    Contraintes ABB: Not supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        domain: Paramètre de chemin URL.
        type: Paramètre de chemin URL.
        instance: Paramètre de chemin URL.
        action: Paramètre query. Optionnel.
        attribute_name: Paramètre body. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 204.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: UNSUPPORTED_MEDIA(415), BAD_REQUEST(400)

    Example:
        # Update one or more attributes
    """
    return await client.post(f"/rw/cfg/{domain}/{type}/instances/{instance}", params={k: v for k, v in {"action": action}.items() if v is not None}, data={k: v for k, v in {"attribute_name": attribute_name}.items() if v is not None})

async def delete_cfg_instance(
    client: RWSClient,
    domain: str,
    type: str,
    instance: str,
) -> httpx.Response:
    """
    Delete CFG instance.

    Route: ``DELETE /rw/cfg/{domain}/{type}/instances/{instance}``
    Contraintes ABB: Not supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        domain: Paramètre de chemin URL.
        type: Paramètre de chemin URL.
        instance: Paramètre de chemin URL.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 204.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD_REQUEST(400)

    Example:
        # Delete CFG instance
    """
    return await client.delete(f"/rw/cfg/{domain}/{type}/instances/{instance}")
