# This file is AUTO-GENERATED by contrib/generator/main.py
# DO NOT EDIT MANUALLY — run the generator to regenerate.
#  Generator author: Clément RACINET
"""
RWS module: RobotWare Services → Devices service → Devices tree information

1:1 mirror of the ABB RobotWare 6 REST API.
Each function maps to exactly one HTTP endpoint.
No composed logic — see highlevel/ for wrappers.
"""
from __future__ import annotations

import httpx

from abb_rws_client._core.client import RWSClient


async def get_devices_tree_information(
    client: RWSClient,
    lang: str | None = None,
) -> httpx.Response:
    """
    Devices tree information.

    Route: ``GET /rw/devices``
    ABB constraints: Not supported in bootserver mode.

    Args:
        client: Open RWSClient instance.
        lang: Query parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD_REQUEST(400), NOT_FOUND(404)

    Example:
        # curl --digest -u "Default User":robotics "http://localhost/rw/devices"
    """
    return await client.get(
        "/rw/devices",
        params={k: v for k, v in {"lang": lang}.items() if v is not None},
    )
