# This file is AUTO-GENERATED by contrib/generator/main.py
# DO NOT EDIT MANUALLY — run the generator to regenerate.
"""
RWS module : RobotWare Services → Devices service → Devices tree information

Miroir 1:1 de l'API REST ABB RobotWare 6.
Chaque fonction correspond à exactement un endpoint HTTP.
Aucune logique composée — voir highlevel/ pour les wrappers.
"""
from __future__ import annotations

import httpx

from abb_rws_client._core.client import RWSClient


async def get_devices_tree_information(
    client: RWSClient,
    lang: str | None = None,
) -> httpx.Response:
    """
    Devices tree information.

    Route: ``GET /rw/devices``
    Contraintes ABB: Not supported in bootserver mode.

    Args:
        client: Instance RWSClient ouverte.
        lang: Paramètre query. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 200.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD_REQUEST(400), NOT_FOUND(404)

    Example:
        # curl --digest -u "Default User":robotics "http://localhost/rw/devices"
    """
    return await client.get("/rw/devices", params={k: v for k, v in {"lang": lang}.items() if v is not None})
