# This file is AUTO-GENERATED by contrib/generator/main.py
# DO NOT EDIT MANUALLY — run the generator to regenerate.
"""
RWS module : RobotWare Services → DIPC service → Get DIPC Resources

Miroir 1:1 de l'API REST ABB RobotWare 6.
Chaque fonction correspond à exactement un endpoint HTTP.
Aucune logique composée — voir highlevel/ pour les wrappers.
"""
from __future__ import annotations

import httpx

from abb_rws_client._core.client import RWSClient


async def get_dipc_resources(client: RWSClient) -> httpx.Response:
    """
    Get DIPC Resources.

    Route: ``GET /rw/dipc``
    Contraintes ABB: Not supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 200.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD_REQUEST(400)

    Example:
        # curl --digest -u "Default User":robotics "http://localhost/rw/dipc"
    """
    return await client.get("/rw/dipc")

async def get_dipc_actions(client: RWSClient) -> httpx.Response:
    """
    Get DIPC Actions.

    Route: ``GET /rw/dipc``
    Contraintes ABB: Not supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 200.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD_REQUEST(400)

    Example:
        # curl --digest -u "Default User":robotics "http://localhost/rw/dipc?action=show"
    """
    return await client.get("/rw/dipc")

async def create_queue(
    client: RWSClient,
    action: str | None = None,
) -> httpx.Response:
    """
    Create a queue.

    Route: ``POST /rw/dipc``
    Contraintes ABB: Not supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        action: Paramètre query. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 201.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD_REQUEST(400)

    Example:
        # Restart controller with the specified mode
    """
    return await client.post("/rw/dipc", params={k: v for k, v in {"action": action}.items() if v is not None})

async def get_dipc_queue(
    client: RWSClient,
    queue_name: str,
) -> httpx.Response:
    """
    Get DIPC Queue.

    Route: ``GET /rw/dipc/{queue-name}``
    Contraintes ABB: Not supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        queue_name: Paramètre de chemin URL.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 200.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD REQUEST(400)

    Example:
        # curl --digest -u "Default User":robotics "http://localhost/rw/dipc/testq"
    """
    return await client.get(f"/rw/dipc/{queue_name}")

async def get_dipc_queue_actions(
    client: RWSClient,
    queue_name: str,
    action: str | None = None,
) -> httpx.Response:
    """
    Get DIPC Queue Actions.

    Route: ``GET /rw/dipc/{queue-name}``
    Contraintes ABB: Not supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        queue_name: Paramètre de chemin URL.
        action: Paramètre query. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 200.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD REQUEST(400)

    Example:
        # curl --digest -u "Default User":robotics -X DELETE "http://localhost/rw/dipc/testq?action=show"
    """
    return await client.get(f"/rw/dipc/{queue_name}", params={k: v for k, v in {"action": action}.items() if v is not None})

async def post_send_message(
    client: RWSClient,
    queue_name: str,
    action: str | None = None,
) -> httpx.Response:
    """
    Send message.

    Route: ``POST /rw/dipc/{queue-name}``
    Contraintes ABB: Not supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        queue_name: Paramètre de chemin URL.
        action: Paramètre query. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 200.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD REQUEST(400)

    Example:
        # Send message to queue
    """
    return await client.post(f"/rw/dipc/{queue_name}", params={k: v for k, v in {"action": action}.items() if v is not None})

async def get_read_message(
    client: RWSClient,
    queue_name: str,
    action: str | None = None,
    timeout: str | None = None,
) -> httpx.Response:
    """
    Read message.

    Route: ``GET /rw/dipc/{queue-name}``
    Contraintes ABB: Not supported in bootserver mode.

    Args:
        client: Instance RWSClient ouverte.
        queue_name: Paramètre de chemin URL.
        action: Paramètre query. Optionnel.
        timeout: Paramètre query. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 200.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD_REQUEST (400)

    Example:
        # curl --digest -u "Default User":robotics "http://localhost/rw/dipc/testq?action=dipc-read"
    """
    return await client.get(f"/rw/dipc/{queue_name}", params={k: v for k, v in {"action": action, "timeout": timeout}.items() if v is not None})

async def delete_dipc_queue(
    client: RWSClient,
    queue_name: str,
) -> httpx.Response:
    """
    Delete DIPC Queue.

    Route: ``DELETE /rw/dipc/{queue-name}``
    Contraintes ABB: Not supported in bootserver mode User can delete DIPC queue only if the queue is created by the same user

    Args:
        client: Instance RWSClient ouverte.
        queue_name: Paramètre de chemin URL.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 204.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD REQUEST(400)

    Example:
        # Delete a queue
    """
    return await client.delete(f"/rw/dipc/{queue_name}")

async def subscribe_dipc_queue(
    client: RWSClient,
    identifier: str | None = None,
    identifier_p: str | None = None,
) -> httpx.Response:
    """
    Subscribe DIPC Queue.

    Route: ``POST /subscription``
    Contraintes ABB: Not supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        identifier: Paramètre body. Optionnel.
        identifier_p: Paramètre body. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 201.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD REQUEST(400)

    Example:
        # Subscribe on queue
    """
    return await client.post("/subscription", data={k: v for k, v in {"identifier": identifier, "identifier_p": identifier_p}.items() if v is not None})

async def subscribe_dipc_queue_without_reading_message(
    client: RWSClient,
    identifier: str | None = None,
    identifier_p: str | None = None,
) -> httpx.Response:
    """
    Subscribe DIPC Queue without reading message.

    Route: ``POST /subscription``

    Args:
        client: Instance RWSClient ouverte.
        identifier: Paramètre body. Optionnel.
        identifier_p: Paramètre body. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 201.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD REQUEST(400)

    Example:
        # Subscribe on queue
    """
    return await client.post("/subscription", data={k: v for k, v in {"identifier": identifier, "identifier_p": identifier_p}.items() if v is not None})
