# This file is AUTO-GENERATED by contrib/generator/main.py
# DO NOT EDIT MANUALLY — run the generator to regenerate.
"""
RWS module : File Service → Get File Service Resources

Miroir 1:1 de l'API REST ABB RobotWare 6.
Chaque fonction correspond à exactement un endpoint HTTP.
Aucune logique composée — voir highlevel/ pour les wrappers.
"""
from __future__ import annotations

import httpx

from abb_rws_client._core.client import RWSClient


async def get_file_service_resources(client: RWSClient) -> httpx.Response:
    """
    Get File Service Resources.

    Route: ``GET /fileservice``
    Contraintes ABB: Though root supports environment variables these are not listed in the returned response. Environment variables are only allowed directly under the root URI i.e. /fileservice/$home Supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 200.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: UNAUTHORIZED(401),NOT_FOUND(404)

    Example:
        # Get a list of root resources
    """
    return await client.get("/fileservice")

async def get_directory_listing_of_resources(
    client: RWSClient,
    environment_variable_device: str,
    directory: str,
) -> httpx.Response:
    """
    Get Directory listing of resources.

    Route: ``GET /fileservice/{environment_variable|device}/{directory}``
    Contraintes ABB: Supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        environment_variable_device: Paramètre de chemin URL.
        directory: Paramètre de chemin URL.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 200.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: UNAUTHORIZED(401), NOT_FOUND(404), BAD_REQUEST(400) See

    Example:
        # Directory Listing
    """
    return await client.get(f"/fileservice/{environment_variable_device}/{directory}")

async def get_directory_actions(
    client: RWSClient,
    device: str,
    directory: str,
    action: str | None = None,
) -> httpx.Response:
    """
    Get Directory Actions.

    Route: ``GET /fileservice/{device}|{directory}``
    Contraintes ABB: Supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        device: Paramètre de chemin URL.
        directory: Paramètre de chemin URL.
        action: Paramètre query. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 200.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD_REQUEST(400) See

    Example:
        # Get actions on directory
    """
    return await client.get(f"/fileservice/{device}|{directory}", params={k: v for k, v in {"action": action}.items() if v is not None})

async def create_directory(
    client: RWSClient,
    device_environment_variable: str,
    directory: str,
) -> httpx.Response:
    """
    Create a directory.

    Route: ``POST /fileservice/{device|environment_variable}/{directory}``
    Contraintes ABB: Only relative path are allowed for "*fs-newname*". Absolute paths are not supported The fs-newname can take nested directory structure e.g. fs-newname=parentdir/subdir will create both the directories if they don't exist i.e. subdir under parentdir Supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        device_environment_variable: Paramètre de chemin URL.
        directory: Paramètre de chemin URL.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 201.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: UNAUTHORIZED(401), BAD_REQUEST(400), UNSUPPORTED_MEDIA(415),

    Example:
        # Create a new directory
    """
    return await client.post(f"/fileservice/{device_environment_variable}/{directory}")

async def post_rename_directory(
    client: RWSClient,
    device_environment_variable: str,
    directory: str,
) -> httpx.Response:
    """
    Rename a directory.

    Route: ``POST /fileservice/{device|environment_variable}/{directory}``
    Contraintes ABB: Supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        device_environment_variable: Paramètre de chemin URL.
        directory: Paramètre de chemin URL.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 200.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: UNAUTHORIZED(401), NOT_FOUND(404), BAD_REQUEST(400), UNSUPPORTED_MEDIA(415), METHOD_NOT_ALLOWED(405)

    Example:
        # Rename a directory
    """
    return await client.post(f"/fileservice/{device_environment_variable}/{directory}")

async def post_copy_directory(
    client: RWSClient,
    device_environment_variable: str,
    directory: str,
) -> httpx.Response:
    """
    Copy a directory.

    Route: ``POST /fileservice/{device|environment_variable}/{directory}``
    Contraintes ABB: The value for fs-newname can either be absolute or relative. It is differentiated based on whether the value has a leading slash (absolute) or not (relative). Note: when absolute paths are used, it should start from /fileservice e.g. Absolute path : fs-newname=/fileservice/$home/copydir2 Relative...

    Args:
        client: Instance RWSClient ouverte.
        device_environment_variable: Paramètre de chemin URL.
        directory: Paramètre de chemin URL.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 204.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: UNAUTHORIZED(401), NOT_FOUND(404), BAD_REQUEST(400), UNSUPPORTED_MEDIA(415), CONFLICT(409)

    Example:
        # Create a copy of a directory
    """
    return await client.post(f"/fileservice/{device_environment_variable}/{directory}")

async def delete_directory(
    client: RWSClient,
    device_environment_variable: str,
    directory: str,
) -> httpx.Response:
    """
    Delete a directory.

    Route: ``DELETE /fileservice/{device|environment_variable}/{directory}``
    Contraintes ABB: Supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        device_environment_variable: Paramètre de chemin URL.
        directory: Paramètre de chemin URL.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 204.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: UNAUTHORIZED(401), NOT_FOUND(404), BAD_REQUEST(400), METHOD_NOT_ALLOWED(405)

    Example:
        # Delate a directory
    """
    return await client.delete(f"/fileservice/{device_environment_variable}/{directory}")

async def get_file(
    client: RWSClient,
    device: str,
    directory: str,
    file: str,
) -> httpx.Response:
    """
    Get a file.

    Route: ``GET /fileservice/{device}|{directory}/{file}``
    Contraintes ABB: Supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        device: Paramètre de chemin URL.
        directory: Paramètre de chemin URL.
        file: Paramètre de chemin URL.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 200.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: UNAUTHORIZED(401), NOT_FOUND(404),

    Example:
        # Get a file.
    """
    return await client.get(f"/fileservice/{device}|{directory}/{file}")

async def get_file_actions(
    client: RWSClient,
    device: str,
    directory: str,
    file: str,
    action: str | None = None,
) -> httpx.Response:
    """
    Get File Actions.

    Route: ``GET /fileservice/{device}|{directory}/{file}``
    Contraintes ABB: Supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        device: Paramètre de chemin URL.
        directory: Paramètre de chemin URL.
        file: Paramètre de chemin URL.
        action: Paramètre query. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 200.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: UNAUTHORIZED(401), NOT_FOUND(404), See

    Example:
        # Get actions on a file.
    """
    return await client.get(f"/fileservice/{device}|{directory}/{file}", params={k: v for k, v in {"action": action}.items() if v is not None})

async def post_rename_file(
    client: RWSClient,
    device_environment_variable_directory: str,
    file: str,
) -> httpx.Response:
    """
    Rename a file.

    Route: ``POST /fileservice/{device|environment_variable|directory}/{file}``
    Contraintes ABB: Supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        device_environment_variable_directory: Paramètre de chemin URL.
        file: Paramètre de chemin URL.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 204.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: UNAUTHORIZED(401), NOT_FOUND(404), BAD_REQUEST(400), UNSUPPORTED_MEDIA(415)

    Example:
        # Rename a file
    """
    return await client.post(f"/fileservice/{device_environment_variable_directory}/{file}")

async def create_copy_of_file(
    client: RWSClient,
    device_environment_variable: str,
    filename: str,
) -> httpx.Response:
    """
    Create a copy of a file.

    Route: ``POST /fileservice/{device|environment_variable}/{filename}``
    Contraintes ABB: The value for fs-newname can either be absolute or relative. It is differentiated based on the whether the value has a leading slash (absolute) or not (relative). Note: when absolute paths are used, it should start from /fileservice e.g. Absolute path : fs-newname=/fileservice/$home/copyfile2.txt...

    Args:
        client: Instance RWSClient ouverte.
        device_environment_variable: Paramètre de chemin URL.
        filename: Paramètre de chemin URL.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 204.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: UNAUTHORIZED(401), NOT_FOUND(404), BAD_REQUEST(400), UNSUPPORTED_MEDIA(415), CONFLICT(409)

    Example:
        # Create a copy of a file
    """
    return await client.post(f"/fileservice/{device_environment_variable}/{filename}")

async def put_upload_file(
    client: RWSClient,
    device_environment_variable_directory: str,
    file: str,
) -> httpx.Response:
    """
    Upload a file.

    Route: ``PUT /fileservice/{device|environment_variable|directory}/{file}``
    Contraintes ABB: If the file exists, the file is overwritten with the specified content else a new file with the given name is created. Supported in bootserver mode Maximum supported file size is less than 800MB.

    Args:
        client: Instance RWSClient ouverte.
        device_environment_variable_directory: Paramètre de chemin URL.
        file: Paramètre de chemin URL.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 200.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: UNAUTHORIZED(401), NOT_FOUND(404), FORBIDDEN(403), BAD_REQUEST(400)

    Example:
        # Upload a file
    """
    return await client.put(f"/fileservice/{device_environment_variable_directory}/{file}")

async def delete_file(
    client: RWSClient,
    device_environment_variable_directory: str,
    file: str,
) -> httpx.Response:
    """
    Delete a file.

    Route: ``DELETE /fileservice/{device|environment_variable|directory}/{file}``
    Contraintes ABB: Supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        device_environment_variable_directory: Paramètre de chemin URL.
        file: Paramètre de chemin URL.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 204.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: UNAUTHORIZED(401), NOT_FOUND(404), BAD_REQUEST(400),METHOD_NOT_ALLOWED(405)

    Example:
        # Delete a file
    """
    return await client.delete(f"/fileservice/{device_environment_variable_directory}/{file}")

async def get_file_meta_data(
    client: RWSClient,
    device_environment_variable_directory: str,
    file: str,
) -> httpx.Response:
    """
    Get file Meta data.

    Route: ``HEAD /fileservice/{device|environment_variable|directory}/{file}``
    Contraintes ABB: Supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        device_environment_variable_directory: Paramètre de chemin URL.
        file: Paramètre de chemin URL.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 204.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: UNAUTHORIZED(401), NOT_FOUND(404), See

    Example:
        # Delete a file
    """
    return await client.head(f"/fileservice/{device_environment_variable_directory}/{file}")
