# This file is AUTO-GENERATED by contrib/generator/main.py
# DO NOT EDIT MANUALLY — run the generator to regenerate.
"""
RWS module : RobotWare Services → Mastership service → Get Mastership Resources

Miroir 1:1 de l'API REST ABB RobotWare 6.
Chaque fonction correspond à exactement un endpoint HTTP.
Aucune logique composée — voir highlevel/ pour les wrappers.
"""
from __future__ import annotations

import httpx

from abb_rws_client._core.client import RWSClient


async def get_mastership_resources(client: RWSClient) -> httpx.Response:
    """
    Get Mastership Resources.

    Route: ``GET /rw/mastership``
    Contraintes ABB: Not supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 200.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD_REQUEST(400)

    Example:
        # curl --digest -u "Default User":robotics "http://localhost/rw/mastership"
    """
    return await client.get("/rw/mastership")

async def get_mastership_actions(
    client: RWSClient,
    action: str | None = None,
) -> httpx.Response:
    """
    Get Mastership Actions.

    Route: ``GET /rw/mastership``
    Contraintes ABB: Not supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        action: Paramètre query. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 200.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD_REQUEST(400)

    Example:
        # curl --digest -u "Default User":robotics "http://localhost/rw/mastership?action=show"
    """
    return await client.get("/rw/mastership", params={k: v for k, v in {"action": action}.items() if v is not None})

async def post_mastership_request(
    client: RWSClient,
    action: str | None = None,
) -> httpx.Response:
    """
    Mastership request.

    Route: ``POST /rw/mastership``
    Contraintes ABB: Not supported in bootserver mode In manual mode, mastership can be gained after getting RMMP.

    Args:
        client: Instance RWSClient ouverte.
        action: Paramètre query. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 204.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD_REQUEST(400)

    Example:
        # Request mastership on all domains
    """
    return await client.post("/rw/mastership", params={k: v for k, v in {"action": action}.items() if v is not None})

async def post_mastership_release(
    client: RWSClient,
    action: str | None = None,
) -> httpx.Response:
    """
    Mastership release.

    Route: ``POST /rw/mastership``
    Contraintes ABB: Not supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        action: Paramètre query. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 204.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD_REQUEST(400)

    Example:
        # Release mastership on all domains
    """
    return await client.post("/rw/mastership", params={k: v for k, v in {"action": action}.items() if v is not None})

async def post_mastership_subscribe(
    client: RWSClient,
    identifier: str | None = None,
    identifier_p: str | None = None,
) -> httpx.Response:
    """
    Mastership Subscribe.

    Route: ``POST /subscription``
    Contraintes ABB: Not supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        identifier: Paramètre body. Optionnel.
        identifier_p: Paramètre body. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 201.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD_REQUEST(400)

    Example:
        # Subscribe on mastership state changes
    """
    return await client.post("/subscription", data={k: v for k, v in {"identifier": identifier, "identifier_p": identifier_p}.items() if v is not None})

async def get_mastership_domain(
    client: RWSClient,
    domain_name: str,
) -> httpx.Response:
    """
    Get Mastership Domain.

    Route: ``GET /rw/mastership/{domain-name}``
    Contraintes ABB: Not supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        domain_name: Paramètre de chemin URL.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 200.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD_REQUEST(400)

    Example:
        # curl --digest -u "Default User":robotics "http://localhost/rw/mastership/cfg"
    """
    return await client.get(f"/rw/mastership/{domain_name}")

async def get_mastership_domain_actions(
    client: RWSClient,
    domain_name: str,
    action: str | None = None,
) -> httpx.Response:
    """
    Get Mastership Domain Actions.

    Route: ``GET /rw/mastership/{domain-name}``
    Contraintes ABB: Not supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        domain_name: Paramètre de chemin URL.
        action: Paramètre query. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 200.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD_REQUEST(400)

    Example:
        # curl --digest -u "Default User":robotics "http://localhost/rw/mastership/cfg?action=show"
    """
    return await client.get(f"/rw/mastership/{domain_name}", params={k: v for k, v in {"action": action}.items() if v is not None})

async def post_mastership_domain_request(
    client: RWSClient,
    domain: str,
    action: str | None = None,
) -> httpx.Response:
    """
    Mastership domain request.

    Route: ``POST /rw/mastership/{domain}``
    Contraintes ABB: Not supported in bootserver mode In manual mode, mastership can be gained after getting RMMP.

    Args:
        client: Instance RWSClient ouverte.
        domain: Paramètre de chemin URL.
        action: Paramètre query. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 204.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: NOT_FOUND(404)

    Example:
        # Request mastership on cfg domain
    """
    return await client.post(f"/rw/mastership/{domain}", params={k: v for k, v in {"action": action}.items() if v is not None})

async def post_mastership_domain_release(
    client: RWSClient,
    domain: str,
    action: str | None = None,
) -> httpx.Response:
    """
    Mastership Domain release.

    Route: ``POST /rw/mastership/{domain}``
    Contraintes ABB: Not supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        domain: Paramètre de chemin URL.
        action: Paramètre query. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 204.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: NOT_FOUND(404)

    Example:
        # Release mastership on cfg domain
    """
    return await client.post(f"/rw/mastership/{domain}", params={k: v for k, v in {"action": action}.items() if v is not None})

async def post_mastership_domain_subscribe(
    client: RWSClient,
    identifier: str | None = None,
    identifier_p: str | None = None,
) -> httpx.Response:
    """
    Mastership Domain Subscribe.

    Route: ``POST /subscription``
    Contraintes ABB: Not supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        identifier: Paramètre body. Optionnel.
        identifier_p: Paramètre body. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 201.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD_REQUEST(400)

    Example:
        # Subscribe on cfg domain for changes
    """
    return await client.post("/subscription", data={k: v for k, v in {"identifier": identifier, "identifier_p": identifier_p}.items() if v is not None})
