# This file is AUTO-GENERATED by contrib/generator/main.py
# DO NOT EDIT MANUALLY — run the generator to regenerate.
#  Generator author: Clément RACINET
"""
RWS module: Operations on IO Profinet Device → Get profinet I/O device read record implicit da...

1:1 mirror of the ABB RobotWare 6 REST API.
Each function maps to exactly one HTTP endpoint.
No composed logic — see highlevel/ for wrappers.
"""
from __future__ import annotations

import httpx

from abb_rws_client._core.client import RWSClient


async def get_profinet_device_read_record_implicit_data(
    client: RWSClient,
    network: str,
    device: str,
    slot: str | None = None,
    subslot: str | None = None,
    index: str | None = None,
    datalength: str | None = None,
    vendorid: str | None = None,
    deviceid: str | None = None,
) -> httpx.Response:
    """
    Get profinet I/O device read record implicit data from device in profinet network.

    Route: ``GET rw/iosystem/devices/{network}/{device}/implicitdata``
    ABB constraints: Not supported in bootserver mode.

    Args:
        client: Open RWSClient instance.
        network: URL path parameter.
        device: URL path parameter.
        slot: Query parameter. Optional.
        subslot: Query parameter. Optional.
        index: Query parameter. Optional.
        datalength: Query parameter. Optional.
        vendorid: Query parameter. Optional.
        deviceid: Query parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: Bad Request(406)

    Example:
        # curl --digest -u "Default User":robotics
            "http://localhost/rw/iosystem/devices/{profinet}/{pnet}/implicitdata"
    """
    return await client.get(
        f"rw/iosystem/devices/{network}/{device}/implicitdata",
        params={
            k: v
            for k, v in {
                "slot": slot,
                "subslot": subslot,
                "index": index,
                "datalength": datalength,
                "vendorid": vendorid,
                "deviceid": deviceid
            }.items()
            if v is not None
        },
    )

async def post_read_record_implicit_data_from_device_in(
    client: RWSClient,
    network: str,
    device: str,
    slot: str | None = None,
    subslot: str | None = None,
    index: str | None = None,
    datalength: str | None = None,
    vendorid: str | None = None,
    deviceid: str | None = None,
    ip: str | None = None,
) -> httpx.Response:
    """
    Read record implicit data from device in profinet network.

    Route: ``POST rw/iosystem/devices/{network}/{device}/implicitdata``
    ABB constraints: Not supported in bootserver mode.

    Args:
        client: Open RWSClient instance.
        network: URL path parameter.
        device: URL path parameter.
        slot: Body parameter. Optional.
        subslot: Body parameter. Optional.
        index: Body parameter. Optional.
        datalength: Body parameter. Optional.
        vendorid: Body parameter. Optional.
        deviceid: Body parameter. Optional.
        ip: Body parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: NOT_ACCEPTABLE(406)

    Example:
        # curl --digest -u "Default User":robotics -d
            "slot=1&subslot=2&index=2&datalength=60&vendorid=42&deviceid=787&ip=127.1.1.
    """
    return await client.post(
        f"rw/iosystem/devices/{network}/{device}/implicitdata",
        data={
            k: v
            for k, v in {
                "slot": slot,
                "subslot": subslot,
                "index": index,
                "datalength": datalength,
                "vendorid": vendorid,
                "deviceid": deviceid,
                "ip": ip
            }.items()
            if v is not None
        },
    )

async def get_forms(
    client: RWSClient,
    network: str,
    device: str,
) -> httpx.Response:
    """
    Get forms.

    Route: ``OPTIONS rw/iosystem/devices/{network}/{device}/implicitdata``
    ABB constraints: Not supported in bootserver mode.

    Args:
        client: Open RWSClient instance.
        network: URL path parameter.
        device: URL path parameter.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: NOT_ACCEPTABLE(406) See

    Example:
        # curl --digest -u "Default User":robotics -X OPTIONS
            "http://localhost/rw/iosystem/devices/PROFINET/PN_Internal_Device/im
    """
    return await client.options(f"rw/iosystem/devices/{network}/{device}/implicitdata")

async def get_profinet_device_read_record_data(
    client: RWSClient,
    network: str,
    device: str,
    slot: str | None = None,
    subslot: str | None = None,
    index: str | None = None,
    datalength: str | None = None,
) -> httpx.Response:
    """
    Get profinet I/O device read record data.

    Route: ``GET rw/iosystem/devices/{network}/{device}/explicitdata``
    ABB constraints: Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        network: URL path parameter.
        device: URL path parameter.
        slot: Query parameter. Optional.
        subslot: Query parameter. Optional.
        index: Query parameter. Optional.
        datalength: Query parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: NOT_ACCEPTABLE(406)

    Example:
        # curl --digest -u "Default User":robotics
            "http://localhost/rw/iosystem/devices/PROFINET/PN_Internal_Device/explicitdata"
    """
    return await client.get(
        f"rw/iosystem/devices/{network}/{device}/explicitdata",
        params={
            k: v
            for k, v in {
                "slot": slot,
                "subslot": subslot,
                "index": index,
                "datalength": datalength
            }.items()
            if v is not None
        },
    )

async def get_profinet_device_read_record_data_2(
    client: RWSClient,
    network: str,
    device: str,
    slot: str | None = None,
    subslot: str | None = None,
    index: str | None = None,
    datalength: str | None = None,
) -> httpx.Response:
    """
    Get profinet I/O device read record data.

    Route: ``POST rw/iosystem/devices/{network}/{device}/explicitdata``
    ABB constraints: Not supported in bootserver mode.

    Args:
        client: Open RWSClient instance.
        network: URL path parameter.
        device: URL path parameter.
        slot: Body parameter. Optional.
        subslot: Body parameter. Optional.
        index: Body parameter. Optional.
        datalength: Body parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: NOT_ACCEPTABLE(406)

    Example:
        # curl --digest -u "Default User":robotics -d "slot=1&subslot=2&index=2&datalength=60" -X
            POST "http://localhost/rw/iosyst
    """
    return await client.post(
        f"rw/iosystem/devices/{network}/{device}/explicitdata",
        data={
            k: v
            for k, v in {
                "slot": slot,
                "subslot": subslot,
                "index": index,
                "datalength": datalength
            }.items()
            if v is not None
        },
    )

async def get_forms_2(
    client: RWSClient,
    network: str,
    device: str,
) -> httpx.Response:
    """
    Get Forms.

    Route: ``OPTIONS rw/iosystem/devices/{network}/{device}/explicitdata``
    ABB constraints: Not supported in bootserver mode.

    Args:
        client: Open RWSClient instance.
        network: URL path parameter.
        device: URL path parameter.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: See

    Example:
        # curl --digest -u "Default User":robotics -X OPTIONS
            "http://localhost/rw/iosystem/devices/PROFINET/PN_Internal_Device/ex
    """
    return await client.options(f"rw/iosystem/devices/{network}/{device}/explicitdata")

async def get_profinet_device_alarms_xml_response(
    client: RWSClient,
    network: str,
    device: str,
) -> httpx.Response:
    """
    Get profinet device alarms xml response.

    Route: ``GET rw/iosystem/devices/{network}/{device}/alarms``
    ABB constraints: Not supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        network: URL path parameter.
        device: URL path parameter.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: NOT_ACCEPTABLE(406)

    Example:
        # curl --digest -u "Default User":robotics
            "http://localhost/rw/iosystem/devices/PROFINET/PN_Internal_Device/alarms"
    """
    return await client.get(f"rw/iosystem/devices/{network}/{device}/alarms")

async def post_clear_the_alarms(
    client: RWSClient,
    network: str,
    device: str,
) -> httpx.Response:
    """
    Clear the alarms.

    Route: ``POST rw/iosystem/devices/{network}/{device}/alarms/clear``
    ABB constraints: Not supported in bootserver mode.

    Args:
        client: Open RWSClient instance.
        network: URL path parameter.
        device: URL path parameter.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: NOT_ACCEPTABLE(406)

    Example:
        # curl --digest -u "Default User":robotics -d POST
            "http://localhost/rw/iosystem/devices/PROFINET/PN_Internal_Device/alarm
    """
    return await client.post(f"rw/iosystem/devices/{network}/{device}/alarms/clear")

async def get_forms_3(
    client: RWSClient,
    network: str,
    device: str,
) -> httpx.Response:
    """
    Get Forms.

    Route: ``OPTIONS rw/iosystem/devices/{network}/{device}/alarms/clear``
    ABB constraints: Not supported in bootserver mode.

    Args:
        client: Open RWSClient instance.
        network: URL path parameter.
        device: URL path parameter.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: NOT_ACCEPTABLE(406) See

    Example:
        # curl --digest -u "Default User":robotics -X OPTIONS
            "http://localhost/rw/iosystem/devices/PROFINET/PN_Internal_Device/al
    """
    return await client.options(f"rw/iosystem/devices/{network}/{device}/alarms/clear")
