# This file is AUTO-GENERATED by contrib/generator/main.py
# DO NOT EDIT MANUALLY — run the generator to regenerate.
"""
RWS module : Root Resource → Get Service list

Miroir 1:1 de l'API REST ABB RobotWare 6.
Chaque fonction correspond à exactement un endpoint HTTP.
Aucune logique composée — voir highlevel/ pour les wrappers.
"""
from __future__ import annotations

import httpx

from abb_rws_client._core.client import RWSClient


async def get_service_list(client: RWSClient) -> httpx.Response:
    """
    Get Service list.

    Route: ``GET /``
    Contraintes ABB: Supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 200.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD_REQUEST(400)

    Example:
        # curl --digest -u "Default User":robotics "http://localhost/"
    """
    return await client.get("/")

async def logout(client: RWSClient) -> httpx.Response:
    """
    Logout.

    Route: ``GET /logout``
    Contraintes ABB: Supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 204.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD_REQUEST(400)

    Example:
        # curl --digest -u "Default User":robotics "http://localhost/logout"
    """
    return await client.get("/logout")
