# This file is AUTO-GENERATED by utils/generator/main.py
# DO NOT EDIT MANUALLY — run the generator to regenerate.
#  Generator author: Clement RACINET
"""
RWS module: User Service → Operations on Remote User → Get remote user actions

1:1 mirror of the ABB RobotWare 6 REST API.
Each function maps to exactly one HTTP endpoint.
No composed logic — see highlevel/ for wrappers.
"""
from __future__ import annotations

import httpx

from abb_rws_client.core.client import RWSClient


async def get_remote_user_actions(
    client: RWSClient,
    action: str | None = None,
) -> httpx.Response:
    """
    Get remote user actions.

    Route: ``GET /users/remoteuser``
    ABB constraints: Not Supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        action: Query parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD REQUEST(400), FORBIDDEN(403), UNAUTHORIZED(401)

    Example:
        ```python
        >>> await get_remote_user_actions(client)
        <Response [200]>
        ```
    """
    return await client.get(
        "/users/remoteuser",
        params={k: v for k, v in {"action": action}.items() if v is not None},
    )

async def post_remote_user_logon_request(
    client: RWSClient,
    action: str | None = None,
) -> httpx.Response:
    """
    Remote User Logon Request.

    Route: ``POST /users/remoteuser``
    ABB constraints: Not Supported in bootserver mode. The UAS grant UAS_REMOTE_LOGIN is
        required.

    Args:
        client: Open RWSClient instance.
        action: Query parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 204.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD REQUEST(400), FORBIDDEN(403), UNAUTHORIZED(401)

    Example:
        ```python
        >>> await post_remote_user_logon_request(client)
        <Response [204]>
        ```
    """
    return await client.post(
        "/users/remoteuser",
        params={k: v for k, v in {"action": action}.items() if v is not None},
        data={},
    )

async def post_remote_user_logout_request(
    client: RWSClient,
    action: str | None = None,
) -> httpx.Response:
    """
    Remote User Logout Request.

    Route: ``POST /users/remoteuser``
    ABB constraints: Not Supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        action: Query parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 204.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD REQUEST(400), FORBIDDEN(403), UNAUTHORIZED(401)

    Example:
        ```python
        >>> await post_remote_user_logout_request(client)
        <Response [204]>
        ```
    """
    return await client.post(
        "/users/remoteuser",
        params={k: v for k, v in {"action": action}.items() if v is not None},
        data={},
    )

async def subscribe_on_remote_user_state(
    client: RWSClient,
    identifier: str | None = None,
    identifier_p: str | None = None,
) -> httpx.Response:
    """
    Subscribe on remote user state.

    Route: ``POST /subscription``
    ABB constraints: Not supported in bootserver mode.

    Args:
        client: Open RWSClient instance.
        identifier: Body parameter. Optional.
        identifier_p: Body parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 201.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: UNSUPPORTED_MEDIA(415), BAD_REQUEST(400)

    Example:
        ```python
        >>> await subscribe_on_remote_user_state(client)
        <Response [201]>
        ```
    """
    return await client.post(
        "/subscription",
        data={
            k: v
            for k, v in {
                "identifier": identifier,
                "identifier_p": identifier_p
            }.items()
            if v is not None
        },
    )
