# This file is AUTO-GENERATED by contrib/generator/main.py
# DO NOT EDIT MANUALLY — run the generator to regenerate.
#  Generator author: Clement RACINET
"""
RWS module: User Service → Operations on RMMP → Get RMMP state

1:1 mirror of the ABB RobotWare 6 REST API.
Each function maps to exactly one HTTP endpoint.
No composed logic — see highlevel/ for wrappers.
"""
from __future__ import annotations

import httpx

from abb_rws_client._core.client import RWSClient


async def get_rmmp_state(client: RWSClient) -> httpx.Response:
    """
    Get RMMP state.

    Route: ``GET /users/rmmp``
    ABB constraints: Not Supported in bootserver mode

    Args:
        client: Open RWSClient instance.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.

    Example:
        ```python
        >>> await get_rmmp_state(client)
        <Response [200]>
        ```
    """
    return await client.get("/users/rmmp")

async def get_rmmp_actions(
    client: RWSClient,
    action: str | None = None,
) -> httpx.Response:
    """
    Get RMMP Actions.

    Route: ``GET /users/rmmp``
    ABB constraints: Not Supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        action: Query parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.

    Example:
        ```python
        >>> await get_rmmp_actions(client)
        <Response [200]>
        ```
    """
    return await client.get(
        "/users/rmmp",
        params={k: v for k, v in {"action": action}.items() if v is not None},
    )

async def request_rmmp(client: RWSClient) -> httpx.Response:
    """
    Request RMMP.

    Route: ``POST /users/rmmp``
    ABB constraints: Not Supported in bootserver mode

    Args:
        client: Open RWSClient instance.

    Returns:
        Raw HTTP response. Expected success: HTTP 202.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: UNSUPPORTED_MEDIA(415), BAD_REQUEST(400)

    Example:
        ```python
        >>> await request_rmmp(client)
        <Response [202]>
        ```
    """
    return await client.post("/users/rmmp")

async def grant_or_deny_an_rmmp_request(
    client: RWSClient,
    action: str | None = None,
) -> httpx.Response:
    """
    Grant or deny an RMMP request.

    Route: ``POST /users/rmmp``
    ABB constraints: Not Supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        action: Query parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 204.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: UNSUPPORTED_MEDIA(415), BAD_REQUEST(400)

    Example:
        ```python
        >>> await grant_or_deny_an_rmmp_request(client)
        <Response [204]>
        ```
    """
    return await client.post(
        "/users/rmmp",
        params={k: v for k, v in {"action": action}.items() if v is not None},
    )

async def cancel_held_or_requested_rmmp(
    client: RWSClient,
    action: str | None = None,
) -> httpx.Response:
    """
    Cancel held or requested RMMP.

    Route: ``POST /users/rmmp``
    ABB constraints: Not Supported in bootserver mode

    Args:
        client: Open RWSClient instance.
        action: Query parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 204.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.

    Example:
        ```python
        >>> await cancel_held_or_requested_rmmp(client)
        <Response [204]>
        ```
    """
    return await client.post(
        "/users/rmmp",
        params={k: v for k, v in {"action": action}.items() if v is not None},
    )

async def subscribe_on_rmmp_request_event(
    client: RWSClient,
    identifier: str | None = None,
    identifier_p: str | None = None,
) -> httpx.Response:
    """
    Subscribe on RMMP Request event.

    Route: ``POST /subscription``
    ABB constraints: Not supported in bootserver mode.

    Args:
        client: Open RWSClient instance.
        identifier: Body parameter. Optional.
        identifier_p: Body parameter. Optional.

    Returns:
        Raw HTTP response. Expected success: HTTP 201.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: UNSUPPORTED_MEDIA(415), BAD_REQUEST(400)

    Example:
        ```python
        >>> await subscribe_on_rmmp_request_event(client)
        <Response [201]>
        ```
    """
    return await client.post(
        "/subscription",
        data={
            k: v
            for k, v in {
                "identifier": identifier,
                "identifier_p": identifier_p
            }.items()
            if v is not None
        },
    )

async def poll_for_rmmp_grant_status(client: RWSClient) -> httpx.Response:
    """
    Poll for RMMP grant status.

    Route: ``GET /users/rmmp/poll``
    ABB constraints: Not Supported in bootserver mode

    Args:
        client: Open RWSClient instance.

    Returns:
        Raw HTTP response. Expected success: HTTP 200.

    Raises:
        RWSAuthenticationError: On HTTP 401.
        RWSNotFoundError: On HTTP 404.
        RWSHTTPError: On any other HTTP >= 400.
        # ABB codes: BAD REQUEST(400)

    Example:
        ```python
        >>> await poll_for_rmmp_grant_status(client)
        <Response [200]>
        ```
    """
    return await client.get("/users/rmmp/poll")
