# This file is AUTO-GENERATED by contrib/generator/main.py
# DO NOT EDIT MANUALLY — run the generator to regenerate.
"""
RWS module : User Service → Operations on RMMP → Get RMMP state

Miroir 1:1 de l'API REST ABB RobotWare 6.
Chaque fonction correspond à exactement un endpoint HTTP.
Aucune logique composée — voir highlevel/ pour les wrappers.
"""
from __future__ import annotations

import httpx

from abb_rws_client._core.client import RWSClient


async def get_rmmp_state(client: RWSClient) -> httpx.Response:
    """
    Get RMMP state.

    Route: ``GET /users/rmmp``
    Contraintes ABB: Not Supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 200.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.

    Example:
        # Get RMMP state
    """
    return await client.get("/users/rmmp")

async def get_rmmp_actions(
    client: RWSClient,
    action: str | None = None,
) -> httpx.Response:
    """
    Get RMMP Actions.

    Route: ``GET /users/rmmp``
    Contraintes ABB: Not Supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        action: Paramètre query. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 200.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.

    Example:
        # curl --digest -u "Default User":robotics "http://localhost/users/rmmp?action=show"
    """
    return await client.get("/users/rmmp", params={k: v for k, v in {"action": action}.items() if v is not None})

async def request_rmmp(client: RWSClient) -> httpx.Response:
    """
    Request RMMP.

    Route: ``POST /users/rmmp``
    Contraintes ABB: Not Supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 202.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: UNSUPPORTED_MEDIA(415), BAD_REQUEST(400)

    Example:
        # Grant RMMP
    """
    return await client.post("/users/rmmp")

async def grant_or_deny_an_rmmp_request(
    client: RWSClient,
    action: str | None = None,
) -> httpx.Response:
    """
    Grant or deny an RMMP request.

    Route: ``POST /users/rmmp``
    Contraintes ABB: Not Supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        action: Paramètre query. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 204.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: UNSUPPORTED_MEDIA(415), BAD_REQUEST(400)

    Example:
        # Grant RMMP
    """
    return await client.post("/users/rmmp", params={k: v for k, v in {"action": action}.items() if v is not None})

async def cancel_held_or_requested_rmmp(
    client: RWSClient,
    action: str | None = None,
) -> httpx.Response:
    """
    Cancel held or requested RMMP.

    Route: ``POST /users/rmmp``
    Contraintes ABB: Not Supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        action: Paramètre query. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 204.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.

    Example:
        # Cancel held rmmp
    """
    return await client.post("/users/rmmp", params={k: v for k, v in {"action": action}.items() if v is not None})

async def subscribe_on_rmmp_request_event(
    client: RWSClient,
    identifier: str | None = None,
    identifier_p: str | None = None,
) -> httpx.Response:
    """
    Subscribe on RMMP Request event.

    Route: ``POST /subscription``
    Contraintes ABB: Not supported in bootserver mode.

    Args:
        client: Instance RWSClient ouverte.
        identifier: Paramètre body. Optionnel.
        identifier_p: Paramètre body. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 201.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: UNSUPPORTED_MEDIA(415), BAD_REQUEST(400)

    Example:
        # only low priority subscription(-p=0) and medium priority subscription(-p=1) are allowed on this resource
    """
    return await client.post("/subscription", data={k: v for k, v in {"identifier": identifier, "identifier_p": identifier_p}.items() if v is not None})

async def poll_for_rmmp_grant_status(client: RWSClient) -> httpx.Response:
    """
    Poll for RMMP grant status.

    Route: ``GET /users/rmmp/poll``
    Contraintes ABB: Not Supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 200.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD REQUEST(400)

    Example:
        # poll for rmmp status
    """
    return await client.get("/users/rmmp/poll")
