# This file is AUTO-GENERATED by contrib/generator/main.py
# DO NOT EDIT MANUALLY — run the generator to regenerate.
"""
RWS module : User Service → Get User Resources

Miroir 1:1 de l'API REST ABB RobotWare 6.
Chaque fonction correspond à exactement un endpoint HTTP.
Aucune logique composée — voir highlevel/ pour les wrappers.
"""
from __future__ import annotations

import httpx

from abb_rws_client._core.client import RWSClient


async def get_user_resources(
    client: RWSClient,
    user_type: str | None = None,
) -> httpx.Response:
    """
    Get User Resources.

    Route: ``GET /users``
    Contraintes ABB: Supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        user_type: Paramètre query. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 200.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.

    Example:
        # curl --digest -u "Default User":robotics "http://localhost/users"
    """
    return await client.get("/users", params={k: v for k, v in {"user_type": user_type}.items() if v is not None})

async def get_user_actions(
    client: RWSClient,
    action: str | None = None,
) -> httpx.Response:
    """
    Get User Actions.

    Route: ``GET /users``
    Contraintes ABB: Supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        action: Paramètre query. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 200.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD_REQUEST(400)

    Example:
        # curl --digest -u "Default User":robotics "http://localhost/users?action=show"
    """
    return await client.get("/users", params={k: v for k, v in {"action": action}.items() if v is not None})

async def register_the_user(client: RWSClient) -> httpx.Response:
    """
    Register the user.

    Route: ``POST /users``
    Contraintes ABB: Supported in bootserver mode. Given username, application and location are used only as free-text information. User can be registered as local client (ulocale=local) only if the request comes from service port or the TPU port.

    Args:
        client: Instance RWSClient ouverte.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 201.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: UNSUPPORTED_MEDIA(415), BAD_REQUEST(400)

    Example:
        # Register user
    """
    return await client.post("/users")

async def impersonate_user(
    client: RWSClient,
    action: str | None = None,
) -> httpx.Response:
    """
    Impersonate a user.

    Route: ``POST /users``
    Contraintes ABB: Supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        action: Paramètre query. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 200.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: BAD_REQUEST(400), FORBIDDEN(403)

    Example:
        # Register user
    """
    return await client.post("/users", params={k: v for k, v in {"action": action}.items() if v is not None})

async def login_as_local_user(
    client: RWSClient,
    action: str | None = None,
    type: str | None = None,
) -> httpx.Response:
    """
    Login as Local User.

    Route: ``POST /users``
    Contraintes ABB: Supported in bootserver mode

    Args:
        client: Instance RWSClient ouverte.
        action: Paramètre query. Optionnel.
        type: Paramètre body. Optionnel.

    Returns:
        Réponse HTTP brute. Succès attendu : HTTP 200.

    Raises:
        RWSAuthenticationError: Sur HTTP 401.
        RWSNotFoundError: Sur HTTP 404.
        RWSHTTPError: Sur tout autre HTTP >= 400.
        # Codes ABB: CONFLICT(409) : if the user has already logged in as remote or local client and sets the type as remote or local respectively.

    Example:
        # Login as local user
    """
    return await client.post("/users", params={k: v for k, v in {"action": action}.items() if v is not None}, data={k: v for k, v in {"type": type}.items() if v is not None})
